force-app/main/default/objects/Web_Forecast__c/Web_Forecast__c.object-meta.xml
<CustomObject>
    <label>Web Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast__c/fields/Week1__c.field-meta.xml
<CustomField>
    <fullName>Week1__c</fullName>
    <formula>Week_Start_Date__c - VALUE(CASE( 
MOD(  Week_Start_Date__c - DATE( 1900, 1, 7 ), 7 ), 
0, &quot;0&quot;, 
1, &quot;1&quot;, 
2, &quot;2&quot;, 
3, &quot;3&quot;, 
4, &quot;4&quot;, 
5, &quot;5&quot;, 
&quot;6&quot; 
)) + 49</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/Web_Forecast_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Web Forecast Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Web Forecast Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Forecast Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Web_Forecast_Header__c.field-meta.xml
<CustomField>
    <fullName>Web_Forecast_Header__c</fullName>
    <label>Web_Forecast_Header</label>
    <referenceTo>Web_Forecast__c</referenceTo>
    <relationshipLabel>Web Forecast Line Items</relationshipLabel>
    <relationshipName>Web_Forecast_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Week1__c.field-meta.xml
<CustomField>
    <fullName>Week1__c</fullName>
    <formula>Web_Forecast_Header__r.Week_Start_Date__c -  VALUE(CASE(
  MOD( Web_Forecast_Header__r.Week_Start_Date__c - DATE( 1900, 1, 7 ), 7 ),
  0, &quot;0&quot;,
  1, &quot;1&quot;,
  2, &quot;2&quot;,
  3, &quot;3&quot;,
  4, &quot;4&quot;,
  5, &quot;5&quot;, 
  &quot;6&quot;
)) + 49</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WebForecastLineItem_Controller.cls
/**
 * Created by jirala on 2/6/2018.
 */

public with sharing class WebForecastLineItem_Controller {

    private ApexPages.StandardController con;
    public List<String> Weeklabels {get;set;}
    public Id HeaderId;
    public Id LineItemId;
    public String retURL;
    public String mode {get;set;}

    public WebForecastLineItem_Controller(ApexPages.StandardController controller) {
        con = controller;

        LineItemId = ApexPages.currentPage().getParameters().get('Id');
        map<string, string> pageParameters = ApexPages.currentPage().getParameters();

        if(LineItemId == null){
            // NEW (create mode)
            mode = 'edit';
            HeaderId = ApexPages.currentPage().getParameters().get(Label.WebforecastHeaderFieldId);
        } else if(pageParameters.get('retUrl') != null){
            // Update (Edit mode)
            mode = 'edit';
            Web_Forecast_Line_Item__c item = [SELECT Id,Web_Forecast_Header__c  FROM Web_Forecast_Line_Item__c where Id = :LineItemId];
            HeaderId = item.Web_Forecast_Header__c;
        } else {
            mode = 'view';
            Web_Forecast_Line_Item__c item = [SELECT Id,Web_Forecast_Header__c FROM Web_Forecast_Line_Item__c where Id = :LineItemId];
            HeaderId = item.Web_Forecast_Header__c;
        }
        System.debug('####mode--> '+mode);
        retURL = ApexPages.currentPage().getParameters().get('retURL');

        if(retURL == null)retURL = '/'+HeaderId;

        system.debug('ApexPages.currentPage().getParameters()-->'+ApexPages.currentPage().getParameters());
        system.debug('ApexPages.currentPage()-->'+ApexPages.currentPage());

        if(HeaderId != null){
            Web_Forecast__c header = [select Id, Week1__c from Web_Forecast__c where Id = :HeaderId];
            Weeklabels = new  List<String>();
            for (Integer i = 0; i <= 25; i++) {
                Weeklabels.add('Week '+(i+1)+' ('+header.Week1__c.addDays(7*i).format()+')');
            }
        }
    }
     public PageReference gotoHeader(){
        PageReference RetPage = new PageReference(retURL);
        RetPage.setRedirect(true);
        return RetPage;
    }
}