force-app/main/default/objects/CommonCarrierOverrideZipcode__c/CommonCarrierOverrideZipcode__c.object-meta.xml
<CustomObject>
    <label>CommonCarrierOverrideZipcode</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>CommonCarrierZipcodeOverride Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CommonCarrierOverrideZipcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommonCarrierOverrideZipcode__c/fields/PLANT__c.field-meta.xml
<CustomField>
    <fullName>PLANT__c</fullName>
    <label>PLANT</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommonCarrierOverrideZipcode__c/fields/USLOC__c.field-meta.xml
<CustomField>
    <fullName>USLOC__c</fullName>
    <label>USLOC</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Fulfillment_Type__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Type__c</fullName>
    <label>Fulfillment Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <description>Common carrier store location</description>
    <label>Location Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchUpdateQuoteCC.cls
global class BatchUpdateQuoteCC implements Database.Batchable<sObject>, Database.Stateful{
      global final String Query;

   global BatchUpdateQuoteCC(){
       Query = 'Select Id, SBQQ__ShippingPostalCode__c, Fulfillment_Type__c, Location_Number__c ' 
           + '  FROM SBQQ__Quote__c ' 
           + ' WHERE Fulfillment_Type__c=null AND Location_Number__c=null ORDER BY LastModifiedDate DESC ' ;
     //      + ' WHERE Id IN ' 
     //      + '(\'a2i560000031rZlAAI\') ';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<SBQQ__Quote__c> lstQuoteZip ){
       
       Integer cnt_QuoteZip = lstQuoteZip.size();
       system.debug('cnt_QuoteZip --> ' + cnt_QuoteZip );
       
       
       Set<String> setQuoteZip = new Set<String>();
       
       for(SBQQ__Quote__c zip:lstQuoteZip){
           setQuoteZip.add(zip.SBQQ__ShippingPostalCode__c);
           cnt_QuoteZip++;
       }
   //    system.debug('setQuoteZip --> ' + setQuoteZip );
       
       List<CommonCarrierOverrideZipcode__c> lstCCOZ = new List<CommonCarrierOverrideZipcode__c>();
       lstCCOZ = [SELECT Id, Name, Zipcode__c, PLANT__c, USLOC__c FROM CommonCarrierOverrideZipcode__c where Zipcode__c IN: setQuoteZip];
 //      system.debug('lstCCOZ --> ' + lstCCOZ );
       
       
       Map<String, String> mapFulType = new Map<String, String>();
       Map<String, String> mapLocNum = new Map<String, String>();
       
       for(CommonCarrierOverrideZipcode__c cc:lstCCOZ){
           mapFulType.put(cc.Zipcode__c, cc.PLANT__c);
           mapLocNum.put(cc.Zipcode__c, cc.USLOC__c);
       }
       
   //    system.debug('mapFulType--> ' + mapFulType );
   //    system.debug('mapLocNum--> ' + mapLocNum );
       
       for(SBQQ__Quote__c zp:lstQuoteZip){
           zp.Fulfillment_Type__c = mapFulType.get(zp.SBQQ__ShippingPostalCode__c);
           zp.Location_Number__c = mapLocNum.get(zp.SBQQ__ShippingPostalCode__c);
       }
       
  //     system.debug('lstQuoteZip--> ' + lstQuoteZip );
       
       
       update lstQuoteZip;
       
       
   }

   global void finish(Database.BatchableContext BC){
   }

}