force-app/main/default/objects/Order/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Parent_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part_Number__c</fullName>
    <label>Parent Part Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Unique_Value__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value__c</fullName>
    <externalId>true</externalId>
    <label>Unique Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Parent_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part_Number__c</fullName>
    <label>Parent Part Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchUpdateUniqueOLI.cls
global class BatchUpdateUniqueOLI implements Database.Batchable<sObject>, Database.Stateful{
    global final String Query;
    
    global BatchUpdateUniqueOLI(){
        Query = 'SELECT Id, Product2Id, Product2.ProductCode, OrderId, ' 
            + '  Order.Order_Reference_Number__c, Unique_Value__c, ' 
            + '  Parent_Part_Number__c, Number__c ' 
            + '  FROM OrderItem ' 
            + ' WHERE Order.Order_Reference_Number__c!=null AND Order.Status NOT IN (\'Completed\', \'Done\') ' ;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<OrderItem> lstOIUpdate ){
        List<OrderItem> lstOrderItem = new List<OrderItem>();
        lstOrderItem = [SELECT Id, Product2Id, Product2.ProductCode, OrderId, 
                        Order.Order_Reference_Number__c, Unique_Value__c, 
                        Parent_Part_Number__c, Number__c 
                        FROM OrderItem 
                        WHERE Order.Order_Reference_Number__c!= null AND Order.Status NOT IN ('Completed', 'Done') 
                       ];
        
        Map<String, String> mapParentCode = new Map<String, String>();
        
        for(OrderItem oi:lstOrderItem){
            if(oi.Parent_Part_Number__c=='0' || oi.Parent_Part_Number__c==null){
                mapParentCode.put(oi.Order.Order_Reference_Number__c + oi.Number__c, oi.Product2.ProductCode );
            }
        }
        
        system.debug('lstOrderItem.size() --> ' + lstOrderItem.size() );
        system.debug('mapParentCode.size() --> ' + mapParentCode.size() );
        
        for(OrderItem oiu:lstOIUpdate){
            if(oiu.Parent_Part_Number__c=='0' || oiu.Parent_Part_Number__c==null){
                oiu.Unique_Value__c = oiu.Order.Order_Reference_Number__c + oiu.Product2.ProductCode;
            }else if(oiu.Parent_Part_Number__c!='0' && oiu.Parent_Part_Number__c!=null){
                oiu.Unique_Value__c = oiu.Order.Order_Reference_Number__c + oiu.Product2.ProductCode + mapParentCode.get(oiu.Order.Order_Reference_Number__c + oiu.Parent_Part_Number__c) ;
            }
        }
        system.debug('lstOIUpdate.size() --> ' + lstOIUpdate.size() );
        update lstOIUpdate;
        
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}