force-app/main/default/objects/Order/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <label>Territory Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name__c</fullName>
    <label>District Manager Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name_Short__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name_Short__c</fullName>
    <label>District Manager Name Short</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/District_Manager_Number__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Number__c</fullName>
    <label>District Manager Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/District_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>District_Territory_ID__c</fullName>
    <description>This field represents the 4 digit District ID.</description>
    <label>District Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Region_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Region_Territory_ID__c</fullName>
    <label>Region Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Search_Term1__c.field-meta.xml
<CustomField>
    <fullName>Search_Term1__c</fullName>
    <label>Search Term1</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Upper_District_short_name__c.field-meta.xml
<CustomField>
    <fullName>Upper_District_short_name__c</fullName>
    <formula>UPPER(District_Manager_Name_Short__c)</formula>
    <label>Upper District short name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_Exception__c/Territory_Exception__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Territory Exception</label>
</CustomObject>

force-app/main/default/objects/Territory_Exception__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>Salesforce user Id - This will be used to fill in the SFDC_User_Id__c on the Territory table</description>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_Exception__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Used to match values in the territory object -- dependent on corresponding Field</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DISTRICT_MGR_NAME__c.field-meta.xml
<CustomField>
    <fullName>DISTRICT_MGR_NAME__c</fullName>
    <label>District Manager Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DISTRICT_MGR_NO__c.field-meta.xml
<CustomField>
    <fullName>DISTRICT_MGR_NO__c</fullName>
    <label>District Manager No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/District_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>District_Territory_ID__c</fullName>
    <label>District Territory</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Region_Territory_ID__c</fullName>
    <label>Region Territory</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SEARCH_TERM1__c.field-meta.xml
<CustomField>
    <fullName>SEARCH_TERM1__c</fullName>
    <label>SEARCH_TERM1</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Upper_Name__c.field-meta.xml
<CustomField>
    <fullName>Upper_Name__c</fullName>
    <formula>UPPER(FirstName&amp;&#39; &#39;&amp;LastName)</formula>
    <label>Upper Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryHandler.cls
public without sharing class TerritoryHandler implements ITrigger {/*
    List<Territory__c> territoriesToDelete = new List<Territory__c>();
    List<Territory__c> territoryCache = new List<Territory__c>();   
    List<String> territoryUsers = new List<String>();
    List<String> territoryManagerNames = new List<String>();
    MAP<String, User> territoryManagerCache = new MAP<String, User>();
    MAP<String,User> territoryUserCache = new MAP<String,User>();
    Map<String, User> usersToUpdate = new Map<String, User>();
    //Tests failed since i create all data dynamically and the query never pulled records to delete. So i adjust the search date depending on what mode we're in.
    Datetime dt = Test.isRunningTest() ? Datetime.now().addMinutes(2) : Datetime.now().addMinutes(-2);
    Map<String, Id> EnterpriseIdUserIdMap = new Map<String, Id>();
    Map<String, Id> DistrictManagerUserIdMap = new Map<String, Id>();
    List<Territory_Exception__c> TerritoryExceptions = Territory_Exception__c.getall().values();
*/
    public TerritoryHandler() {     
    }

    public void bulkBefore(){/*
        if(!Trigger.isDelete){ 
            territoryCache  = [SELECT Id, CreatedDate FROM Territory__c WHERE CreatedDate < :dt ];

            for (User user : [SELECT Id, Sears_Enterprise_Id__c, Name, Upper_Name__c  FROM User WHERE UserType = 'Standard' AND IsActive = True ORDER BY IsActive DESC]) {
                if(!String.isBlank(user.Sears_Enterprise_id__c)) {
                    EnterpriseIdUserIdMap.put(user.Sears_Enterprise_Id__c, user.Id);
                }
                DistrictManagerUserIdMap.put(user.Upper_Name__c, user.Id);
            }
        }*/
    }

    public void bulkAfter(){  /* 
        if(!Trigger.isDelete){ 
            for (territory__c newterr : (List<Territory__c>)Trigger.new) {
                territoryUsers.add(newterr.SFDC_USER_ID__c);
                territoryManagerNames.add(newterr.District_Manager_Name_Short__c);
            }
            
            for(User user :[SELECT Id, Territory_ID__c, Territory_Name__c, District_Territory_ID__c, District_Name__c, Region__c, Region_Name__c, DISTRICT_MGR_NO__c, DISTRICT_MGR_NAME__c, SEARCH_TERM1__c FROM User WHERE id IN :territoryUsers]){
                territoryUserCache.put(user.Id, user);
            }

            for(User manager :[SELECT Id, Name FROM User WHERE Name IN :territoryManagerNames]){                
                territoryManagerCache.put(manager.Name.toLowerCase(), manager);
            }

            System.debug('***** Managers: ' + territoryManagerCache.values());
        }*/
    }

    public void beforeInsert(Sobject obj){
   //     territoriesToDelete = territoryCache;
   //     updateSFDCUserId((Territory__c)obj);
    }

    public void beforeUpdate(Sobject oldObj, Sobject newObj){
  //      updateSFDCUserId((Territory__c)newObj);
    }

    public  void beforeDelete(Sobject obj){

    }

    public void afterInsert(Sobject obj){
  //      Territory__c territoryObj = (Territory__c)obj;
  //      updateTerritoryIDforUser(territoryObj);
  //      updateManager(territoryObj);
    }

    public void afterUpdate(Sobject oldObj, Sobject newObj){
   //     Territory__c territoryObj = (Territory__c)newObj;
   //     updateTerritoryIDforUser(territoryObj);
   //     updateManager(territoryObj);
    }

    public void afterDelete(Sobject obj){

    }

    public void andFinally(){/*
        try{
            if(territoriesToDelete.size() > 0){
                delete territoriesToDelete;
            }
            if (usersToUpdate.size() > 0) {
                update usersToUpdate.values();
                System.debug('***** updating: ' + usersToUpdate.values());
            }
        }
        catch(DmlException de){
            System.debug(de);
        }
        catch(Exception e){
            System.debug(e);
        }*/
    }

/*
    // ***************************Helper Methods******************************
    private void updateTerritoryIDforUser(Territory__c territory){
        //System.debug('***** Start updateTerritoryIDforUser()');
        if(territoryUserCache.containskey(territory.SFDC_USER_ID__c)){
            User user = territoryUserCache.get(territory.SFDC_USER_ID__c);
            //System.debug('***** Updating Territory for User: ' + user.Id);
            user.Territory_ID__c = territory.Territory_ID__c;
            user.Territory_Name__c = territory.Name;
            user.District_Territory_ID__c = territory.District_Territory_ID__c;
            user.District_Name__c = territory.District_Name__c;
            user.Region__c = territory.Region_Territory_ID__c;
            user.Region_Name__c = territory.Region_Name__c;
            user.DISTRICT_MGR_NO__c = territory.District_Manager_Number__c;
            user.DISTRICT_MGR_NAME__c = territory.District_Manager_Name__c;
            user.SEARCH_TERM1__c = territory.Search_Term1__c;
            usersToUpdate.put(user.Id, user);
        }       
        //System.debug('***** End updateTerritoryIDforUser()');
    }
    //before insert, before update
    private void updateSFDCUserId(territory__c territory){
        System.debug('***** tenterprise: ' + territory.Enterprise_ID__c);
        if (EnterpriseIdUserIdMap.containskey(territory.Enterprise_ID__c)) {
            territory.SFDC_User_ID__c = EnterpriseIdUserIdMap.get(territory.Enterprise_ID__c);
            System.debug('***** updatesfdcuserid ' + EnterpriseIdUserIdMap.get(territory.Enterprise_ID__c));
        } 
        else if (DistrictManagerUserIdMap.containskey(territory.Upper_District_short_name__c)) {
            territory.SFDC_User_ID__c = DistrictManagerUserIdMap.get(territory.Upper_District_short_name__c);
        }
        else {
          for(Territory_Exception__c te: TerritoryExceptions) {
            if(territory.get(te.Field__c) == te.Value__c) {
              territory.SFDC_USER_ID__c = te.User_Id__c;
            }
            }
        }
    }

    private void updateManager(Territory__c territory){
        System.debug('***** updateManager() start');
        if(String.isNotBlank(territory.District_Manager_Name_Short__c) && territoryManagerCache.containskey(territory.District_Manager_Name_Short__c.toLowerCase())){           
            User manager = territoryManagerCache.get(territory.District_Manager_Name_Short__c.toLowerCase());
            System.debug('***** manager found: ' + territory.District_Manager_Name_Short__c);
            if(String.isNotBlank(territory.SFDC_USER_ID__c) && territoryUserCache.containskey(territory.SFDC_USER_ID__c)){
                User user = territoryUserCache.get(territory.SFDC_USER_ID__c);
                if(territory.SFDC_USER_ID__c == user.Id){
                    if(user.ManagerId != manager.Id && user.Id != manager.Id && !territory.District_Name__c.containsIgnoreCase('Inside Sales')){
                        if(usersToUpdate.containsKey(user.Id)){
                            //National accounts have a different manager in Salesforce than SAP, skip normal process and auto assign the current manager by using a Labal
                            //The label can be updated on the fly through the normail SF UI
                            usersToUpdate.get(user.Id).ManagerId = territory.District_Name__c.containsIgnoreCase('National Accounts') ? System.Label.National_Account_DM : manager.Id;
                        }
                        else{
                            user.ManagerId = territory.District_Name__c.containsIgnoreCase('National Accounts') ? System.Label.National_Account_DM : manager.Id;
                            usersToUpdate.put(user.Id, user);
                        }
                        
                    }
                }
            }
        }
    }*/
}