force-app/main/default/objects/Order/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <label>Territory Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name_Short__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name_Short__c</fullName>
    <label>District Manager Name Short</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TerritoryTriggerTest.cls
@isTest
private class TerritoryTriggerTest {

	static testmethod void truncateTerritory() {
		Test.startTest();
		List<Territory__c> territories = TestDataFactory.createTerritories(3);
		insert territories;

		List<Territory__c> territoryResult = [SELECT Id FROM Territory__c];
		System.assertEquals(territoryResult.size(), 3);

		List<Territory__c> territories2 = TestDataFactory.createTerritories(5);
		insert territories2;

		territoryResult = [SELECT Id FROM Territory__c];
	//	System.assertEquals(territoryResult.size(), 5);

		delete territories2;
		Test.stopTest();
	}
	
	static testmethod void updateTerritoryIdForUser() {
		Test.startTest();
		List<User> users = TestDataFactory.createUsers(5);
		insert users;

		List<Territory__c> territories = TestDataFactory.createTerritories(3);
		territories[0].SFDC_USER_ID__c = users[0].Id;
		territories[1].SFDC_USER_ID__c = users[1].Id;
		territories[2].SFDC_USER_ID__c = users[2].Id;
		insert territories;

		List<User> userResult = [SELECT Id, Territory_ID__c FROM User WHERE Id = :users[1].Id];
		System.assertEquals(userResult[0].Territory_ID__c, territories[1].Territory_ID__c);

		territories[0].SFDC_USER_ID__c = users[2].Id;
		territories[1].SFDC_USER_ID__c = users[3].Id;
		territories[2].SFDC_USER_ID__c = users[4].Id;
		update territories;

		userResult = [SELECT Id, Territory_ID__c FROM User WHERE Id = :users[4].Id];
		System.assertEquals(userResult[0].Territory_ID__c, territories[2].Territory_ID__c);
		Test.stopTest();
	}

	static testmethod void userManagerUpdate(){
		TestDataFactory.setupCommonVariables();

		Test.startTest();
		List<User> users = TestDataFactory.createUsers(5);		
		User thisUser = [ select Id from User where Id = :UserInfo.getUserId()];
	//	List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'Standard Commercial AM User'];
		List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

		System.runAs ( thisUser ) {
		    insert users;

		    users[0].ManagerId = users[3].Id;
			users[1].ManagerId = users[4].Id;
			users[0].Sears_Enterprise_Id__c = '101010';
			users[1].Sears_Enterprise_Id__c = '202020';
			users[0].ProfileId = profiles[0].Id;
			users[1].ProfileId = profiles[0].Id;
			update users;
		}

		Set<Id> resultIds = (new Map<Id,SObject>(users)).keySet();

		List<User> userResults = [SELECT Id, Name, ManagerId, UserType, IsActive FROM User WHERE Id IN :resultIds ORDER BY Name];
		System.debug('***** UserResults ' + userResults);
		userResults.sort();

		List<Territory__c> territories = TestDataFactory.createTerritories(2);
		territories[0].District_Manager_Name_Short__c = userResults[2].Name;
		territories[0].SFDC_USER_ID__c = userResults[0].Id;
		territories[0].Region_Name__c = 'Sales Operations Region National';
		territories[0].District_Name__c = 'National Accounts District';
		territories[0].Enterprise_ID__c = '101010';
		territories[1].District_Manager_Name_Short__c = userResults[4].Name;
		territories[1].SFDC_USER_ID__c = userResults[1].Id;
		territories[1].Region_Name__c = 'Sales Operations Region West';
		territories[1].District_Name__c = 'Military Accounts District';
		territories[1].Enterprise_ID__c = '202020';
		System.runAs ( thisUser ) {
			insert territories;
		}

		userResults = [SELECT Id, Name, ManagerId FROM User WHERE Id IN :resultIds ORDER BY Name];
		userResults.sort();
		
	//	System.assertEquals(userResults[0].ManagerId, System.Label.National_Account_DM);
	//	System.assertEquals(userResults[1].ManagerId, userResults[4].Id);

		territories[1].District_Manager_Name_Short__c = userResults[3].Name;
		System.runAs ( thisUser ) {
			update territories;
		}
		userResults = [SELECT Id, Name, ManagerId FROM User WHERE Id IN :resultIds ORDER BY Name];
	//	System.assertEquals(userResults[1].ManagerId, userResults[3].Id);


		Test.stopTest();
	}
}