force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Amount_Processed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Processed__c</fullName>
    <label>Release Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Amount_Remaining__c</fullName>
    <formula>Total_Amount__c - Amount_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Billed_Value__c.field-meta.xml
<CustomField>
    <fullName>Billed_Value__c</fullName>
    <label>Billed Value</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <label>Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/isProductParent__c.field-meta.xml
<CustomField>
    <fullName>isProductParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isProductParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Items_Processed__c.field-meta.xml
<CustomField>
    <fullName>Items_Processed__c</fullName>
    <label>Release Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Items_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Items_Remaining__c</fullName>
    <formula>Total_Quantity__c -   Items_Processed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Items Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/ProductParentUnique__c.field-meta.xml
<CustomField>
    <fullName>ProductParentUnique__c</fullName>
    <label>ProductParentUnique</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Expected Total Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Target Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <label>Total Tax Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <inlineHelpText>Solid waste fee/ Disposable fee for North Carolina &amp; South Carolina States</inlineHelpText>
    <label>Solid Waste fee/Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <summarizedField>SBQQ__QuoteLine__c.Total_Tax_Amount__c</summarizedField>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Net_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Price__c</fullName>
    <formula>Net_Unit_Price__c *  SBQQ__Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>List_Price__c - SBQQ__AdditionalDiscountAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <formula>( Tax__c * SBQQ__Quantity__c) + Disposable_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UpdateContractAmendment.cls
public class UpdateContractAmendment {
    
    @InvocableMethod
    public static void quoteBusiensshour_method(List<Id> qId) {
        
        System.debug('qId--> ' + qId);
        
        if(qId!=null){
            
            SBQQ__Quote__c objQuote = new SBQQ__Quote__c();
            
            objQuote = [SELECT Id, Name, SBQQ__MasterContract__c
                        FROM SBQQ__Quote__c 
                        WHERE Id IN: qId
                       ];
            
            if(objQuote.Id!=null && objQuote.SBQQ__MasterContract__c!=null ){
                
                List<SBQQ__QuoteLine__c> lstQuoteLine = new List<SBQQ__QuoteLine__c>();
                lstQuoteLine = [SELECT Id, Name, SBQQ__Product__c, SBQQ__Quantity__c, SBQQ__Quote__c, 
                                List_Price__c, Net_Unit_Price__c, Net_Total_Price__c, Disposable_Fee__c, 
                                isProductParent__c, SBQQ__Number__c, Feature__c,ProductParentUnique__c, Tax_Rate__c,
                                Configuration_Code__c, Configuration_Option__c
                                FROM SBQQ__QuoteLine__c 
                                WHERE SBQQ__Quote__c=:objQuote.Id
                                ORDER BY SBQQ__Number__c
                               ];
                
                List<Contract_Line_Item__c> lstContractLineItem = new List<Contract_Line_Item__c>();
                lstContractLineItem = [SELECT Id, Name, Contract__c, Amount_Processed__c, Amount_Remaining__c, Disposable_Fee__c, 
                                       Feature__c, Items_Processed__c, Items_Remaining__c, List_Unit_Price__c, Net_Unit_Price__c, 
                                       Number__c, ProductParentUnique__c, Product__c, Requested_Delivery_Date__c, Status__c, 
                                       Tax_Rate__c, Total_Amount__c, Total_Quantity__c, isProductParent__c, Configuration_Code__c, 
                                       Configuration_Option__c, Product_Code__c, Tax_Amount__c, Total_Tax_Amount__c, 
                                       Billed_Quantity__c, Billed_Value__c, Shipped_Quantity__c 
                                       FROM Contract_Line_Item__c 
                                       WHERE Contract__c=:objQuote.SBQQ__MasterContract__c
                                      ];
                
                Contract_Line_Item__c objContractLineItem = new Contract_Line_Item__c();
                List<Contract_Line_Item__c> lstContractLineItemUpsert = new List<Contract_Line_Item__c>();
                List<String> lstCLINonDelete = new List<String>();
                
                
                Map<String, Contract_Line_Item__c> mapContractLineItem = new Map<String, Contract_Line_Item__c>();
                Map<String, Boolean> mapIsProcessed = new Map<String, Boolean>();
                Set<String> setIsProcessed = new Set<String>();
                
                String clKey = '';
                String temp_clKey = '';
                
                for(Contract_Line_Item__c cl:lstContractLineItem){
                    System.debug('cl.Product__c--> ' + cl.Product__c + '  ||  cl.ProductParentUnique__c--> ' + cl.ProductParentUnique__c);
                    temp_clKey = cl.Product__c + cl.ProductParentUnique__c;
                    clKey = temp_clKey.substring(0,temp_clKey.length()-6);
              //      mapContractLineItem.put(cl.Product__c + cl.ProductParentUnique__c , cl);
                    mapContractLineItem.put(clKey , cl);
                    if(cl.Items_Processed__c>0 || cl.Amount_Processed__c>0 || cl.Billed_Quantity__c>0 || cl.Billed_Value__c>0 || cl.Shipped_Quantity__c>0 ){
                        setIsProcessed.add(cl.ProductParentUnique__c);
                    }
                }
                
                String qlKey = '';
                String temp_qlKey = '';
                
                for(SBQQ__QuoteLine__c ql:lstQuoteLine){
                    System.debug('ql.SBQQ__Product__c--> ' + ql.SBQQ__Product__c + '  ||  ql.ProductParentUnique__c--> ' + ql.ProductParentUnique__c);
                    objContractLineItem = new Contract_Line_Item__c();
                //    qlKey = ql.SBQQ__Product__c + ql.ProductParentUnique__c;
                    temp_qlKey = ql.SBQQ__Product__c + ql.ProductParentUnique__c;
                    qlKey = temp_qlKey.substring(0,temp_qlKey.length()-6);
                    
                    if(mapContractLineItem.keySet().contains(qlKey)){
                        objContractLineItem.Total_Quantity__c = ql.SBQQ__Quantity__c;
                        objContractLineItem.Total_Amount__c = ql.Net_Total_Price__c;
                        objContractLineItem.Tax_Rate__c = ql.Tax_Rate__c!=null?ql.Tax_Rate__c:0;
                        objContractLineItem.Feature__c = ql.Feature__c;
                        objContractLineItem.Configuration_Code__c = ql.Configuration_Code__c;
                        objContractLineItem.Configuration_Option__c = ql.Configuration_Option__c;
                        objContractLineItem.isProductParent__c = ql.isProductParent__c;
                        objContractLineItem.Number__c = ql.SBQQ__Number__c;
                        objContractLineItem.List_Unit_Price__c = ql.List_Price__c;
                        objContractLineItem.Net_Unit_Price__c = ql.Net_Unit_Price__c;
                        objContractLineItem.Disposable_Fee__c = ql.Disposable_Fee__c;
                        
                        objContractLineItem.Id = mapContractLineItem.get(qlKey).Id;
                        objContractLineItem.Amount_Processed__c = mapContractLineItem.get(qlKey).Amount_Processed__c;
                        //       objContractLineItem.Amount_Remaining__c = mapContractLineItem.get(qlKey).Amount_Remaining__c;
                        objContractLineItem.Items_Processed__c = mapContractLineItem.get(qlKey).Items_Processed__c;
                        //       objContractLineItem.Items_Remaining__c = mapContractLineItem.get(qlKey).Items_Remaining__c;
                        objContractLineItem.Requested_Delivery_Date__c = mapContractLineItem.get(qlKey).Requested_Delivery_Date__c;
                        objContractLineItem.Status__c = mapContractLineItem.get(qlKey).Status__c;
                        objContractLineItem.Billed_Quantity__c = mapContractLineItem.get(qlKey).Billed_Quantity__c;
                        objContractLineItem.Billed_Value__c = mapContractLineItem.get(qlKey).Billed_Value__c;
                        objContractLineItem.Shipped_Quantity__c = mapContractLineItem.get(qlKey).Shipped_Quantity__c;
                        objContractLineItem.Tax_Amount__c = mapContractLineItem.get(qlKey).Tax_Amount__c;
                        objContractLineItem.Total_Tax_Amount__c = mapContractLineItem.get(qlKey).Total_Tax_Amount__c;
                        lstCLINonDelete.add(qlKey);
                        System.debug('objContractLineItem--> ' + objContractLineItem);
                    }else{
                        objContractLineItem.Contract__c = objQuote.SBQQ__MasterContract__c;
                        objContractLineItem.Product__c = ql.SBQQ__Product__c;
                        objContractLineItem.Total_Quantity__c = ql.SBQQ__Quantity__c;
                        objContractLineItem.Total_Amount__c = ql.Net_Total_Price__c;
                        objContractLineItem.Tax_Rate__c = ql.Tax_Rate__c!=null?ql.Tax_Rate__c:0;
                        objContractLineItem.Status__c = 'Open';
                        objContractLineItem.Feature__c = ql.Feature__c;
                        objContractLineItem.Configuration_Code__c = ql.Configuration_Code__c;
                        objContractLineItem.Configuration_Option__c = ql.Configuration_Option__c;
                        objContractLineItem.Items_Processed__c = 0;
                        objContractLineItem.Amount_Processed__c = 0;
                        objContractLineItem.Billed_Quantity__c = 0;
                        objContractLineItem.Billed_Value__c = 0;
                        objContractLineItem.isProductParent__c = ql.isProductParent__c;
                        objContractLineItem.ProductParentUnique__c = ql.ProductParentUnique__c;
                        objContractLineItem.Number__c = ql.SBQQ__Number__c;
                        objContractLineItem.List_Unit_Price__c = ql.List_Price__c;
                        objContractLineItem.Net_Unit_Price__c = ql.Net_Unit_Price__c;
                        objContractLineItem.Disposable_Fee__c = ql.Disposable_Fee__c;
                        System.debug('objContractLineItem--> ' + objContractLineItem);
                    }
                    
                    lstContractLineItemUpsert.add(objContractLineItem);
                    
                    
                    
                }
            
                
                Integer iu_cli = lstContractLineItemUpsert.size();
                List<Contract_Line_Item__c> lstContractLineItemDelete = new List<Contract_Line_Item__c>();
                
                for(String mcli:mapContractLineItem.keySet()){
                    System.debug('mcli--> ' + mcli );
                    if(!lstCLINonDelete.contains(mcli) && setIsProcessed.contains(mapContractLineItem.get(mcli).ProductParentUnique__c) ){
                            iu_cli++;
                            objContractLineItem = new Contract_Line_Item__c();
                            objContractLineItem  = mapContractLineItem.get(mcli);
                            objContractLineItem.Number__c = iu_cli;
                        lstContractLineItemUpsert.add(objContractLineItem);
                        System.debug('mapContractLineItem.get(mcli)--> ' + mapContractLineItem.get(mcli));
                    }else if(!lstCLINonDelete.contains(mcli) && !setIsProcessed.contains(mapContractLineItem.get(mcli).ProductParentUnique__c) ){
                        lstContractLineItemDelete.add(mapContractLineItem.get(mcli));
                        System.debug('mapContractLineItem.get(mcli)--> ' + mapContractLineItem.get(mcli));
                    }
                }
                
                
                upsert lstContractLineItemUpsert;
                System.debug('lstContractLineItemUpsert.size()--> ' + lstContractLineItemUpsert.size());            
                
                
                delete lstContractLineItemDelete;
                System.debug('lstContractLineItemDelete.size()--> ' + lstContractLineItemDelete.size());            
                
            }
            
            
        }
        
        
        
        
    }
    
}