force-app/main/default/objects/FCST_Item_Info__c/FCST_Item_Info__c.object-meta.xml
<CustomObject>
    <description>Forecast Item data</description>
    <label>FCST Item Info</label>
    <nameField>
        <label>FCST Item Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Item Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FCST_Item_Info__c/fields/Dist_Type__c.field-meta.xml
<CustomField>
    <fullName>Dist_Type__c</fullName>
    <label>Dist Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/Item_8721_Stock__c.field-meta.xml
<CustomField>
    <fullName>Item_8721_Stock__c</fullName>
    <label>Item_8721_Stock</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/Item_Num__c.field-meta.xml
<CustomField>
    <fullName>Item_Num__c</fullName>
    <label>Item Num</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transitions_Item__c/Transitions_Item__c.object-meta.xml
<CustomObject>
    <label>Transitions Item</label>
    <nameField>
        <label>Transitions Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transitions Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transitions_Item__c/fields/New_Item__c.field-meta.xml
<CustomField>
    <fullName>New_Item__c</fullName>
    <label>New Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transitions_Item__c/fields/Old_Item__c.field-meta.xml
<CustomField>
    <fullName>Old_Item__c</fullName>
    <label>Old Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/Web_Forecast__c.object-meta.xml
<CustomObject>
    <label>Web Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast__c/fields/Ship_to_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Zipcode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship to Zipcode</label>
    <referenceTo>Zipcode_DDC_RRC__c</referenceTo>
    <relationshipLabel>Web Forecasts</relationshipLabel>
    <relationshipName>Web_Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/Web_Forecast_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Web Forecast Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Web Forecast Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Forecast Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/DDC_Item__c.field-meta.xml
<CustomField>
    <fullName>DDC_Item__c</fullName>
    <label>Servicing DDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <inlineHelpText>Only the major appliance divisions can be forecast:  20, 22, 26 and 46</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>022</fullName>
            </value>
            <value>
                <fullName>026</fullName>
            </value>
            <value>
                <fullName>046</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <inlineHelpText>Only items stocked in the DDC and RRC can be forecast – we cannot accept forecast for EZ Order items</inlineHelpText>
    <label>Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Item_Dist_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Dist_Type__c</fullName>
    <inlineHelpText>DD = DDC / TW = RRC</inlineHelpText>
    <label>Distribution Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Item_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Item_Formatted__c</fullName>
    <label>Item Formatted</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/RRC_Item__c.field-meta.xml
<CustomField>
    <fullName>RRC_Item__c</fullName>
    <label>Servicing RRC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Web_Forecast_Header__c.field-meta.xml
<CustomField>
    <fullName>Web_Forecast_Header__c</fullName>
    <label>Web_Forecast_Header</label>
    <referenceTo>Web_Forecast__c</referenceTo>
    <relationshipLabel>Web Forecast Line Items</relationshipLabel>
    <relationshipName>Web_Forecast_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/Zipcode_DDC_RRC__c.object-meta.xml
<CustomObject>
    <description>Holds all zip codes with DDC &amp; RRC information</description>
    <label>Zipcode DDC RRC</label>
    <nameField>
        <label>Zipcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zipcode DDC RRCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/DDC__c.field-meta.xml
<CustomField>
    <fullName>DDC__c</fullName>
    <label>DDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/RRC__c.field-meta.xml
<CustomField>
    <fullName>RRC__c</fullName>
    <label>RRC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ForecastItemValidations.cls
public class ForecastItemValidations {
    
    public static void ForecastItemBeforeValidations(Web_Forecast_Line_Item__c LineItem) {

        system.debug ('Line item details ' +LineItem);

        if(LineItem.Item__c != null && LineItem.Division__c != null){

        String lv_item = LineItem.Item__c;
        if(LineItem.Item__c.length() == 4) {
            lv_item = lv_item + ' ';
        }

        LineItem.Item_Formatted__c = LineItem.Division__c + '-' + lv_item.rightPad(5, '0') + '-' + '000';
        system.debug('LineItem.Item__c--> '+LineItem.Item_Formatted__c);
        //Get shipto zipcode from header
        //Step1. Validate if it is a valid div/item or not
        //Query FCST_Item table

        Web_Forecast__c header = [select Id, Ship_to_Zipcode__r.name from Web_Forecast__c where Id = :LineItem.Web_Forecast_Header__c];
        system.debug('Header--> '+header);
        FCST_Item_Info__c[] fcstitemdet = [select Dist_Type__c, Item_8721_Stock__c, Status__c from FCST_Item_Info__c where Item_Num__c = :LineItem.Item_Formatted__c];
        system.debug('FCST_Item_Info--> '+fcstitemdet);
        Transitions_Item__c[] transitem = [select Old_Item__c, New_Item__c from Transitions_Item__c where Old_Item__c = :LineItem.Item_Formatted__c];
        system.debug('Transitions_Item--> '+transitem);
        Zipcode_DDC_RRC__c[] DDC_info = [select DDC__c, RRC__c from Zipcode_DDC_RRC__c where Name = :header.Ship_to_Zipcode__r.name];
        system.debug('Zipcode_DDC_RRC--> '+DDC_info);
        LineItem.DDC_Item__c = DDC_info[0].DDC__c;
        LineItem.RRC_Item__c = DDC_info[0].RRC__c;

        //Unique item key


        Web_Forecast_Line_Item__c[] itemuniquequery = [SELECT Id, Item__c FROM Web_Forecast_Line_Item__c where Web_Forecast_Header__c = :header.Id and Item_Formatted__c = :LineItem.Item_Formatted__c
                                                            and id <> :LineItem.Id ];
        system.debug('duplicate item' +itemuniquequery);
        if(itemuniquequery.size() > 0){
            LineItem.Item__c.addError( 'Duplicate item is not allowed. Item has already been entered');
        }

        if(fcstitemdet.size() > 0) {

            if(transitem.size() > 0) {
                //Step2: Is it a Transition item? Query Transitions Item table
                if(transitem[0].Old_Item__c <> transitem[0].New_Item__c) {
                    //raise error message to User saying transition item exists
                    LineItem.Item__c.addError( transitem[0].Old_Item__c+' is discontinued, please use transition item '+transitem[0].New_Item__c.substring(4,9));
                  //  LineItem.addError( transitem[0].Old_Item__c+' is discontinued, please use transition item '+transitem[0].New_Item__c);
                }
            }

            //Step3: Check If DDC = '8721' check FCST_item table, field 8721_stock to determine if set to Yes -- If not change DDC to '8870'
            //Query Zipcode table
            if((DDC_info[0].DDC__c == '8721' && fcstitemdet[0].Item_8721_Stock__c == 'N' )) {
                LineItem.DDC_Item__c = '8870';  //update DDC on header to
            }

            LineItem.Item_Dist_Type__c = fcstitemdet[0].Dist_Type__c;

        } else{
            //Raise error message "Item is not valid"
            LineItem.Item__c.addError('Division/Item Cannot Be Forecast');
        }

    }
    }
    
}