force-app/main/default/objects/FCST_Item_Info__c/FCST_Item_Info__c.object-meta.xml
<CustomObject>
    <description>Forecast Item data</description>
    <label>FCST Item Info</label>
    <nameField>
        <label>FCST Item Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Item Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FCST_Item_Info__c/fields/Dist_Type__c.field-meta.xml
<CustomField>
    <fullName>Dist_Type__c</fullName>
    <label>Dist Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/External_ID_Num__c.field-meta.xml
<CustomField>
    <fullName>External_ID_Num__c</fullName>
    <externalId>true</externalId>
    <label>External ID Num</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/Item_8721_Stock__c.field-meta.xml
<CustomField>
    <fullName>Item_8721_Stock__c</fullName>
    <label>Item_8721_Stock</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/Item_Num__c.field-meta.xml
<CustomField>
    <fullName>Item_Num__c</fullName>
    <label>Item Num</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FCST_Item_Info__c/fields/MDM_Item__c.field-meta.xml
<CustomField>
    <fullName>MDM_Item__c</fullName>
    <label>MDM Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transitions_Item__c/Transitions_Item__c.object-meta.xml
<CustomObject>
    <label>Transitions Item</label>
    <nameField>
        <label>Transitions Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transitions Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transitions_Item__c/fields/Ext_Num__c.field-meta.xml
<CustomField>
    <fullName>Ext_Num__c</fullName>
    <externalId>true</externalId>
    <label>Ext Num</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transitions_Item__c/fields/New_Item__c.field-meta.xml
<CustomField>
    <fullName>New_Item__c</fullName>
    <label>New Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transitions_Item__c/fields/Old_Item__c.field-meta.xml
<CustomField>
    <fullName>Old_Item__c</fullName>
    <label>Old Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/Web_Forecast__c.object-meta.xml
<CustomObject>
    <label>Web Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast__c/fields/District_Manager__c.field-meta.xml
<CustomField>
    <fullName>District_Manager__c</fullName>
    <label>District Manager</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Sales_Rep_Email__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Email__c</fullName>
    <label>Send Email Confirmations to:</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Name__c</fullName>
    <label>Sales Rep Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Sales_Rep_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Number__c</fullName>
    <label>Sales Rep Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Ship_to_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Zipcode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship to Zipcode</label>
    <referenceTo>Zipcode_DDC_RRC__c</referenceTo>
    <relationshipLabel>Web Forecasts</relationshipLabel>
    <relationshipName>Web_Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Week1__c.field-meta.xml
<CustomField>
    <fullName>Week1__c</fullName>
    <formula>Week_Start_Date__c - VALUE(CASE( 
MOD(  Week_Start_Date__c - DATE( 1900, 1, 7 ), 7 ), 
0, &quot;0&quot;, 
1, &quot;1&quot;, 
2, &quot;2&quot;, 
3, &quot;3&quot;, 
4, &quot;4&quot;, 
5, &quot;5&quot;, 
&quot;6&quot; 
)) + 49</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Web_Forecast__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Date Submitted</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/Web_Forecast_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Web Forecast Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Web Forecast Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Forecast Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <inlineHelpText>Only the major appliance divisions can be forecast:  20, 22, 26 and 46</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>022</fullName>
            </value>
            <value>
                <fullName>026</fullName>
            </value>
            <value>
                <fullName>046</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <inlineHelpText>Only items stocked in the DDC and RRC can be forecast – we cannot accept forecast for EZ Order items</inlineHelpText>
    <label>Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Selling price to the customer</inlineHelpText>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week10__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week10__c</fullName>
    <label>Qty_Week10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week11__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week11__c</fullName>
    <label>Qty_Week11</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week12__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week12__c</fullName>
    <label>Qty_Week12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week13__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week13__c</fullName>
    <label>Qty_Week13</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week14__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week14__c</fullName>
    <label>Qty_Week14</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week15__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week15__c</fullName>
    <label>Qty_Week15</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week16__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week16__c</fullName>
    <label>Qty_Week16</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week17__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week17__c</fullName>
    <label>Qty_Week17</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week18__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week18__c</fullName>
    <label>Qty_Week18</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week19__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week19__c</fullName>
    <label>Qty_Week19</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week1__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week1__c</fullName>
    <label>Qty_Week1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week20__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week20__c</fullName>
    <label>Qty_Week20</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week21__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week21__c</fullName>
    <label>Qty_Week21</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week22__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week22__c</fullName>
    <label>Qty_Week22</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week2__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week2__c</fullName>
    <label>Qty Week2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week3__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week3__c</fullName>
    <label>Qty_Week3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week4__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week4__c</fullName>
    <label>Qty_Week4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week5__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week5__c</fullName>
    <label>Qty_Week5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week6__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week6__c</fullName>
    <label>Qty_Week6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week7__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week7__c</fullName>
    <label>Qty_Week7</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week8__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week8__c</fullName>
    <label>Qty_Week8</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Qty_Week9__c.field-meta.xml
<CustomField>
    <fullName>Qty_Week9__c</fullName>
    <label>Qty_Week9</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Web_Forecast_Header__c.field-meta.xml
<CustomField>
    <fullName>Web_Forecast_Header__c</fullName>
    <label>Web_Forecast_Header</label>
    <referenceTo>Web_Forecast__c</referenceTo>
    <relationshipLabel>Web Forecast Line Items</relationshipLabel>
    <relationshipName>Web_Forecast_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Web_Forecast_Line_Item__c/fields/Week1__c.field-meta.xml
<CustomField>
    <fullName>Week1__c</fullName>
    <formula>Web_Forecast_Header__r.Week_Start_Date__c -  VALUE(CASE(
  MOD( Web_Forecast_Header__r.Week_Start_Date__c - DATE( 1900, 1, 7 ), 7 ),
  0, &quot;0&quot;,
  1, &quot;1&quot;,
  2, &quot;2&quot;,
  3, &quot;3&quot;,
  4, &quot;4&quot;,
  5, &quot;5&quot;, 
  &quot;6&quot;
)) + 49</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/Zipcode_DDC_RRC__c.object-meta.xml
<CustomObject>
    <description>Holds all zip codes with DDC &amp; RRC information</description>
    <label>Zipcode DDC RRC</label>
    <nameField>
        <label>Zipcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zipcode DDC RRCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/DDC__c.field-meta.xml
<CustomField>
    <fullName>DDC__c</fullName>
    <label>DDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/DOS_Unit__c.field-meta.xml
<CustomField>
    <fullName>DOS_Unit__c</fullName>
    <label>MDO</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zipcode_DDC_RRC__c/fields/RRC__c.field-meta.xml
<CustomField>
    <fullName>RRC__c</fullName>
    <label>RRC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebForecastHandlerTest.cls
/**
 * Created by jirala on 2/8/2018.
 */
@isTest
public class WebForecastHandlerTest {

    public static Web_Forecast__c header;
    public static Web_Forecast_Line_Item__c forecastline;

    static void setupData(boolean withitem){
        Zipcode_DDC_RRC__c shiptozip = new Zipcode_DDC_RRC__c(External_ID__c = '1', Name = '60089',
                DOS_Unit__c = '8808', DDC__c = '8721', RRC__c = '449');
        Insert shiptozip;

        FCST_Item_Info__c itemdet_DDC = new FCST_Item_Info__c(
                External_ID_Num__c = '1',
                Division__c = '026',
                Item_Num__c = '026-48232-000',
                MDM_Item__c = '02648232000',
                Item_8721_Stock__c = 'Y',
                Dist_Type__c = 'DD'
                );
        Insert itemdet_DDC;

        FCST_Item_Info__c itemdet_RRC = new FCST_Item_Info__c(
                External_ID_Num__c = '2',
                Division__c = '046',
                Item_Num__c = '046-70339-000',
                MDM_Item__c = '04670339000',
                Item_8721_Stock__c = 'Y',
                Dist_Type__c = 'TW'
        );
        Insert itemdet_RRC;

        Transitions_Item__c transitem = new Transitions_Item__c(
                Ext_Num__c = '1',
                Old_Item__c = '026-51022-000',
                New_Item__c = '026-51122-000'
        );
        Insert transitem;

        //setup test data: Quote header & Line items.
        header = new Web_Forecast__c(
                Week_Start_Date__c = Date.today(),
                Ship_to_Zipcode__c = shiptozip.Id,
                Name = 'Testclass Forecast',
                Sales_Rep_Email__c = 'testclass@test.com',
            	Sales_Rep_Name__c = 'Test Account Manager',
            	Sales_Rep_Number__c = '1234',
            	District_Manager__c = 'Test DM'
        );
        insert header;

        if(withitem){
            forecastline = new Web_Forecast_Line_Item__c(
                    Web_Forecast_Header__c = header.Id,
                    Division__c = '026',
                    Item__c = '48232',
                    Price__c = 50,
                    Qty_Week1__c = 1,
                    Qty_Week2__c = 1,
                    Qty_Week3__c = 1,
                    Qty_Week4__c = 1,
                    Qty_Week5__c = 1,
                    Qty_Week6__c = 1,
                    Qty_Week7__c = 1,
                    Qty_Week8__c = 1,
                    Qty_Week9__c = 1,
                    Qty_Week10__c = 1,
                    Qty_Week11__c = 1,
                    Qty_Week12__c = 1,
                    Qty_Week13__c = 1,
                	Qty_Week14__c = 1,
                	Qty_Week15__c = 1,
                	Qty_Week16__c = 1,
                	Qty_Week17__c = 1,
                	Qty_Week18__c = 1,
                	Qty_Week19__c = 1,
                	Qty_Week20__c = 1,
                	Qty_Week21__c = 1,
                	Qty_Week22__c = 1,
                	Qty_Week23__c = 1,
                	Qty_Week24__c = 1,
                	Qty_Week25__c = 1,
                	Qty_Week26__c = 1
            ); insert forecastline;

            Web_Forecast_Line_Item__c forecastline_RRC = new Web_Forecast_Line_Item__c(
                    Web_Forecast_Header__c = header.Id,
                    Division__c = '046',
                    Item__c = '70339',
                    Price__c = 50,
                    Qty_Week1__c = 1,
                    Qty_Week2__c = 1,
                    Qty_Week3__c = 1,
                    Qty_Week4__c = 1,
                    Qty_Week5__c = 1,
                    Qty_Week6__c = 1,
                    Qty_Week7__c = 1,
                    Qty_Week8__c = 1,
                    Qty_Week9__c = 1,
                    Qty_Week10__c = 1,
                    Qty_Week11__c = 1,
                    Qty_Week12__c = 1,
                    Qty_Week13__c = 1,
                    Qty_Week14__c = 1,
                	Qty_Week15__c = 1,
                	Qty_Week16__c = 1,
                	Qty_Week17__c = 1,
                	Qty_Week18__c = 1,
                	Qty_Week19__c = 1,
                	Qty_Week20__c = 1,
                	Qty_Week21__c = 1,
                	Qty_Week22__c = 1,
                	Qty_Week23__c = 1,
                	Qty_Week24__c = 1,
                	Qty_Week25__c = 1,
                	Qty_Week26__c = 1
            ); insert forecastline_RRC;
        }
    }

    public static testMethod void WebForecastItemTrigger(){
        setupData(false);

        Web_Forecast_Line_Item__c forecastline = new Web_Forecast_Line_Item__c(
                Web_Forecast_Header__c = header.Id,
                Division__c = '026',
                Item__c = '48232',
                Price__c = 50
        );

        Web_Forecast_Line_Item__c forecastline_dupl = new Web_Forecast_Line_Item__c(
                Web_Forecast_Header__c = header.Id,
                Division__c = '026',
                Item__c = '48232',
                Price__c = 50
        );

        Test.startTest();
        Database.SaveResult result = Database.insert(forecastline,false);
        Database.SaveResult result_dupl = Database.insert(forecastline_dupl,false);
        Test.stopTest();

        Web_Forecast_Line_Item__c forecastdet = [select Week1__c, Item_Formatted__c, Item_Dist_Type__c, DDC_Item__c, RRC_Item__c from Web_Forecast_Line_Item__c where Web_Forecast_Header__c = :header.Id];
        //System.assertEquals(forecastdet.Week1__c, '');
        System.assertEquals(forecastdet.Item_Formatted__c, '026-48232-000');
        System.assertEquals(forecastdet.Item_Dist_Type__c, 'DD');
        System.assertEquals(forecastdet.DDC_Item__c, '8721');
        System.assertEquals(forecastdet.RRC_Item__c, '449');

        system.assertEquals(result_dupl.isSuccess(),false,'Duplicate Item check fails');
    }

    //test method for 'View' Forecase item VF Page .
    public static testMethod void ViewWebForecaseItemOverride() {

        setupData(true);
        PageReference pageRef = Page.WebForecastLineItemVF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', forecastline.Id);
        ApexPages.StandardController stdController = new ApexPages.StandardController(forecastline);
        WebForecastLineItem_Controller custcontroller = new WebForecastLineItem_Controller(stdController);
        PageReference retURL = custcontroller.gotoHeader();
    }

    //test method for 'Edit' Forecase item VF Page .
    public static testMethod void EditWebForecaseItemOverride() {

        setupData(true);
        PageReference pageRef = Page.WebForecastLineItemVF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', forecastline.Id);
        ApexPages.currentPage().getParameters().put('retUrl', header.Id);
        ApexPages.StandardController stdController = new ApexPages.StandardController(forecastline);
        WebForecastLineItem_Controller custcontroller = new WebForecastLineItem_Controller(stdController);
        PageReference retURL = custcontroller.gotoHeader();
    }

    //test method for 'Create' Forecase item VF Page .
    public static testMethod void CreateWebForecaseItemOverride() {

        setupData(true);
        PageReference pageRef = Page.WebForecastLineItemVF;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController = new ApexPages.StandardController(forecastline);
        WebForecastLineItem_Controller custcontroller = new WebForecastLineItem_Controller(stdController);
        PageReference retURL = custcontroller.gotoHeader();
    }

    //test method for VF Page button to generate email on web forecasting.
    public static testMethod void GenerateFiles_Email_VF() {

        setupData(true);
        List<Contact> Contacts = TestDataFactory.createContacts(1);
        Contacts[0].Email = 'test@testmail.com';
        insert Contacts;

        PageReference pageRef = Page.WebForecastEmailFiles;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController = new ApexPages.StandardController(header);
        WebForecastEmailConfirmation custcontroller = new WebForecastEmailConfirmation(stdController);
        PageReference retURL = custcontroller.EmailandAttach();


    }

}