force-app/main/default/objects/Contract/fields/Legal_Approver__c.field-meta.xml
<CustomField>
    <fullName>Legal_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LegalContract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Amount_Processed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Processed__c</fullName>
    <label>Release Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <label>Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/isProductParent__c.field-meta.xml
<CustomField>
    <fullName>isProductParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isProductParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Items_Processed__c.field-meta.xml
<CustomField>
    <fullName>Items_Processed__c</fullName>
    <label>Release Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/ProductParentUnique__c.field-meta.xml
<CustomField>
    <fullName>ProductParentUnique__c</fullName>
    <label>ProductParentUnique</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Expected Total Value</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Target Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <inlineHelpText>Solid waste fee/ Disposable fee for North Carolina &amp; South Carolina States</inlineHelpText>
    <label>Solid Waste fee/Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Net_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Price__c</fullName>
    <formula>Net_Unit_Price__c *  SBQQ__Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>List_Price__c - SBQQ__AdditionalDiscountAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ContractHandler.cls
public class ContractHandler implements ITrigger {
    
    public void bulkBefore() {}
    
    public void bulkAfter() {}
    
    public void beforeInsert(Sobject obj) {
        Contract objcontract = (Contract) obj;
        
                string legal_user = '';
        List<User> lstUser = new List<User>();
        lstUser = [SELECT Id, Name FROM User WHERE Name='Donna Carollo' LIMIT 1];
        if(lstUser.size()>0){
            legal_user = lstUser[0].Id;
        }
        
        
        objcontract.Legal_Approver__c = legal_user;
        
    }
    
    public void beforeUpdate(Sobject oldObj, Sobject newObj) {}
    
    public void beforeDelete(Sobject obj) {}
    
    public void afterInsert(Sobject obj) {
        Contract objcontract = (Contract) obj;
        System.debug('objcontract--> ' + objcontract);
        System.debug('objcontract.SBQQ__Quote__c--> ' + objcontract.SBQQ__Quote__c);
        
        Contract_Line_Item__c objContractLineItem = new Contract_Line_Item__c();
        List<Contract_Line_Item__c> lstContractLineItem = new List<Contract_Line_Item__c>();
        
        if(objcontract.SBQQ__Quote__c!=null){
            
            List<SBQQ__QuoteLine__c> lstQuoteLine = new List<SBQQ__QuoteLine__c>();
            
            lstQuoteLine = [SELECT Id, Name, SBQQ__Product__c, SBQQ__Quantity__c, SBQQ__Quote__c, 
                            	List_Price__c, Net_Unit_Price__c, Net_Total_Price__c, Disposable_Fee__c, 
                            	isProductParent__c, SBQQ__Number__c, Feature__c,ProductParentUnique__c, Tax_Rate__c,
                            	Configuration_Code__c, Configuration_Option__c
                            FROM SBQQ__QuoteLine__c 
                            WHERE SBQQ__Quote__c=:objcontract.SBQQ__Quote__c
                           ];
            
            if(lstQuoteLine.size()>0){
                
                for(SBQQ__QuoteLine__c ql:lstQuoteLine){
                    objContractLineItem = new Contract_Line_Item__c();
                    objContractLineItem.Contract__c = objcontract.Id;
                    objContractLineItem.Product__c = ql.SBQQ__Product__c;
                    objContractLineItem.Total_Quantity__c = ql.SBQQ__Quantity__c;
                    objContractLineItem.Total_Amount__c = ql.Net_Total_Price__c;
                    objContractLineItem.Tax_Rate__c = ql.Tax_Rate__c!=null?ql.Tax_Rate__c:0;
                    objContractLineItem.Status__c = 'Open';
                //    objContractLineItem.Feature__c = ql.SBQQ__ProductOption__r.SBQQ__Feature__r.Name;
                    objContractLineItem.Feature__c = ql.Feature__c;
                    objContractLineItem.Configuration_Code__c = ql.Configuration_Code__c;
                    objContractLineItem.Configuration_Option__c = ql.Configuration_Option__c;
                    objContractLineItem.Items_Processed__c = 0;
                    objContractLineItem.Amount_Processed__c = 0;
                    objContractLineItem.isProductParent__c = ql.isProductParent__c;
                    objContractLineItem.ProductParentUnique__c = ql.ProductParentUnique__c;
                    objContractLineItem.Number__c = ql.SBQQ__Number__c;
                    objContractLineItem.List_Unit_Price__c = ql.List_Price__c;
                    objContractLineItem.Net_Unit_Price__c = ql.Net_Unit_Price__c;
                    objContractLineItem.Disposable_Fee__c = ql.Disposable_Fee__c;
                    lstContractLineItem.add(objContractLineItem);
        			System.debug('objContractLineItem--> ' + objContractLineItem);
                }
                
                insert lstContractLineItem;
        		System.debug('lstContractLineItem--> ' + lstContractLineItem);
            }
            
            List<Attachment> lstAttachment = new List<Attachment>();
            lstAttachment = [SELECT Id, ParentId, Name, ContentType, Body 
                             FROM Attachment 
                       //      WHERE ParentId='a2bW0000000kNKTIA2'
                             WHERE ParentId=:objcontract.SBQQ__Quote__c AND Name LIKE '%(signed).pdf'
                             ORDER BY CreatedDate DESC
                             LIMIT 1
                            ];
            
            if(!Test.isRunningTest()){
                if(lstAttachment.size()>0){
            Attachment attach = new Attachment();
            attach.Body = lstAttachment[0].Body;
            attach.Name = lstAttachment[0].Name;
            attach.ContentType = 'application/pdf';
            attach.ParentId = objcontract.Id;
            attach.IsPrivate = false;   
            insert attach;
                }
            }
           /* 
        if(!Test.isRunningTest()){
            Attachment attach = new Attachment();
            Blob body;      
            body = pdf.getContentAsPDF(); 
            system.debug('Body ' + body);
            attach.Body = body;
        //    attach.Name = 'Rider_' + contractId +'.pdf';
            attach.Name = 'Rider_' + string.valueof(system.now()) +'.pdf';
            attach.IsPrivate = false;       
            attach.ParentId = contractId;
            attach.ContentType = 'application/pdf';
            insert attach;
        }
        */
            
            
        }
        
        
    }
    
    public void afterUpdate(Sobject oldObj, Sobject newObj) {}
    
    public void afterDelete(Sobject obj) {}
    
    public void andFinally() {}
    
}