force-app/main/default/objects/Commercial_Contract__c/Commercial_Contract__c.object-meta.xml
<CustomObject>
    <description>Sears Commercial Contracts</description>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Supplier agreement</fullName>
                <default>true</default>
                <label>Supplier agreement</label>
            </value>
            <value>
                <fullName>Subcontractor agreement</fullName>
            </value>
            <value>
                <fullName>Government agreement</fullName>
            </value>
            <value>
                <fullName>Signed Sales Order/Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Addendums</fullName>
            </value>
            <value>
                <fullName>Final/signed contract</fullName>
            </value>
            <value>
                <fullName>Initial forecast</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Site readiness form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the contract ends</description>
    <inlineHelpText>Contract End Date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Contract Start Date</description>
    <inlineHelpText>Contract Start Date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Most Sears Commercial Contracts will be &quot;Product&quot; contracts, but some will be contractual agreements for &quot;Rebates&quot;.  Most Home Services / A&amp;E contracts will be &quot;Service&quot; contracts.</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UploadAttachmentCustomControllerTest.cls
@isTest
private class UploadAttachmentCustomControllerTest {
    
    static testmethod void attachmentUploadTestMethod() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;    

        ApexPages.StandardController stdController = new ApexPages.StandardController(accounts[0]);
        UploadAttachmentCustomController controller = new UploadAttachmentCustomController(stdController);

        Test.setCurrentPageReference(new PageReference('Page.myPage'));
        System.currentPageReference().getParameters().put('contractId', null);

        controller.fileName = 'Test Name';
        controller.selectedType = 'Supplier agreement';
        controller.selectedDocumentType = 'Addendums';
        controller.contract.Start_Date__c = System.today();
        controller.contract.End_Date__c = System.today() + 7;

        Test.startTest();       

        PageReference page = controller.processUpload();
        System.assertEquals(null, page);

        controller.fileBody = Blob.valueOf('Test Body');

        PageReference page2 = controller.processUpload();
        System.assertNotEquals(null, page2);
        
        List<Commercial_Contract__c> contracts = TestDataFactory.createCommercialContracts(1);
        contracts[0].Account__c = accounts[0].Id;
        contracts[0].Name = controller.contractName;        
        contracts[0].Contract_Type__c = 'Supplier agreement';
        contracts[0].Document_Type__c = 'Addendums';
        insert contracts;

        System.currentPageReference().getParameters().put('contractId', contracts[0].Id);
        UploadAttachmentCustomController controller2 = new UploadAttachmentCustomController(stdController);
        
        controller2.fileName = 'Test Name 2';
        controller2.fileBody = Blob.valueOf('Test Body 2');
        controller2.processUpload();

        UploadAttachmentCustomController controller3 = new UploadAttachmentCustomController(stdController);

        List<Commercial_Contract__c> contract = TestDataFactory.createCommercialContracts(1);
        contract[0].Account__c = accounts[0].Id;
        contract[0].Name = controller3.contractName;        
        contract[0].Contract_Type__c = 'Subcontractor agreement';
        contract[0].Document_Type__c = 'Addendums';

        controller3.contract = contract[0];
        controller3.fileName = 'Test Name 2';
        controller3.fileBody = Blob.valueOf('Test Body 2');
        controller3.selectedType = 'Subcontractor agreement';
        controller3.selectedDocumentType = 'Addendums';
        controller3.processUpload();

        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());

        // Check that the error message you are expecting is in pageMessages
        Boolean messageFound = false;

        for(ApexPages.Message message : pageMessages) {
            if(message.getSummary() == 'Total Ammount is required for this document.'
                && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;        
            }
        }

        System.assert(messageFound);

        Test.stopTest();
    }
    
}