force-app/main/default/objects/Commercial_Contract__c/Commercial_Contract__c.object-meta.xml
<CustomObject>
    <description>Sears Commercial Contracts</description>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountCommercialContractRLTest.cls
@isTest
private class AccountCommercialContractRLTest {
	
	static testmethod void commercialContractRelatedListTestMethod() {
		List<Account> accounts = TestDataFactory.createAccounts(1);
		insert accounts;		

		List<Commercial_Contract__c> contracts = TestDataFactory.createCommercialContracts(1);
		contracts[0].Account__c = accounts[0].Id;
		insert contracts;

		ApexPages.StandardController stdController = new ApexPages.StandardController(contracts[0]);
		AccountCommercialContractRLController controller = new AccountCommercialContractRLController(stdController);
		List<Attachment> result = controller.getAttachmentList();

		List<Attachment> attachments =  TestDataFactory.createAttachemts(2);
		attachments[0].ParentId = contracts[0].Id;
		attachments[1].ParentId = contracts[0].Id;
		insert attachments;


		contracts[0].Attachment__c = attachments[1].Id;
		update contracts;

		Test.startTest();	

		result = controller.getAttachmentList();
		System.assert(result.size() == 2);
		
		Test.setCurrentPageReference(new PageReference('Page.myPage'));
		System.currentPageReference().getParameters().put('recordid', attachments[1].Id);
		controller.deleteContract();

		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertNotEquals(0, pageMessages.size());


		System.currentPageReference().getParameters().put('recordid', attachments[0].Id);
		controller.deleteContract();

		result = controller.getAttachmentList();
		System.assert(result.size() == 1);

		Test.stopTest();
	}
	
}