force-app/main/default/objects/Commercial_Contract__c/Commercial_Contract__c.object-meta.xml
<CustomObject>
    <description>Sears Commercial Contracts</description>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Supplier agreement</fullName>
                <default>true</default>
                <label>Supplier agreement</label>
            </value>
            <value>
                <fullName>Subcontractor agreement</fullName>
            </value>
            <value>
                <fullName>Government agreement</fullName>
            </value>
            <value>
                <fullName>Signed Sales Order/Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Addendums</fullName>
            </value>
            <value>
                <fullName>Final/signed contract</fullName>
            </value>
            <value>
                <fullName>Initial forecast</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Site readiness form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the contract ends</description>
    <inlineHelpText>Contract End Date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Contract Start Date</description>
    <inlineHelpText>Contract Start Date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Most Sears Commercial Contracts will be &quot;Product&quot; contracts, but some will be contractual agreements for &quot;Rebates&quot;.  Most Home Services / A&amp;E contracts will be &quot;Service&quot; contracts.</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCommercialContractController.cls
public with sharing class AccountCommercialContractController {
	private final Account account {get; set;}
	public String destURL {get; set;}
	
	public AccountCommercialContractController(ApexPages.StandardController controller) {
		if(!test.isRunningTest()){
			controller.addFields(new List<String>{'ParentId'});
		}
		this.account = (Account)controller.getRecord();	
		this.destURL = String.format('/apex/CommercialContractUpload?id={0}&contractId=', new String[]{account.Id});
	}

	public List<DisplayContracts> getContractList(){
		List<DisplayContracts> contractList = new List<DisplayContracts>();

		for(Commercial_Contract__c record: [SELECT Account__c,Attachment__c,Document_Type__c,Contract_Type__c,End_Date__c,Id,Name,Total_Amount__c,Start_Date__c FROM Commercial_Contract__c WHERE Account__c = :account.ParentId AND IsDeleted = false ORDER BY Start_Date__c DESC]){
			contractList.add(new DisplayContracts(record,[SELECT ContentType,Description,Id,Name,OwnerId,ParentId FROM Attachment WHERE Id = :record.Attachment__c],true));
		}
		
		for(Commercial_Contract__c record: [SELECT Account__c,Attachment__c,Document_Type__c,Contract_Type__c,End_Date__c,Id,Name,Total_Amount__c,Start_Date__c FROM Commercial_Contract__c WHERE Account__c = :account.Id AND IsDeleted = false ORDER BY Start_Date__c DESC]){
			contractList.add(new DisplayContracts(record,[SELECT ContentType,Description,Id,Name,OwnerId,ParentId FROM Attachment WHERE Id = :record.Attachment__c],false));
		}		

		if(contractList.size() > 0)
			return contractList;
		else
			return null;
	}

	@TestVisible class DisplayContracts{
		 public Commercial_Contract__c contract { get;set; }
		 public Attachment attachment { get; set; }
		 public Boolean parent {get; set;}

		 public DisplayContracts(Commercial_Contract__c c, Attachment a, Boolean isParent){
		 	this.contract = c;
		 	this.attachment = a;
		 	this.parent = isParent;
		 }
	}
}