force-app/main/default/objects/Account/recordTypes/Home_Services.recordType-meta.xml
<RecordType>
    <fullName>Home_Services</fullName>
    <active>true</active>
    <label>Home Services</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Purchase_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Number__c</fullName>
    <label>Purchase Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/ContractRenewalOpportunityFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ContractRenewalOpportunityFields</label>
</CustomObject>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Business__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Business__c</fullName>
    <description>Default Business value for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Business value for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Business</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <description>Default Record Type ID for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Record Type ID for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Record Type ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Default Stage for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Stage for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Stage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <formula>CASE(StageName,
&quot;Qualified&quot;,&quot;Open&quot;,
&quot;Working On Quote&quot;,&quot;Open&quot;,
&quot;Quote Sent&quot;,&quot;Open&quot;,
&quot;Out For Signature&quot;,&quot;Open&quot;,
&quot;Awaiting Credit Approval&quot;,&quot;Open&quot;,
&quot;Identification&quot;,&quot;Open&quot;, 
&quot;Conduct Due Diligence&quot;,&quot;Open&quot;, 
&quot;Review Customer Requirements&quot;,&quot;Open&quot;, 
&quot;Determine Solution&quot;,&quot;Open&quot;, 
&quot;Develop/Review Pricing Model&quot;,&quot;Open&quot;, 
&quot;Finance Review&quot;,&quot;Open&quot;, 
&quot;Develop Proposal&quot;,&quot;Open&quot;, 
&quot;Proposal Presentation&quot;,&quot;Open&quot;, 
&quot;Solution Discussion and Negotiation&quot;,&quot;Open&quot;, 
&quot;Contract Preparation and Negotiation&quot;,&quot;Open&quot;, 
&quot;Financial Approval&quot;,&quot;Open&quot;, 
&quot;Closed Won&quot;,&quot;Closed Won&quot;,
&quot;Deal Closure/Won&quot;,&quot;Closed Won&quot;, 
&quot;Closed Lost&quot;,&quot;Closed Lost&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Home_Services.recordType-meta.xml
<RecordType>
    <fullName>Home_Services</fullName>
    <active>true</active>
    <businessProcess>Home Services</businessProcess>
    <label>Home Services</label>
</RecordType>

force-app/main/default/classes/TestBatchContractRenewal.cls
public with sharing class TestBatchContractRenewal 
{
	static testMethod void testContractRenewal()
	{

		//create test data
		List<Account> acc = TestDataFactory.createAccounts(1);
		insert acc;
		
		Contract contract = new Contract();
		contract.Name = 'Test';
		contract.AccountId = acc[0].Id;
		contract.Status = 'Draft';
		//Use query for unit test instead of Dates
		contract.StartDate = Date.today();
		contract.ContractTerm = 3;
		contract.Contract_End_Date__c = Date.today().addDays(90);
        contract.Purchase_Number__c = 'PO_C_00' ;
		insert contract;
		
		ContractRenewalOpportunityFields__c crof = new ContractRenewalOpportunityFields__c();
		crof.Name = 'Defaults';
		crof.Opportunity_Business__c = 'Home Services';
		crof.Opportunity_Stage__c = 'Determine Solution';
		crof.Opportunity_Record_Type__c = [select Id from RecordType where SObjectType = 'Opportunity'  AND DeveloperName = 'Home_Services'].Id;
		insert crof;
				
		//test
		BatchContractRenewal bcr = new BatchContractRenewal();
		Test.startTest();
		Database.executeBatch(bcr);
		Test.stopTest();
		
		//validation
		Integer opportunitiesCreated = [SELECT COUNT() FROM Opportunity WHERE AccountId = :acc[0].Id]; 
		System.assertEquals(1, opportunitiesCreated);
		
	}

}