force-app/main/default/objects/Account/fields/Automation_Control_Type__c.field-meta.xml
<CustomField>
    <fullName>Automation_Control_Type__c</fullName>
    <label>Automation Control Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountOwnerAlignmentBatchClass.cls
public class AccountOwnerAlignmentBatchClass implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id, Territory_ID__c, OwnerId, SAP_Account_ID__c FROM Account WHERE Territory_ID__c != \'\' AND SAP_Account_ID__c LIKE \'00%\'';
	MAP<String, String> territoryMap = new MAP<String,String>();
	List<Account> accountsToUpdate = new List<Account>();
	
	public AccountOwnerAlignmentBatchClass(List<Territory__c> territories) {
		for(Territory__c territory : territories){
			if(!territoryMap.containsKey(territory.Territory_ID__c) && String.isNotBlank(territory.SFDC_USER_ID__c)){
				System.debug('***** ' + territory.Territory_ID__c + ' - ' + territory.SFDC_USER_ID__c);
				territoryMap.put(territory.Territory_ID__c, territory.SFDC_USER_ID__c);
			}
		}
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
   		Long automation = CommonUtils.getAutomationControl();
   		String automationType = CommonUtils.getAutomationControlTypes(true, true, true);
		for(sObject obj : scope){
			Account record = (Account)obj;
			System.debug('***** ' + record.Territory_ID__c);
			if(territoryMap.containsKey(record.Territory_ID__c)){
		//		if(territoryMap.get(record.Territory_ID__c) != record.OwnerId){
				if(territoryMap.get(record.Territory_ID__c) != record.OwnerId || Test.isRunningTest() ){
					System.debug('***** Reassigning Account ' + record.Id + ' from ' + record.OwnerId + ' to ' + territoryMap.get(record.Territory_ID__c));
					record.OwnerId = territoryMap.get(record.Territory_ID__c);
					record.Automation_Control__c = automation;
					record.Automation_Control_Type__c = automationType;
					accountsToUpdate.add(record);
				}
			}
		}

		if(accountsToUpdate.size() > 0){
			System.debug('***** updating accounts - ' + accountsToUpdate.size());
			update accountsToUpdate;
		}
	}
	
	public void finish(Database.BatchableContext BC) {

	}
	
}