force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A&amp;E</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Home Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Pricing_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Customer_Pricing_Procedure__c</fullName>
    <description>1	Defaulted to &quot;Standard&quot;</description>
    <inlineHelpText>1	Standard</inlineHelpText>
    <label>Customer Pricing Procedure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>For the nickname related to the account.</description>
    <label>Nickname</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Annual_Sales_Volume__c.field-meta.xml
<CustomField>
    <fullName>Potential_Annual_Sales_Volume__c</fullName>
    <description>Score Accounts by potential annual sales volume</description>
    <inlineHelpText>A - &gt; $500,000
B - $250,000 - $499,999
C - $100,000 - $249,999 
D - $50,000 - $99,999
E - $20,000 - $49,999
F - &lt; $20,000</inlineHelpText>
    <label>Potential Annual Sales Volume</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_NAICS_Code__c</fullName>
    <description>To Translate the NAICS Code from a formula field to a text value for the SAP integration.</description>
    <inlineHelpText>2-digit to 8-digit code representing the market segment of the company with which you are doing business</inlineHelpText>
    <label>SAP NAICS Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Terms_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_of_Payment__c</fullName>
    <description>0002	14 days 2%, 30 net
0001	Pay immediately w/o deduction</description>
    <inlineHelpText>0002	14 days 2%, 30 net
0001	Pay immediately w/o deduction</inlineHelpText>
    <label>Terms of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0001</fullName>
                <default>true</default>
                <label>0001</label>
            </value>
            <value>
                <fullName>0002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds all zip codes with associated city and state</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountDetailPage2ControllerTest.cls
@isTest
public class AccountDetailPage2ControllerTest{
    
    public static testMethod void function(){
        Test.startTest();
        Profile profile_obj = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];
        
        //Role is Sears Administrator in User Object
        UserRole role_obj = [select id, Name from UserRole where Name = 'Sears Administrator' limit 1];
        
        //Set the Test user
        List<User> users = TestDataFactory.createUsers(2);
        users[0].UserRoleId=role_obj.Id;
        users[0].profileid=profile_obj.ID; 
        insert users;        

        List<Zip_Code__c> lstTestZipCode = new List<Zip_Code__c>();
        
        Zip_Code__c test_zipcode_1 = new Zip_Code__c();
        test_zipcode_1.Name = '56040';
        test_zipcode_1.OwnerId = system.UserInfo.getUserId();
        test_zipcode_1.State__c = 'AL';
        
        lstTestZipCode.add(test_zipcode_1);
        
        insert lstTestZipCode;
                   
        
        Account account_obj_2 = new Account();        
        Account account_obj_1 = new Account();
        
        System.runAs(users[0]){
            //Creating records for Account Object
            account_obj_1.Nickname__c = 'Test';
            account_obj_1.SAP_NAICS_Code__c = '23';
            account_obj_1.Type = 'Prospect';
            account_obj_1.Fax = '53543';
            account_obj_1.Website = 'http://fgjddghj.com';
            account_obj_1.Business__c = 'Commercial';
            account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
            account_obj_1.Terms_of_Payment__c = '0001';
            account_obj_1.Customer_Pricing_Procedure__c = '5';
            account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
            account_obj_1.Phone = '(899) 725-8325';
            account_obj_1.Name = 'User_Account_1';
            account_obj_1.BillingStreet = 'ST';
            account_obj_1.BillingState = 'AL';
            account_obj_1.BillingCity = 'TestCity';
            account_obj_1.BillingPostalCode = '56040';
            account_obj_1.BillingCountry = 'PR';
            account_obj_1.SAP_Account_ID__c= '525434';
            account_obj_1.OwnerId = users[0].Id;
            insert account_obj_1;
            
            //Update a record for Account Object
            account_obj_2.Id = account_obj_1.Id;
            account_obj_1.Nickname__c = 'Test2';
            account_obj_1.SAP_NAICS_Code__c = '233';
            account_obj_1.Type = 'Prospect';
            account_obj_1.Fax = '5354334';
            account_obj_1.Website = 'http://fgjddghj.com';
            account_obj_1.Business__c = 'Commercial';
            account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
            account_obj_1.Terms_of_Payment__c = '0002';
            account_obj_1.Customer_Pricing_Procedure__c = '5';
            account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
            account_obj_1.Phone = '(899) 725-8325';
            account_obj_1.Name = 'User_Account_1';
            account_obj_1.BillingStreet = 'ST';
            account_obj_1.BillingState = 'AL';
            account_obj_1.BillingCity = 'TestCity';
            account_obj_1.BillingPostalCode = '56040';
            account_obj_1.BillingCountry = 'PR';
            account_obj_1.SAP_Account_ID__c= '525434';
            update account_obj_2;
            
            //ApexPages.currentPage().getParameters().put('Id',account_obj_1.id);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(account_obj_2);
            ApexPages.currentPage().getParameters().put('Id',account_obj_2.id);
            
            AccountDetailPage2Controller account_detail_object = new AccountDetailPage2Controller(sc);
            account_detail_object.Save1();
             account_detail_object.Cancel1();

           System.runAs(users[1]){
                ApexPages.Standardcontroller sc2 = new ApexPages.Standardcontroller(account_obj_1);
                ApexPages.currentPage().getParameters().put('Id',account_obj_1.id);
            
                account_detail_object = new AccountDetailPage2Controller(sc2);
                account_detail_object.Save1();
           }
        }
       Test.stopTest();
    }    
}