force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>CASE( Industry,
 &quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;,
 &quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;,
 &quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;,
 &quot;Builders&quot;, &quot;23&quot;,  
 &quot;Education&quot;, &quot;61&quot;, 
 &quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;,
 &quot;Information&quot;, &quot;51&quot;,
 &quot;Insurance Companies&quot;, &quot;52&quot;,
 &quot;Lodging&quot;, &quot;72&quot;,
 &quot;Management of Companies and Enterprises&quot;, &quot;55&quot;,
 &quot;Manufacturing&quot;, &quot;337110&quot;,
 &quot;Military&quot;, &quot;928810&quot;,
 &quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;,
 &quot;Other Services (except Public Administration)&quot;, &quot;81&quot;,
 &quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;,
 &quot;Property Management&quot;, &quot;53&quot;,
 &quot;Retail Trade&quot;, &quot;44-45&quot;,
 &quot;Transportation and Warehousing&quot;, &quot;48-49&quot;,
 &quot;Utilities&quot;, &quot;22&quot;,
 &quot;Wholesale Trade&quot;, &quot;42&quot;,
 &quot;Government&quot;, &quot;92&quot;,
 &quot;23&quot;
)</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Owner_Id__c</fullName>
    <label>Owner Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_ID_Old__c.field-meta.xml
<CustomField>
    <fullName>Owner_ID_Old__c</fullName>
    <label>Owner ID Old</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>The North American Industry Classification System (NAICS) is the standard used by Federal statistical agencies in classifying business establishments for the purpose of collecting, analyzing, and publishing statistical data related to the U.S. business economy.</description>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name_Short__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name_Short__c</fullName>
    <label>District Manager Name Short</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/EID_Length__c.field-meta.xml
<CustomField>
    <fullName>EID_Length__c</fullName>
    <formula>LEN(Enterprise_ID__c) &lt; 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EID Length</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds all zip codes with associated city and state</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/updateAccountTest.cls
@isTest
public class updateAccountTest{
     static testmethod void testAccUpdate(){
            
        List<Zip_Code__c> lstTestZipCode = new List<Zip_Code__c>();
        
        Zip_Code__c test_zipcode_1 = new Zip_Code__c();
        test_zipcode_1.Name = '01012';
        test_zipcode_1.OwnerId = system.UserInfo.getUserId();
        test_zipcode_1.State__c = 'AL';
        
        lstTestZipCode.add(test_zipcode_1);
        
        insert lstTestZipCode;
                   
        Business_Sector__c buSec = new Business_Sector__c();
        buSec.Name='usinessname';
        insert buSec;
        
        Industry_Segment__c inSec = new Industry_Segment__c();
        inSec.Business_Sector__c = buSec.id;
        inSec.Name = 'industryname';
        //inSec.NAICS_Code__c=020120;
        insert inSec;
        
        
        Account acc = new Account(); 
        //acc.Id= 'accountid';  
        acc.Territory__c= '0012';  
        acc.Territory_ID__c='111';
        //acc.Owner_ID_Old__c= 'owneridoldtest';  
        //acc.Owner_Id__c = 'owneridtest';
        acc.SAP_Account_ID__c='001245'; 
        acc.BillingStreet='teststreet';
        acc.BillingCity='testcity';
        acc.BillingState='AL';
        acc.BillingPostalCode='01012';
        acc.BillingCountry='US';
        acc.Industry='testindustry';
        acc.Name='testname';
        acc.Phone='(999)999-9999';
        acc.Business_Sector__c = buSec.id;
        acc.Industry_Segment__c = inSec.id;
        insert acc;
        
        Territory__c terr = new Territory__c();
        terr.Territory_ID__c ='111';
        terr.FIRST_NAME__c ='testFname';
        terr.LAST_NAME__c='testLname';
        terr.Enterprise_ID__c='testsearchid';
        terr.District_Manager_Name_Short__c='District Manager';
        //terr.EID_length__c ='true';
        
        insert terr;
        
        User user = new User();
        user.FirstName='District ';
        user.LastName='Manager';
        user.Sears_Enterprise_id__c  ='testsearchid';
        user.Username='johnacmeff@fgf.com';
        user.Email='testemail@cg.com';
        user.Alias='aa';
        user.isActive=true;
        user.CommunityNickname='testccname';
        user.TimeZoneSidKey='America/Denver';
        user.LocaleSidKey='en_US';
        user.EmailEncodingKey='UTF-8';
        user.ProfileId='00e30000001FeAR';
        user.LanguageLocaleKey='en_US';
        
        
        insert user;
        
      
        Test.startTest();
        updateAccount updateAccountTest = new updateAccount();
        Database.executeBatch(updateAccountTest) ;
        Test.stopTest();

        
     }
 
}