force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <description>05	Builders
01	Educational Services
02	Govt &amp; Military
03	Health Care &amp; Social
07	Others
04	Property Mgmt
06   Utilities</description>
    <inlineHelpText>05	Builders
01	Educational Services
02	Govt &amp; Military
03	Health Care &amp; Social
07	Others
04	Property Mgmt
06   Utilities</inlineHelpText>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Pricing_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Customer_Pricing_Procedure__c</fullName>
    <description>1	Defaulted to &quot;Standard&quot;</description>
    <inlineHelpText>1	Standard</inlineHelpText>
    <label>Customer Pricing Procedure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Opportunity_Amount__c</fullName>
    <description>Used by Lead Assignment trigger to auto assign correct owner</description>
    <label>Estimated Opportunity Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>CASE( Industry,
 &quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;,
 &quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;,
 &quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;,
 &quot;Builders&quot;, &quot;23&quot;,  
 &quot;Education&quot;, &quot;61&quot;, 
 &quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;,
 &quot;Information&quot;, &quot;51&quot;,
 &quot;Insurance Companies&quot;, &quot;52&quot;,
 &quot;Lodging&quot;, &quot;72&quot;,
 &quot;Management of Companies and Enterprises&quot;, &quot;55&quot;,
 &quot;Manufacturing&quot;, &quot;337110&quot;,
 &quot;Military&quot;, &quot;928810&quot;,
 &quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;,
 &quot;Other Services (except Public Administration)&quot;, &quot;81&quot;,
 &quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;,
 &quot;Property Management&quot;, &quot;53&quot;,
 &quot;Retail Trade&quot;, &quot;44-45&quot;,
 &quot;Transportation and Warehousing&quot;, &quot;48-49&quot;,
 &quot;Utilities&quot;, &quot;22&quot;,
 &quot;Wholesale Trade&quot;, &quot;42&quot;,
 &quot;Government&quot;, &quot;92&quot;,
 &quot;23&quot;
)</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <description>Field needs to be translated</description>
    <label>Price List Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>C0</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C6</fullName>
            </value>
            <value>
                <fullName>C7</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CK</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CQ</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <defaultValue>&quot;Bronze&quot;</defaultValue>
    <label>Pricing Tier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing_Tier_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Assignment_Date__c</fullName>
    <label>Pricing Tier Assignment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing_Tier_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Expiration_Date__c</fullName>
    <label>Pricing Tier Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing_Tier_QTD_Sales__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_QTD_Sales__c</fullName>
    <label>Pricing Tier QTD Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing_Tier_YTD_Sales__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_YTD_Sales__c</fullName>
    <label>Pricing Tier YTD Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>This object is mainly used to change any existing data from account/SAP.</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <formula>Account_Name__r.Business_Sector__r.Name</formula>
    <label>Business Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <formula>TEXT(Account_Name__r.Customer_Group__c)</formula>
    <label>Customer Price Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <formula>Account_Name__r.Industry_Segment__r.Name</formula>
    <label>Industry Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>Account_Name__r.NAICS_Code__c</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <formula>Account_Name__r.Payment_Term__c</formula>
    <label>Payment Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <formula>TEXT(Account_Name__r.Price_List_Type__c)</formula>
    <label>Price List Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <formula>Account_Name__r.Pricing_Tier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Pricing_Tier_QTD_Sales__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_QTD_Sales__c</fullName>
    <formula>Account_Name__r.Pricing_Tier_QTD_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier QTD Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Pricing_Tier_YTD_Sales__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_YTD_Sales__c</fullName>
    <formula>Account_Name__r.Pricing_Tier_YTD_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier YTD Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>The North American Industry Classification System (NAICS) is the standard used by Federal statistical agencies in classifying business establishments for the purpose of collecting, analyzing, and publishing statistical data related to the U.S. business economy.</description>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ChangeRequestPage2Controller.cls
public class ChangeRequestPage2Controller{

    public Change_Request__c change_request_obj{get;set;}
    public id accid {get; set;}
    //public boolean response {get; set;}
    //public id cRId {get; set;}
    
    public List<Account> account_obj_list {get;set;}
    public List<Account> user_obj_list {get;set;}
    //public List<Industry_Segment__c> industry_segment_list;
   // public List<Business_Sector__c> business_sector_list;
    
    //public String parentAccName{get;set;}
    //public String accName{get;set;}
    public String sTree{get;set;}
    public String cIty{get;set;}
    public String reGion{get;set;}
    public String postalCode{get;set;}
    public String couNtry{get;set;}
    public String telePhone{get;set;}
    public String eMail{get;set;}
    public String customPriceProcedue{get;set;}
    public String customerGroup{get;set;}
    public String industry{get;set;}
    public String paymentTerm{get;set;}
    public String priceGroup{get;set;}
    public String priceListType{get;set;}
    public String territoryId{get;set;}
    public String name1 {get; set;}
    public String request_status{get; set;}
    //public String buSiness{get; set;}
    //public String buSinessId;
    public String sapId{get; set;}
    public String sfdcId{get; set;}
    //public String industrySegment{get; set;}
    //public String industrySegmentId;
    public String NAICS_Code{get; set;}
    //public String PotentialAnnualSalesVolume{get; set;}
    
    public String owner_first_name{get;set;}
    public String owner_last_name{get;set;}
    public String owner_email{get; set;}
    //public String appNmae{get; set;}
    //public String fileNETNmae{get; set;}
    
    public String pricingTier{get;set;}
    public String account_manager {get;set;}
    public String newnaic_code {get;set;}
    public string newTerriID{get;set;}
    public Decimal pricingQTDSales{get;set;}
    public Decimal pricingYTDSales{get;set;}
    public Boolean requireField {get;set;}
    public Boolean tierVisible {get;set;}
    public Boolean accountVisible {get;set;}

    public ChangeRequestPage2Controller(){
        change_request_obj = new Change_Request__c();
        accid = ApexPages.currentPage().getParameters().get('myId');
        tierVisible = ApexPages.currentPage().getParameters().get('tier') == 'true' ? True : False;
        accountVisible = !tierVisible;

        requireField = false;

        if(String.isNotBlank(accid)){
            account_obj_list = [SELECT Id, Name, Name_2__c, BillingStreet, BillingCity, Business_Sector__c, SAP_Account_ID__c, BillingState, 
                                       BillingPostalCode, BillingCountry, Phone, Email_Address__c, Customer_Pricing_Procedure__c,  
                                       Customer_Group__c, Industry, Payment_Term__c, Industry_Segment__c, Parent.Name,
                                       Price_List_Type__c, Territory_ID__c, NAICS_Code__c, Pricing_Tier__c,Pricing_Tier_Assignment_Date__c,Pricing_Tier_Expiration_Date__c,
                                       Pricing_Tier_YTD_Sales__c, Pricing_Tier_QTD_Sales__c, Estimated_Opportunity_Amount__c
                                FROM Account 
                                WHERE Id = :accid];

            for(Opportunity opp :[SELECT Amount FROM Opportunity WHERE AccountId = :accid AND IsClosed = false]){
                if(opp.Amount != null && opp.Amount > 0){
                    change_request_obj.Open_Opportunity_Amount__c = change_request_obj.Open_Opportunity_Amount__c == null ? 0.00 : change_request_obj.Open_Opportunity_Amount__c;                    
                    change_request_obj.Open_Opportunity_Amount__c += opp.Amount;
                }
            }
                                                    
            change_request_obj.Account_Name__c =  accid;
            //change_request_obj.New_Potential_Annual_Sales_Volume__c = String.ValueOf(account_obj_list[0].Potential_Annual_Sales_Volume__c);      
            
            name1 =  String.ValueOf(account_obj_list[0].Name) ;
            System.debug('name1 -----------------' +name1 );
            System.debug('change_request_obj.Account_Name__r.Name-----------------' +change_request_obj.Account_Name__r.Name);
            System.debug('change_request_obj.Account_Name__r.Name-----------------' +change_request_obj.Account_Name__c);
       
            //accName=String.ValueOf(account_obj_list[0].Parent.Name) ;
            sTree=String.ValueOf(account_obj_list[0].BillingStreet) ;
            cIty=String.ValueOf(account_obj_list[0].BillingCity) ; 
            reGion=String.ValueOf(account_obj_list[0].BillingState) ; 
            postalCode=String.ValueOf(account_obj_list[0].BillingPostalCode) ; 
            couNtry=String.ValueOf(account_obj_list[0].BillingCountry) ; 
            telePhone=String.ValueOf(account_obj_list[0].Phone) ; 
            eMail=String.ValueOf(account_obj_list[0].Email_Address__c) ;
            customPriceProcedue=String.ValueOf(account_obj_list[0].Customer_Pricing_Procedure__c) ; 
            customerGroup=String.ValueOf(account_obj_list[0].Customer_Group__c) ; 
            industry=String.ValueOf(account_obj_list[0].Industry) ; 
            paymentTerm=String.ValueOf(account_obj_list[0].Payment_Term__c) ; 
            //priceGroup=String.ValueOf(account_obj_list[0].Potential_Annual_Sales_Volume__c) ; 
            priceListType=String.ValueOf(account_obj_list[0].Price_List_Type__c) ; 
            territoryId=String.ValueOf(account_obj_list[0].Territory_ID__c  ) ; 
            //buSinessId=String.ValueOf(account_obj_list[0].Business_Sector__c) ;
            sapId=String.ValueOf(account_obj_list[0].SAP_Account_ID__c) ;
            sfdcId=String.ValueOf(account_obj_list[0].Id) ; 
            NAICS_Code = String.ValueOf(account_obj_list[0].NAICS_Code__c);
            //PotentialAnnualSalesVolume = String.ValueOf(account_obj_list[0].Potential_Annual_Sales_Volume__c);
            pricingTier=String.ValueOf(account_obj_list[0].Pricing_Tier__c);
            pricingQTDSales= account_obj_list[0].Pricing_Tier_QTD_Sales__c == null ? 0.00 : account_obj_list[0].Pricing_Tier_QTD_Sales__c;
            pricingYTDSales= account_obj_list[0].Pricing_Tier_YTD_Sales__c == null ? 0.00 : account_obj_list[0].Pricing_Tier_YTD_Sales__c;
            
            industry = String.ValueOf(account_obj_list[0].Industry);
            if(industry == '' || industry == null) {
                requireField = true;
            }
           
            
            request_status = 'None';

            user_obj_list = [SELECT id, Owner.FirstName, Owner.LastName, Owner.Email, Owner.Username FROM Account WHERE Account.Id = :accid];
            
            owner_first_name = String.ValueOf(user_obj_list[0].Owner.FirstName) ;
            owner_last_name = String.ValueOf(user_obj_list[0].Owner.LastName) ;
            owner_email = String.ValueOf(user_obj_list[0].Owner.Email) ; 
            account_manager = owner_first_name + ' ' + owner_last_name ;
        }
    }

    public void newNaicCode()
    {  
    }

    public void newTerriID()
    {
        newTerriID=[select Territory_ID__c from User where id=:change_request_obj.New_Account_Owner__c Limit 1].Territory_ID__c;
    }
    
    //On click of Save button in the VF page, the Resquest Status field will be updated to Saved.
    public void Save(){
        request_status = 'Saved';
        change_request_obj.Request_Status__c = request_status;
        insert change_request_obj;
    }     
  
    //On click of Cancel button in the VF page, the page will be redirected to List View page.
    public PageReference Cancel(){  
        PageReference page_reference_obj_after_cancel = new PageReference('/'+accid);
        page_reference_obj_after_cancel.setRedirect(true);
        
        return page_reference_obj_after_cancel;
    }
    
    /*1. On accepting of sending for Approval Process, the Request Status will be updated to Submitted 
      2. Page will be redirected to account List View page*/
    public PageReference Approval_Process_Call(){  
        change_request_obj.Request_Status__c = 'Submitted';
        Database.Update(change_request_obj);
        System.debug('MYMethod fnction----------------------------------');
        PageReference my_function = new PageReference('/'+accid);
        my_function.setRedirect(true);
        
        return my_function;
    }
    
    public PageReference submit_for_approval() {
        //Change_Request__c change_request_obj;
        Approval.ProcessSubmitRequest req1=new Approval.ProcessSubmitRequest();
        //req1.setComments('Submitting request for approval');
        req1.setObjectId(change_request_obj.id);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            if(result.isSuccess())
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your Change Request has been submitted to your District Manager for approval. Once approved it will be sent to the file administration team for approval and update in SAP. Updates will automatically populate to the account within 24 hours.'));
            }
            else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'SubmissionFailed as the contract not in Submitted Status'));
            }
        }
        catch(Exception e){
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.info,e));
        }
        return null;

    }
}