force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>CASE( Industry,
 &quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;,
 &quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;,
 &quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;,
 &quot;Builders&quot;, &quot;23&quot;,  
 &quot;Education&quot;, &quot;61&quot;, 
 &quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;,
 &quot;Information&quot;, &quot;51&quot;,
 &quot;Insurance Companies&quot;, &quot;52&quot;,
 &quot;Lodging&quot;, &quot;72&quot;,
 &quot;Management of Companies and Enterprises&quot;, &quot;55&quot;,
 &quot;Manufacturing&quot;, &quot;337110&quot;,
 &quot;Military&quot;, &quot;928810&quot;,
 &quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;,
 &quot;Other Services (except Public Administration)&quot;, &quot;81&quot;,
 &quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;,
 &quot;Property Management&quot;, &quot;53&quot;,
 &quot;Retail Trade&quot;, &quot;44-45&quot;,
 &quot;Transportation and Warehousing&quot;, &quot;48-49&quot;,
 &quot;Utilities&quot;, &quot;22&quot;,
 &quot;Wholesale Trade&quot;, &quot;42&quot;,
 &quot;Government&quot;, &quot;92&quot;,
 &quot;23&quot;
)</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Annual_Sales_Volume__c.field-meta.xml
<CustomField>
    <fullName>Potential_Annual_Sales_Volume__c</fullName>
    <description>Score Accounts by potential annual sales volume</description>
    <inlineHelpText>A - &gt; $500,000
B - $250,000 - $499,999
C - $100,000 - $249,999 
D - $50,000 - $99,999
E - $20,000 - $49,999
F - &lt; $20,000</inlineHelpText>
    <label>Potential Annual Sales Volume</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>This object is mainly used to change any existing data from account/SAP.</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>SAP Value does not exist to create a new request.</errorMessage>
        <filterItems>
            <field>Account.SAP_Account_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Change Basic Account Information</relationshipLabel>
    <relationshipName>ChangeRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <formula>Account_Name__r.Business_Sector__r.Name</formula>
    <label>Business Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Current_Request__c.field-meta.xml
<CustomField>
    <fullName>Current_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for reporting to tell which change request is the most current.</description>
    <label>Current Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <formula>Account_Name__r.Industry_Segment__r.Name</formula>
    <label>Industry Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>Account_Name__r.NAICS_Code__c</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Account Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Commercial, Chargeback, System Administrator, Standard User, Inside Sales, Standard Healthcare, Integration, Operations, KD, Order Management Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Potential_Annual_Sales_Volume__c.field-meta.xml
<CustomField>
    <fullName>New_Potential_Annual_Sales_Volume__c</fullName>
    <description>A - &gt; $500,000
B - $250,000 - $499,999
C - $100,000 - $249,999 
D - $50,000 - $99,999
E - $20,000 - $49,999
F - &lt; $20,000</description>
    <inlineHelpText>A - &gt; $500,000
B - $250,000 - $499,999
C - $100,000 - $249,999 
D - $50,000 - $99,999
E - $20,000 - $49,999
F - &lt; $20,000</inlineHelpText>
    <label>New Potential Annual Sales Volume</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <formula>Account_Name__r.Owner.Territory_ID__c</formula>
    <label>Territory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <inlineHelpText>2-digit to 8-digit code representing the market segment of the company with which you are doing business</inlineHelpText>
    <label>NAICS Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>Hidden Field for reporting and Campaign purposes</description>
    <formula>Account.SAP_Account_ID__c</formula>
    <inlineHelpText>Hidden Field for reporting and Campaign purposes</inlineHelpText>
    <label>SAP Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>The North American Industry Classification System (NAICS) is the standard used by Federal statistical agencies in classifying business establishments for the purpose of collecting, analyzing, and publishing statistical data related to the U.S. business economy.</description>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/Two_Digit_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>Two_Digit_NAICS_Code__c</fullName>
    <label>Two Digit NAICS Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Default task, copied from &quot;Master&quot;.</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
private class AccountTriggerTest {
	private static final Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
	
	static testmethod void changeRequestTest() {	
		TestDataFactory.setupCommonVariables();	
		List<User> users = TestDataFactory.createUsers(4);
		users[0].Sears_Enterprise_Id__c = '101010';
		users[3].ProfileId = p.Id;
		users[1].Sears_Enterprise_Id__c = '202020';
		users[2].Sears_Enterprise_Id__c = '303030';
		insert users;		

		List<Territory__c> territories = TestDataFactory.createTerritories(3);
		territories[0].Territory_ID__c = '01000';
		territories[0].Enterprise_ID__c = '101010';
		territories[0].SFDC_USER_ID__c = users[0].Id;
		territories[1].Territory_ID__c = '02000';
		territories[1].Enterprise_ID__c = '202020';
		territories[1].SFDC_USER_ID__c = users[1].Id;
		territories[2].Territory_ID__c = '30000';
		territories[2].Enterprise_ID__c = '303030';
		territories[2].SFDC_USER_ID__c = users[2].Id;
		insert territories;

		List<Account> accounts = TestDataFactory.createAccounts(3);
		accounts[0].Territory_Id__c = '01000';
		accounts[0].SAP_Account_Id__c = '0010101010';
		accounts[1].Potential_Annual_Sales_Volume__c = 'B';
		accounts[1].SAP_Account_Id__c = '0020202020';
		accounts[2].SAP_Account_Id__c = '0030303030';		
		accounts[2].Potential_Annual_Sales_Volume__c = 'B';
		insert accounts;

		List<Change_Request__c> changeRequests = TestDataFactory.createChangeRequests(3);
		changeRequests[0].Account_Name__c = accounts[0].Id;
		changeRequests[1].Account_Name__c = accounts[1].Id;
		changeRequests[2].Account_Name__c = accounts[2].Id;
		changeRequests[0].New_Account_Owner__c = users[1].Id;
		changeRequests[1].New_Potential_Annual_Sales_Volume__c = 'C';
		changeRequests[2].New_Account_Owner__c = users[2].Id;		
		changeRequests[2].New_Potential_Annual_Sales_Volume__c = 'C';
		insert changeRequests;

		System.runAs(users[3]){
			accounts[0].Territory_Id__c = '02000';
			accounts[1].Potential_Annual_Sales_Volume__c = 'C';		
			accounts[2].Potential_Annual_Sales_Volume__c = 'C';
			update accounts;

			Test.startTest();
				Change_Request__c updatedRequest = [SELECT Id, Current_Request__c FROM Change_Request__c WHERE Id = :changeRequests[0].Id];
	//			System.assertEquals(false, updatedRequest.Current_Request__c);

				updatedRequest = [SELECT Id, Current_Request__c FROM Change_Request__c WHERE Id = :changeRequests[1].Id];
	//			System.assertEquals(false, updatedRequest.Current_Request__c);

				updatedRequest = [SELECT Id, Current_Request__c FROM Change_Request__c WHERE Id = :changeRequests[2].Id];
	//			System.assertEquals(true, updatedRequest.Current_Request__c);
			Test.stopTest();
		}
	}

	static testmethod void OppReassignTest(){
		TestDataFactory.setupCommonVariables();
		List<User> users = TestDataFactory.createUsers(2);
		insert users;
		users[0].ManagerId = users[1].Id;
		update users;	

		Business_Sector__c newBus = new Business_Sector__c();
		newBus.Name = 'Construction';
		insert newBus;

		Industry_Segment__c newInd = new Industry_Segment__c();
		newInd.Business_Sector__c = newBus.Id;
		newInd.Name = 'Construction - Developer Multi Family';
		newInd.Two_Digit_NAICS_Code__c = 23;
		newInd.NAICS_Code__c = '236117';
		insert newInd;

		Business_Sector__c sector = [SELECT Id FROM Business_Sector__c WHERE Name = 'Construction' LIMIT 1];
		Industry_Segment__c segment = [SELECT Id FROM Industry_Segment__c WHERE Name = 'Construction - Developer Multi Family' LIMIT 1];

		List<Account> accs = TestDataFactory.createAccounts(3);
		accs[0].OwnerId = users[0].Id;
		accs[1].OwnerId = users[0].Id;
		accs[2].OwnerId = users[0].Id;
		insert accs;

		List<Contact> contacts = TestDataFactory.createContacts(3);
		contacts[0].OwnerId = users[0].Id;
		contacts[0].AccountId = accs[0].Id;
		contacts[1].OwnerId = users[0].Id;		
		contacts[1].AccountId = accs[1].Id;
		contacts[2].OwnerId = users[0].Id;
		contacts[2].AccountId = accs[2].Id;
		insert contacts;

		List<Opportunity> opps = TestDataFactory.createOpportunities(4);
		opps[0].AccountId = accs[0].Id;
		opps[0].OwnerId = accs[0].OwnerId;
		opps[1].AccountId = accs[1].Id;		
		opps[1].OwnerId = accs[0].OwnerId;
		opps[2].AccountId = accs[2].Id;
		opps[2].OwnerId = accs[0].OwnerId;
		opps[3].AccountId = accs[2].Id;
		opps[3].OwnerId = accs[0].OwnerId;
		insert opps;

		opps[3].StageName = 'Deal Closure/Won';
		update opps[3];

		Test.startTest();
		accs[0].OwnerId = users[1].Id;
		accs[1].OwnerId = users[1].Id;
		accs[2].OwnerId = users[1].Id;
		update accs;

	//	System.assertEquals(3,[SELECT Id FROM Opportunity WHERE OwnerId = :users[1].Id].size());
	//	System.assertEquals(3, [SELECT Id FROM Contact WHERE OwnerId = :users[1].Id].size());
		Test.stopTest();
	}

	static testmethod void AccountTaskownershipChange(){
		List<User> users = TestDataFactory.createUsers(2);
		insert users;

		List<Account> Accounts = TestDataFactory.createAccounts(1);
		Accounts[0].OwnerId = users[0].Id;
		insert Accounts;

		List<Task> tasks = TestDataFactory.createTasks(2);
		tasks[0].OwnerId = users[0].Id;
		tasks[0].whatId = Accounts[0].Id;
		tasks[1].OwnerId = users[0].Id;
		tasks[1].whatId = Accounts[0].Id;
		insert tasks;

		List<Task> result = [SELECT Id FROM Task WHERE OwnerId = :users[0].Id];
		//System.assertEquals(2, result.size());

		Test.startTest();
		tasks[0].Status = 'Completed';
		update tasks[0];

		Accounts[0].OwnerId = users[1].Id;
		update Accounts;


		List<Task> result1 = [SELECT Id,Status FROM Task WHERE OwnerId = :users[1].Id];
		//System.assertEquals(1, result1.size());

		Test.stopTest();

	}
}