force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_NAICS_Code__c</fullName>
    <description>To Translate the NAICS Code from a formula field to a text value for the SAP integration.</description>
    <inlineHelpText>2-digit to 8-digit code representing the market segment of the company with which you are doing business</inlineHelpText>
    <label>SAP NAICS Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>This object is mainly used to change any existing data from account/SAP.</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>SAP Value does not exist to create a new request.</errorMessage>
        <filterItems>
            <field>Account.SAP_Account_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Change Basic Account Information</relationshipLabel>
    <relationshipName>ChangeRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Account_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_SAP_ID__c</fullName>
    <formula>Account_Name__r.SAP_Account_ID__c</formula>
    <label>Account SAP ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Account_SFDC_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_SFDC_ID__c</fullName>
    <formula>Account_Name__r.Id</formula>
    <label>Account SFDC ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <formula>Account_Name__r.Business_Sector__r.Name</formula>
    <label>Business Sector</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Current_Request__c.field-meta.xml
<CustomField>
    <fullName>Current_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for reporting to tell which change request is the most current.</description>
    <label>Current Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <formula>Account_Name__r.Industry_Segment__r.Name</formula>
    <label>Industry Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Account_Name__c</fullName>
    <label>New Account Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Account Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>contains</operation>
            <value>Commercial, Chargeback, System Administrator, Standard User, Inside Sales, Standard Healthcare, Integration, Operations, KD, Order Management Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>New_Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_City__c.field-meta.xml
<CustomField>
    <fullName>New_City__c</fullName>
    <label>New City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Country__c.field-meta.xml
<CustomField>
    <fullName>New_Country__c</fullName>
    <label>New Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Group__c</fullName>
    <label>New Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>05	Builders</fullName>
            </value>
            <value>
                <fullName>01	Educational Services</fullName>
            </value>
            <value>
                <fullName>02	Govt &amp; Military</fullName>
            </value>
            <value>
                <fullName>03	Health Care &amp; Social</fullName>
            </value>
            <value>
                <fullName>07	Others</fullName>
            </value>
            <value>
                <fullName>04	Property Mgmt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Customer_Price_Procedure__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Price_Procedure__c</fullName>
    <label>New Customer Price Procedure</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Email__c.field-meta.xml
<CustomField>
    <fullName>New_Email__c</fullName>
    <label>New Email</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Industry_Sector__c.field-meta.xml
<CustomField>
    <fullName>New_Industry_Sector__c</fullName>
    <label>New Industry Sector</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>New_Industry_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.New_Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>New_NAICS_Code__c</fullName>
    <formula>CASE( New_Industry__c, 
&quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;, 
&quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;, 
&quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;, 
&quot;Builders&quot;, &quot;23&quot;, 
&quot;Education&quot;, &quot;61&quot;, 
&quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;, 
&quot;Government&quot;, &quot;92&quot;,
&quot;Information&quot;, &quot;51&quot;, 
&quot;Insurance Companies&quot;, &quot;52&quot;, 
&quot;Lodging&quot;, &quot;72&quot;, 
&quot;Management of Companies and Enterprises&quot;, &quot;55&quot;, 
&quot;Manufacturing&quot;, &quot;337110&quot;, 
&quot;Military&quot;, &quot;928810&quot;, 
&quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;, 
&quot;Other Services (except Public Administration)&quot;, &quot;81&quot;, 
&quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;, 
&quot;Property Management&quot;, &quot;53&quot;, 
&quot;Retail Trade&quot;, &quot;44-45&quot;, 
&quot;Transportation and Warehousing&quot;, &quot;48-49&quot;, 
&quot;Utilities&quot;, &quot;22&quot;, 
&quot;Wholesale Trade&quot;, &quot;42&quot;, 
&quot;23&quot; 
)</formula>
    <label>New NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Parent_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Parent_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Parent Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Change Parent Account</relationshipLabel>
    <relationshipName>ChangeRequests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>New_Payment_Term__c</fullName>
    <label>New Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0002	14 days 2%, 30 net</fullName>
            </value>
            <value>
                <fullName>0001	Pay immediately w/o deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>New_Postal_Code__c</fullName>
    <label>New Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <formula>Account_Name__r.Owner.Territory_ID__c</formula>
    <label>Territory</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/SAP_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_NAICS_Code__c</fullName>
    <formula>NAICS_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public without sharing class AccountHandler implements ITrigger {
    List<string> sapcode = new List<string>();
    List<string> accountIds = new List<String>();
    List<string> accOwnerChanged = new List<String>();
    List<Change_Request__c> requestsToUpdate = new List<Change_Request__c>();
    List<Opportunity> oppsToUpdate = new List<Opportunity>();
    List<Contact> contactsToTupdate = new List<Contact>();
    MAP<String, Change_Request__c> changeRequestMap = new Map<String, Change_Request__c>();
    Map<string, Industry_Segment__c>  industrysegmentmap= new Map<string, Industry_Segment__c>();
    Map<Id,List<Opportunity>> oppMap = new Map<Id,List<Opportunity>>();
    Map<Id,List<Contact>> contactMap = new Map<Id,List<Contact>>();
    Map<String, String> postalCodeMap = new Map<String, String>();
    private Boolean isFirstRun;

    List<Territory__c> territories = new List<Territory__c>([SELECT Territory_Id__c, SFDC_User_Id__c FROM Territory__c]);
    Id CommercialCustomerRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Commercial Customer').getRecordTypeId();
    Id CommericalProspectRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Commercial Prospect').getRecordTypeId();
    Id HomeServicesRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Home Services').getRecordTypeId();
    private static final Id sysAdminId = [select Id from Profile where Name = 'System Administrator'].Id;
    private static final Id integrationId = [select Id from Profile where Name = 'Integration'].Id;

	// *** JEEVANA START
	Map<String, List<Task>> accTasks = new Map<String, List<Task>>();
	List<Task> tasksToUpdate = new List<Task>();
	// *** JEEVANA END
    public AccountHandler(){
    }

    public void bulkBefore(){
        isFirstRun = CommonUtils.isFirstRun('Account');
        System.debug('***** Account Trigger Ran');
        if(!Trigger.isDelete){
            if(isFirstRun){
                List<String> postalCodes = new List<String>();
                For( Account newAcc :(List<Account>)Trigger.new){
                    Sapcode.add( newAcc.SAP_NAICS_Code__C);
                    if(String.isNotBlank(newAcc.BillingPostalCode)){
                        postalCodes.add(newAcc.BillingPostalCode.Trim().Left(5));
                        System.debug('*****' + newAcc.BillingPostalCode);
                    }
                }
                System.debug('*****zip list ' + postalCodes.size());
                //If(sapcode.Size()>0){
                //    For(Industry_Segment__c NewIds :[SELECT ID, Business_Sector__c,SAP_NAICS_Code__c FROM Industry_segment__c WHERE SAP_NAICS_Code__c IN: sapcode]){
                //        industrysegmentmap.put(NewIds.SAP_NAICS_Code__c,NewIds);
                //   } 
                //}

               postalCodeMap = TerritoryUtils.getDistrictMapping(postalCodes);
               System.debug('***** map size ' + postalCodeMap.size());
            }
        }
    }

    public void bulkAfter(){   
        if(!Trigger.isDelete){
             For( Account newAcc :(List<Account>)Trigger.new){
                    accountIds.add( newAcc.Id);
                    if(Trigger.isUpdate){
                        For(Account oldAcc :(List<Account>)Trigger.old){
                        //if we are changing ownership, add to list for related object search
                        if(oldAcc.OwnerId != newAcc.OwnerId){
                            accOwnerChanged.add(oldAcc.Id);
                        }
                    }
                }
            }
            

            List<Change_Request__c> changeRequests = [SELECT Account_SAP_ID__c,Account_Name__c,Account_SFDC_ID__c,Current_Request__c,Id,Name,New_Account_Name__c,New_Account_Owner__c,New_Business_Sector__c,
                                    New_City__c,New_Country__c,New_Customer_Group__c,New_Customer_Price_Procedure__c,New_Email__c,New_Industry_Sector__c,New_Industry_Segment__c,
                                    New_NAICS_Code__c,New_Parent_Account_Name__c,New_Payment_Term__c,New_Postal_Code__c,New_Potential_Annual_Sales_Volume__c,New_Price_Group__c,
                                    New_Price_List_Type__c,New_Region__c,New_Street__c,New_Telephone__c,New_Territory_Id__c 
                                    FROM Change_Request__c WHERE Current_Request__c = true AND Account_Name__c in :accountIds];
            if(changeRequests.size() > 0){
                for(Change_Request__c reqeust : changeRequests){
                    System.debug('***** request name' + reqeust.Account_Name__c);
                    changeRequestMap.put(reqeust.Account_Name__c, reqeust);
                }
            }

            if(accOwnerChanged != null && accOwnerChanged.size() > 0){
                List<Opportunity> accOpps = [SELECT AccountId, Id, OwnerId FROM Opportunity WHERE AccountId IN :accOwnerChanged AND IsClosed = false];                
                List<Contact> accContacts= [SELECT Id, OwnerId, AccountId FROM Contact WHERE AccountId IN :accOwnerChanged AND IsDeleted = false];

                System.debug('***** Opp Size:' + accOpps.size());
                for(Opportunity opp :accOpps){
                    if(!oppMap.containsKey(opp.AccountId)){
                        System.debug('***** oppMap updated');
                        oppMap.put(opp.AccountId, new List<Opportunity>());
                    }

                    oppMap.get(opp.AccountId).add(opp);
                }
                for(Contact contact :accContacts){
                    if(!contactMap.containsKey(contact.AccountId)){
                        contactMap.put(contact.AccountId, new List<Contact>());
                    }

                    contactMap.get(contact.AccountId).add(contact);
                }
            }
            

        }
        
      // *** JEEVANA START 01
     if(!Trigger.isDelete){
         if(Trigger.isUpdate){
             List<Id> accId = new List<Id>();
             Map<Id, Id> mapAccoutOwners = new Map<Id, Id>();

             For( Account newacc :(List<Account>)Trigger.new){
                 accId.add(newacc.Id);
                 mapAccoutOwners.put(newacc.Id, newacc.OwnerId);
             }

             //tasksToUpdate = CommonUtils.updateTaskOwner(accId, Account.sObjecttype, mapAccoutOwners);

            }

         }

            // *** JEEVANA END
    }

    public void beforeInsert(Sobject obj){
        Account newObject = (Account)obj;
        
        if(newObject.ParentId == null){
            if(newObject.Delivery_Charge_First__c == null){
            	newObject.Delivery_Charge_First__c = 79;
            }
            if(newObject.Delivery_Charge_Subsequent__c == null){
            	newObject.Delivery_Charge_Subsequent__c = 25;
            }
        }

        if(newObject.BillingCountry != 'US'){
            newObject.BillingCountry = 'US';
        }

        // SCO Account Creation
        if(newObject.SCO_Account_ID__c==null ||  newObject.SCO_Account_ID__c=='' || newObject.SCO_Account_ID__c=='Processing' ){
                newObject.Create_SCO_Account__c = true;
                newObject.SCO_Account_ID__c = 'Processing';
        }
        
        //NAICS Code
        if(String.isNotBlank(newObject.Industry)){
            newObject.SAP_NAICS_Code__c = CommonUtils.getNAICSCode(newObject.Industry);            
        }

        if(newObject.RecordTypeId != HomeServicesRecordTypeId) {
            for(Territory__c territory : territories) {
                if(territory.SFDC_USER_ID__c == newObject.OwnerId) {
                    newObject.Territory_ID__c = territory.Territory_ID__c;
                }
            }

            //Territory Assignment
            if(String.isNotBlank(newObject.BillingPostalCode) && postalCodeMap.containsKey(newObject.BillingPostalCode.Trim().Left(5))){
                System.debug('***** Insert Territory__c');
                newObject.Territory__c = postalCodeMap.get(newObject.BillingPostalCode.Trim().Left(5));
            }

            if(String.isBlank(newObject.Potential_Annual_Sales_Volume__c)){
                newObject.Potential_Annual_Sales_Volume__c = 'D';
                newObject.Pricing_Tier__c = 'Bronze';
            }
        }
    }

    public void beforeUpdate(Sobject oldObj, Sobject newObj){
        Account newObject = (Account)newObj;
        Account oldObject = (Account)oldObj;
        
        if(newObject.ParentId != oldObject.ParentId){
            if(newObject.ParentId == null){
                if(newObject.Delivery_Charge_First__c == null){
                    newObject.Delivery_Charge_First__c = 79;
                }
                if(newObject.Delivery_Charge_Subsequent__c == null){
                    newObject.Delivery_Charge_Subsequent__c = 25;
                }
            }else{
                newObject.Delivery_Charge_First__c = null;
                newObject.Delivery_Charge_Subsequent__c = null;
            }
        }else{
            if(newObject.ParentId == null){
                if(newObject.Delivery_Charge_First__c == null){
                    newObject.Delivery_Charge_First__c = 79;
                }
                if(newObject.Delivery_Charge_Subsequent__c == null){
                    newObject.Delivery_Charge_Subsequent__c = 25;
                }
            }
        }
        
        
        //NAICS Code
        if(String.isNotBlank(newObject.Industry) && newObject.Industry != oldObject.Industry && (String.isBlank(newObject.SAP_Account_ID__c) || !newObject.SAP_Account_ID__c.startsWith('001'))){
            newObject.SAP_NAICS_Code__c = CommonUtils.getNAICSCode(newObject.Industry);            
        }
        else if(String.isNotBlank(newObject.SAP_NAICS_Code__c) && newObject.SAP_NAICS_Code__c != oldObject.SAP_NAICS_Code__c && String.isNotBlank(newObject.SAP_Account_ID__c) && newObject.SAP_Account_ID__c.startsWith('001')){
            newObject.Industry_Segmentation__c = CommonUtils.getIndustry(newObject.SAP_NAICS_Code__c);
        }

        if(isFirstRun){ 
            
            //If(!String.isBlank(newObject.SAP_Account_ID__c)){      
            //    If(industrysegmentmap.containskey(newObject.SAP_NAICS_Code__c)){
            //        newObject.Industry_Segment__c = industrysegmentmap.get(newObject.SAP_NAICS_Code__c).Id;
            //        newObject.Business_Sector__c = industrysegmentmap.get(newObject.SAP_NAICS_Code__c).Business_Sector__c;
            //    }
            //} 

            if(newObject.BillingCountry != 'US'){
                newObject.BillingCountry = 'US';
            }     
            
            if(String.isNotBlank(newObject.BillingPostalCode) && newObject.BillingPostalCode != oldObject.BillingPostalCode && postalCodeMap.containsKey(newObject.BillingPostalCode.Trim().Left(5))){ 
                System.debug('***** Update Territory__c');               
                newObject.Territory__c = postalCodeMap.get(newObject.BillingPostalCode.Trim().Left(5));
            }

            if(String.isNotBlank(newObject.Potential_Annual_Sales_Volume__c)){
                newObject.Pricing_Tier__c = newObject.Potential_Annual_Sales_Volume__c == 'C' ? 'Silver' : newObject.Potential_Annual_Sales_Volume__c == 'B' ? 'Gold' : newObject.Potential_Annual_Sales_Volume__c == 'A' ? 'Platinum' : 'Bronze';
            }

        //    if(String.isNotBlank(newObject.SCO_Account_ID__c) && String.isNotBlank(oldObject.SCO_Account_ID__c) &&  newObject.SCO_Account_ID__c != oldObject.SCO_Account_ID__c){
        //        newObject.Merged_SCO_Account_Id__c = newObject.SCO_Account_ID__c;
        //        newObject.SCO_Account_ID__c = oldObject.SCO_Account_ID__c;
        //    }

            updateTerritoryOwner(newObject);
        }
    }

    public  void beforeDelete(Sobject obj){
        
    }

    public void afterInsert(Sobject obj){
        
    }

    public void afterUpdate(Sobject oldObj, Sobject newObj){
        if((UserInfo.getProfileId() == sysAdminId || UserInfo.getProfileId() == integrationId) && changeRequestMap.size() > 0){            
            System.debug('***** changeRequests: ' + changeRequestMap.size());
            changeRequestDeactivation((Account)newObj);
        }
        
        reassignOpps((Account)oldObj, (Account)newObj);        
    }

    public void afterDelete(Sobject obj){

    }

    public void andFinally(){
        System.debug('***** size to update: ' + requestsToUpdate.size());
        if(requestsToUpdate.size() > 0){
            update requestsToUpdate;
        }
        if(oppsToUpdate.size() > 0){
            update oppsToUpdate;
        }
        if(contactsToTupdate.size() > 0){
            update contactsToTupdate;
        }
         //**** JEEVANA START
        if(tasksToUpdate.size() > 0){
            update tasksToUpdate;
        }
         //**** JEEVANA END
    }

    //***************************Helper Methods******************************
    private void updateTerritoryOwner(Account account){
        System.debug('*****Else If Update Started*******  ');                
        if(account.RecordTypeId == CommercialCustomerRecordTypeId) {
            for(Territory__c territory : territories) {
                if(account.Territory_ID__c == territory.Territory_ID__c) {
                    if(String.isNotBlank(territory.SFDC_USER_ID__c)){
                        System.debug('*****ACCOUNT OWNER UPDATE *******  ' + territory.Territory_ID__c + '  - ' + territory.SFDC_USER_ID__c);
                   //     account.OwnerId = territory.SFDC_USER_ID__c;
                    }
                    break;
                }  
            }
        }
        else if (account.RecordTypeId == CommericalProspectRecordTypeId) {
            for(Territory__c territory : territories) {
                if(account.OwnerId == territory.SFDC_USER_ID__c) {
                    System.debug('*****ACCOUNT OWNER UPDATE *******  ' + territory.Territory_ID__c + '  - ' + territory.SFDC_USER_ID__c);
                    account.Territory_ID__c = territory.Territory_ID__c;
                    break;
                }
            }
        }
    }

    private void changeRequestDeactivation(Account account){
        if(changeRequestMap.containskey(account.Id)){
            System.debug('****** found reqeust');
            Change_Request__c request = changeRequestMap.get(account.Id);
            Boolean needsUpdate = false;
            Boolean noError = true;

            Integer result = checkChangeRequestFields(request.New_Territory_Id__c, account.Territory_ID__c);
            if( result == 1){
                noError = false;
            }
            else if(result == 0){
                needsUpdate = true;
            }

            result = checkChangeRequestFields(request.New_Potential_Annual_Sales_Volume__c, account.Potential_Annual_Sales_Volume__c);
            if( result == 1){
                noError = false;
            }
            else if(result == 0){
                needsUpdate = true;
            }

            if(needsUpdate && noError){
                request.Current_Request__c = false;
                requestsToUpdate.add(request);
                System.debug('***** added request');
           }
        }
    }

    private Integer checkChangeRequestFields(String requestField, String accountField){
        if(String.isNotBlank(requestField)){
            if(requestField == accountField){
                return 0;
            }
            return 1;
        }

        return 2;
    }

    private void reassignOpps(Account oldAcc, Account newAcc){
        if(oldAcc.OwnerId != null && oldAcc.OwnerId != newAcc.OwnerId){
            System.debug('***** Owner Changed');
            List<Opportunity> oppList = oppMap.get(newAcc.Id);
            List<Contact> contactList = contactMap.get(newAcc.Id);

            if(oppList != NULL && oppList.size() > 0){
                for(Opportunity opp :oppList){
                    if(opp.OwnerId != newAcc.OwnerId){
                        opp.OwnerId = newAcc.OwnerId;
                        opp.Automation_Control__c = CommonUtils.getAutomationControl();
                        opp.Automation_Control_Type__c = CommonUtils.getAutomationControlTypes(true,true,true);

                        oppsToUpdate.add(opp);
                    }
                }
            }

            if(contactList != NULL && contactList.size() > 0){
                for(Contact contact :contactList){
                    if(contact.OwnerId != newAcc.OwnerId){
                        contact.OwnerId = newAcc.OwnerId;                    
                        contact.Automation_Control__c = CommonUtils.getAutomationControl();
                        contact.Automation_Control_Type__c = CommonUtils.getAutomationControlTypes(true,true,true);

                        contactsToTupdate.add(contact);
                    }
                }
            }
        }
    }
}