force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A&amp;E</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Home Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Pricing_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Customer_Pricing_Procedure__c</fullName>
    <description>1	Defaulted to &quot;Standard&quot;</description>
    <inlineHelpText>1	Standard</inlineHelpText>
    <label>Customer Pricing Procedure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>CASE( Industry,
 &quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;,
 &quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;,
 &quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;,
 &quot;Builders&quot;, &quot;23&quot;,  
 &quot;Education&quot;, &quot;61&quot;, 
 &quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;,
 &quot;Information&quot;, &quot;51&quot;,
 &quot;Insurance Companies&quot;, &quot;52&quot;,
 &quot;Lodging&quot;, &quot;72&quot;,
 &quot;Management of Companies and Enterprises&quot;, &quot;55&quot;,
 &quot;Manufacturing&quot;, &quot;337110&quot;,
 &quot;Military&quot;, &quot;928810&quot;,
 &quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;,
 &quot;Other Services (except Public Administration)&quot;, &quot;81&quot;,
 &quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;,
 &quot;Property Management&quot;, &quot;53&quot;,
 &quot;Retail Trade&quot;, &quot;44-45&quot;,
 &quot;Transportation and Warehousing&quot;, &quot;48-49&quot;,
 &quot;Utilities&quot;, &quot;22&quot;,
 &quot;Wholesale Trade&quot;, &quot;42&quot;,
 &quot;Government&quot;, &quot;92&quot;,
 &quot;23&quot;
)</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Annual_Sales_Volume__c.field-meta.xml
<CustomField>
    <fullName>Potential_Annual_Sales_Volume__c</fullName>
    <description>Score Accounts by potential annual sales volume</description>
    <inlineHelpText>A - &gt; $500,000
B - $250,000 - $499,999
C - $100,000 - $249,999 
D - $50,000 - $99,999
E - $20,000 - $49,999
F - &lt; $20,000</inlineHelpText>
    <label>Potential Annual Sales Volume</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Terms_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Terms_of_Payment__c</fullName>
    <description>0002	14 days 2%, 30 net
0001	Pay immediately w/o deduction</description>
    <inlineHelpText>0002	14 days 2%, 30 net
0001	Pay immediately w/o deduction</inlineHelpText>
    <label>Terms of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0001</fullName>
                <default>true</default>
                <label>0001</label>
            </value>
            <value>
                <fullName>0002</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>The North American Industry Classification System (NAICS) is the standard used by Federal statistical agencies in classifying business establishments for the purpose of collecting, analyzing, and publishing statistical data related to the U.S. business economy.</description>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds all zip codes with associated city and state</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateAccountDetailsControllerTest.cls
@isTest
public class UpdateAccountDetailsControllerTest{
public static testMethod void changePage(){
            Profile profile_obj = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];
            UserRole role_obj = [select id, Name from UserRole where Name = 'Sears Administrator' limit 1];

            List<User> users = TestDataFactory.createUsers(2); 
            users[0].Territory_ID__c ='35678';
            users[0].UserRoleId=role_obj.Id;
            users[0].profileid=profile_obj.Id;
            insert users;

            system.runas(users[0]){
            
        List<Zip_Code__c> lstTestZipCode = new List<Zip_Code__c>();
        
        Zip_Code__c test_zipcode_1 = new Zip_Code__c();
        test_zipcode_1.Name = '56004';
        test_zipcode_1.OwnerId = system.UserInfo.getUserId();
        test_zipcode_1.State__c = 'AL';
        
        lstTestZipCode.add(test_zipcode_1);
        
        insert lstTestZipCode;
                   
                Business_Sector__c buSec = new Business_Sector__c();
                buSec.Name='businessname';
                insert buSec;
        
                Industry_Segment__c inSec = new Industry_Segment__c();
                inSec.Business_Sector__c = buSec.id;
                inSec.Name = 'industryname';
                //inSec.NAICS_Code__c=020120;
                insert inSec;
                
                Account account_obj_1 = new Account();
                account_obj_1.Business__c = 'Commercial';
                account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
                account_obj_1.Terms_of_Payment__c = '0001';
                account_obj_1.Customer_Pricing_Procedure__c = '05';
                account_obj_1.Potential_Annual_Sales_Volume__c = 'A';
                account_obj_1.Territory_ID__c = '09836';
                account_obj_1.Territory__c = 'Test territory';
                account_obj_1.Phone = '(999) 999-9999';
                account_obj_1.Name = 'User_Account_1';
                account_obj_1.BillingStreet = '123 Test St';
                account_obj_1.BillingState = 'AL';
                account_obj_1.BillingCity = 'TestCity';
                account_obj_1.BillingPostalCode = '56004';
                account_obj_1.BillingCountry = 'US';
                account_obj_1.SAP_Account_ID__c= '51111';
                account_obj_1.Business_Sector__c =buSec.id;
                account_obj_1.Industry_Segment__c=inSec.id;
                insert account_obj_1;

                System.runAs(users[1]){
                    PageReference pageRef = Page.UpdateAccountDetails;
                    Test.setCurrentPage(pageRef);
                    ApexPages.currentPage().getParameters().put('Id', account_obj_1.id);
                    UpdateAccountDetailsController controller = new UpdateAccountDetailsController();
           //         controller.Save();
                }

                PageReference pageRef = Page.UpdateAccountDetails;
                Test.setCurrentPage(pageRef);
                ApexPages.currentPage().getParameters().put('Id', account_obj_1.id);
                UpdateAccountDetailsController controller = new UpdateAccountDetailsController();                
                String pageTest = controller.init().getUrl();
                pageTest = pageTest.substring(0,pageTest.indexOf('&'));
                System.assertNotEquals(null,pageTest);
                System.debug(pageTest);
                System.assertEquals('/apex/AccountDetailPage2?Id=' + account_obj_1.Id,pageTest);

                account_obj_1.BillingStreet = 'Test Street';
                account_obj_1.BillingPostalCode = '56004';
                update account_obj_1;
                Test.setCurrentPage(pageRef);
                ApexPages.currentPage().getParameters().put('Id', account_obj_1.id);
                controller = new UpdateAccountDetailsController();     
                pageTest = controller.init().getUrl();
                pageTest = pageTest.substring(0,pageTest.indexOf('&'));
                System.assertNotEquals(null,pageTest);
                System.debug(pageTest);
                System.assertEquals('/apex/AccountDetailPage2?Id=' + account_obj_1.Id,pageTest);

                account_obj_1.BillingPostalCode = '56004';
                update account_obj_1;
                Test.setCurrentPage(pageRef);
                ApexPages.currentPage().getParameters().put('Id', account_obj_1.id);
                controller = new UpdateAccountDetailsController();                
                pageRef = controller.init();
                //System.assertEquals(null,pageRef);

                

                controller.Save();
                controller.Cancel();
                
       }         
                
       
  }
 }