force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountOwnerAlignmentBatchTest.cls
@isTest
private class AccountOwnerAlignmentBatchTest {
	
	static testmethod void accountOwnerAlignmentTest() {
		TestDataFactory.setupCommonVariables();
		List<User> users = TestDataFactory.createUsers(5);
		insert users;
		users[0].Sears_Enterprise_Id__c = '101010';
		users[1].Sears_Enterprise_Id__c = '202020';
		users[2].Sears_Enterprise_Id__c = '303030';
		users[3].Sears_Enterprise_Id__c = '404040';
		users[4].Sears_Enterprise_Id__c = '505050';
		update users;
		

		List<Territory__c> territories = TestDataFactory.createTerritories(4);
		territories[0].Territory_ID__c = '01000';
		territories[0].Enterprise_ID__c = '101010';
		territories[0].SFDC_USER_ID__c = users[0].Id;
		territories[1].Territory_ID__c = '02000';
		territories[1].Enterprise_ID__c = '202020';
		territories[1].SFDC_USER_ID__c = users[1].Id;
		territories[2].Territory_ID__c = '30000';
		territories[2].Enterprise_ID__c = '303030';
		territories[2].SFDC_USER_ID__c = users[2].Id;
		territories[3].Territory_ID__c = '04000';
		territories[3].Enterprise_ID__c = '404040';
		territories[3].SFDC_USER_ID__c = users[3].Id;
		insert territories;

		Business_Sector__c sector = new Business_Sector__c();
		sector.Name = 'Construction';
		insert sector;

		List<Account> accounts = TestDataFactory.createAccounts(3);
		accounts[0].Territory_ID__c = territories[0].Territory_ID__c;
		accounts[0].OwnerId = territories[0].SFDC_USER_ID__c;
		accounts[0].Sap_Account_ID__C = '0011111111';
		accounts[0].Business_Sector__c = sector.Id;
		accounts[1].Territory_ID__c = territories[1].Territory_ID__c;
		accounts[1].OwnerId = territories[1].SFDC_USER_ID__c;		
		accounts[1].Sap_Account_ID__C = '0022222222';		
		accounts[1].Business_Sector__c = sector.Id;
		accounts[2].Territory_ID__c = territories[2].Territory_ID__c;
		accounts[2].OwnerId = territories[2].SFDC_USER_ID__c;		
		accounts[2].Sap_Account_ID__C = '0033333333';
		accounts[2].Business_Sector__c = sector.Id;
		insert accounts;

		Test.startTest();
		System.assertEquals(users[0].Id, territories[0].SFDC_USER_ID__c);
		System.assertEquals(territories[0].SFDC_USER_ID__c, accounts[0].OwnerId);

		territories[0].Enterprise_ID__c = '505050';
		update territories;

		List<Territory__c> territoryList = [SELECT Id, Territory_ID__c, SFDC_USER_ID__c FROM Territory__c];
		AccountOwnerAlignmentBatchClass accountAlignment = new AccountOwnerAlignmentBatchClass(territoryList);
		ID batchProcess = Database.executeBatch(accountAlignment);
		Test.stopTest();



		Account updatedAccount = [SELECT Id, OwnerId FROM Account WHERE Id = :accounts[0].Id];
	//	System.assertEquals(users[4].Id, updatedAccount.OwnerId);

	}	
}