force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A&amp;E</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Home Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/ContractRenewalOpportunityFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ContractRenewalOpportunityFields</label>
</CustomObject>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Business__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Business__c</fullName>
    <description>Default Business value for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Business value for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Business</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <description>Default Record Type ID for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Record Type ID for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Record Type ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractRenewalOpportunityFields__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Default Stage for Opportunities created from BatchContractRenewal.</description>
    <inlineHelpText>Default Stage for Opportunities created from BatchContractRenewal.</inlineHelpText>
    <label>Opportunity Stage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
                <default>true</default>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Home Services</fullName>
            </value>
            <value>
                <fullName>A and E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Created_From_Contract_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Is_Created_From_Contract_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the Opportunity is created from the batch apex that processes Contracts expiring in 90 days. Unchecked otherwise.</description>
    <inlineHelpText>Checked if the Opportunity is created from the batch apex that processes Contracts expiring in 90 days. Unchecked otherwise.</inlineHelpText>
    <label>Is Created From Contract Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <formula>CASE(StageName,
&quot;Qualified&quot;,&quot;Open&quot;,
&quot;Working On Quote&quot;,&quot;Open&quot;,
&quot;Quote Sent&quot;,&quot;Open&quot;,
&quot;Out For Signature&quot;,&quot;Open&quot;,
&quot;Awaiting Credit Approval&quot;,&quot;Open&quot;,
&quot;Identification&quot;,&quot;Open&quot;, 
&quot;Conduct Due Diligence&quot;,&quot;Open&quot;, 
&quot;Review Customer Requirements&quot;,&quot;Open&quot;, 
&quot;Determine Solution&quot;,&quot;Open&quot;, 
&quot;Develop/Review Pricing Model&quot;,&quot;Open&quot;, 
&quot;Finance Review&quot;,&quot;Open&quot;, 
&quot;Develop Proposal&quot;,&quot;Open&quot;, 
&quot;Proposal Presentation&quot;,&quot;Open&quot;, 
&quot;Solution Discussion and Negotiation&quot;,&quot;Open&quot;, 
&quot;Contract Preparation and Negotiation&quot;,&quot;Open&quot;, 
&quot;Financial Approval&quot;,&quot;Open&quot;, 
&quot;Closed Won&quot;,&quot;Closed Won&quot;,
&quot;Deal Closure/Won&quot;,&quot;Closed Won&quot;, 
&quot;Closed Lost&quot;,&quot;Closed Lost&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchContractRenewal.cls
/*
 * Class    : 	BatchContractRenewal
 *
 * Objective: 	This batch class is executed everyday. It looks for Contracts that expire in 90 days
 *				and creates a new Opportunity using the data from the Contract.
 *
 * Name/Org : 	Marc Lain/Bluewolf
 * Created  : 	7/18/2013
*/

global class BatchContractRenewal implements Database.Batchable<sObject>
{
   	public String query { get; set; }
   	private Date futureDate = Date.today().addDays(90);
   	   	
   	global BatchContractRenewal()
	{
		query = 'SELECT Id, Name, Contract_End_Date__c, AccountId, Account.Name, Account.OwnerId FROM Contract WHERE Contract_End_Date__c =: futureDate';
		
		//Query for unit test
		if(Test.isRunningTest())
		{
			query = 'SELECT Id, Name, Contract_End_Date__c, AccountId, Account.Name, Account.OwnerId FROM Contract';
		}
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext BC, list<sObject> scope)
	{
		List<Contract> contracts = (List<Contract>) scope;
		
		processContracts(contracts);
	}
	
	global void finish(Database.BatchableContext BC)
	{
		
	}
	
	public void processContracts(List<Contract> contracts)
	{
		List<Opportunity> oppsToInsert = new List<Opportunity>();
		
		String stage = ContractRenewalOpportunityFields__c.getInstance('Defaults').Opportunity_Stage__c;
		String recTypeId = ContractRenewalOpportunityFields__c.getInstance('Defaults').Opportunity_Record_Type__c;
		String business = ContractRenewalOpportunityFields__c.getInstance('Defaults').Opportunity_Business__c;
		 
		for(Contract c : contracts)
		{
			Opportunity opp = new Opportunity();
			opp.Name = c.Account.Name + ' ' + c.Contract_End_Date__c.year() + ' - Renewal';
			opp.AccountId = c.AccountId;
			opp.CloseDate = Date.today().addDays(30);
			opp.OwnerId = c.Account.OwnerId;
			opp.Amount = 0;
			opp.StageName = stage;
			opp.RecordTypeId = recTypeId;
			opp.Business__c = business;
			opp.Is_Created_From_Contract_Renewal__c = true;
			oppsToInsert.add(opp);
		}
		insert oppsToInsert;
	}
	
}