force-app/main/default/objects/Account/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <formula>CASE( Industry,
 &quot;Administrative and Support and Waste Management and Remediation Services&quot;, &quot;56&quot;,
 &quot;Agriculture, Forestry, Fishing &amp; Hunting&quot;, &quot;11&quot;,
 &quot;Arts, Entertainment, and Recreation&quot;, &quot;71&quot;,
 &quot;Builders&quot;, &quot;23&quot;,  
 &quot;Education&quot;, &quot;61&quot;, 
 &quot;Healthcare &amp; Social Assistance&quot;, &quot;62&quot;,
 &quot;Information&quot;, &quot;51&quot;,
 &quot;Insurance Companies&quot;, &quot;52&quot;,
 &quot;Lodging&quot;, &quot;72&quot;,
 &quot;Management of Companies and Enterprises&quot;, &quot;55&quot;,
 &quot;Manufacturing&quot;, &quot;337110&quot;,
 &quot;Military&quot;, &quot;928810&quot;,
 &quot;Mining, Quarrying, and Oil and Gas&quot;, &quot;21&quot;,
 &quot;Other Services (except Public Administration)&quot;, &quot;81&quot;,
 &quot;Professional, Scientific, and Technical Services&quot;, &quot;54&quot;,
 &quot;Property Management&quot;, &quot;53&quot;,
 &quot;Retail Trade&quot;, &quot;44-45&quot;,
 &quot;Transportation and Warehousing&quot;, &quot;48-49&quot;,
 &quot;Utilities&quot;, &quot;22&quot;,
 &quot;Wholesale Trade&quot;, &quot;42&quot;,
 &quot;Government&quot;, &quot;92&quot;,
 &quot;23&quot;
)</formula>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Common_Variables__c/Common_Variables__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to define common variables utilized by Apex to avoid hard coding items or using items that can change such as userIds or Stages/Statuses.</description>
    <label>Common Variables</label>
</CustomObject>

force-app/main/default/objects/Common_Variables__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Used to define the content of the variable to be referenced in Apex.</description>
    <label>Content</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/Industry_Segment__c.object-meta.xml
<CustomObject>
    <label>Industry Segment</label>
    <nameField>
        <label>Industry Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Segment__c/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <description>This is the child relationship to the Business Sector Object</description>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Industry Segments</relationshipLabel>
    <relationshipName>Industry_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>The North American Industry Classification System (NAICS) is the standard used by Federal statistical agencies in classifying business establishments for the purpose of collecting, analyzing, and publishing statistical data related to the U.S. business economy.</description>
    <label>NAICS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Segment__c/fields/Two_Digit_NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>Two_Digit_NAICS_Code__c</fullName>
    <label>Two Digit NAICS Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Sector__c.field-meta.xml
<CustomField>
    <fullName>Business_Sector__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Sector</label>
    <referenceTo>Business_Sector__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Industry Segment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Industry_Segment__c.Business_Sector__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Industry_Segment__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Default task, copied from &quot;Master&quot;.</description>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/UserTriggerTest.cls
@isTest
private class UserTriggerTest {
	
	static testmethod void inactiveUserTest() {
		Map<String, Common_Variables__c> commonVariables = TestDataFactory.createCommonVariables();
		insert commonVariables.values();		

		List<User> users = TestDataFactory.createUsers(2);
		users[0].ProfileId = commonVariables.get('Account Manager Profile Id').Content__c;
		insert users;
		users[0].ManagerId = users[1].Id;
		update users;		

		Business_Sector__c newBus = new Business_Sector__c();
		newBus.Name = 'Construction';
		insert newBus;

		Industry_Segment__c newInd = new Industry_Segment__c();
		newInd.Business_Sector__c = newBus.Id;
		newInd.Name = 'Construction - Developer Multi Family';
		newInd.Two_Digit_NAICS_Code__c = 23;
		newInd.NAICS_Code__c = '236117';
		insert newInd;

		Business_Sector__c sector = [SELECT Id FROM Business_Sector__c WHERE Name = 'Construction' LIMIT 1];
		Industry_Segment__c segment = [SELECT Id FROM Industry_Segment__c WHERE Name = 'Construction - Developer Multi Family' LIMIT 1];

		List<Account> accs = TestDataFactory.createAccounts(3);
		accs[0].OwnerId = users[0].Id;
		accs[1].OwnerId = users[0].Id;
		accs[1].SAP_Account_Id__c = '00101010';
		accs[1].RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND Name = 'Commercial Customer' LIMIT 1].Id;		
		accs[1].Business_Sector__c = sector.Id;
		accs[1].Industry_Segment__c = segment.Id;
		accs[2].OwnerId = users[1].Id;
		insert accs;

		List<Task> tasks = TestDataFactory.createTasks(4);
		tasks[0].OwnerId = users[0].Id;
		tasks[1].OwnerId = users[0].Id;
		tasks[2].OwnerId = users[0].Id;
		tasks[3].OwnerId = users[0].Id;
		insert tasks;


		tasks[3].Status = 'Completed';
		update tasks;

		List<Lead> leads = TestDataFactory.createLeads(3);
		leads[0].OwnerId = users[0].Id;
		leads[0].Business_Sector__c = sector.Id;
		leads[0].Industry_Segment__c = segment.Id;
		leads[1].OwnerId = users[0].Id;
		leads[1].Business_Sector__c = sector.Id;
		leads[1].Industry_Segment__c = segment.Id;
		leads[2].OwnerId = users[0].Id;
		leads[2].Business_Sector__c = sector.Id;
		leads[2].Industry_Segment__c = segment.Id;
		insert leads;

		//Database.LeadConvert lc = new database.LeadConvert();
		//lc.setLeadId(leads[2].id);

		//LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
		//lc.setConvertedStatus(convertStatus.MasterLabel);
		 
		//Database.LeadConvertResult lcr = Database.convertLead(lc);
		//System.assert(lcr.isSuccess());

		Test.startTest();
		
		User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
		System.runAs ( thisUser ) {
			users[0].IsActive = false;
			update users;
		}
		
		Test.stopTest();

		List<Task> inactiveUserTasks = [SELECT Id FROM Task WHERE OwnerId = :users[1].Id];
		List<Lead> inactiveUserLeads = [SELECT Id FROM Lead WHERE OwnerId = :users[1].Id];
		List<Account> inactiveUserAccounts = [SELECT Id FROM Account WHERE OwnerId = :users[1].Id];
	//	System.assertEquals(inactiveUserTasks.size(),3);
	//	System.assertEquals(inactiveUserLeads.size(),3);
	//	System.assertEquals(inactiveUserAccounts.size(),2);
	}	
}