force-app/main/default/objects/Account/fields/Create_SCO_Account__c.field-meta.xml
<CustomField>
    <fullName>Create_SCO_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to tell Sears Commercial Online that an account needs to be created and linked</description>
    <label>Create SCO Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCO_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCO_Account_ID__c</fullName>
    <description>External ID of account on Sears Commercial Online website</description>
    <externalId>true</externalId>
    <label>SCO Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateSCOAccountRequestController.cls
public class CreateSCOAccountRequestController {
    public String accountId {get; set;}
    public List<Account> lstAccount {get; set;}
    
    public CreateSCOAccountRequestController(ApexPages.StandardController controller){
        accountId= '1';
        accountId = ApexPages.CurrentPage().getparameters().get('Id');
        system.debug('accountId--> ' + accountId ); 
            
    }
    
    public PageReference redirectButton(){
        system.debug('accountId--> ' + accountId ); 
        
        lstAccount = new List<Account>();
        lstAccount = [SELECT Id, Name, Create_SCO_Account__c, SCO_Account_ID__c FROM Account WHERE Id=: accountId LIMIT 1];
        
        system.debug('lstAccount--> ' + lstAccount ); 
        
        if(lstAccount[0].SCO_Account_ID__c==null ||  lstAccount[0].SCO_Account_ID__c=='' || lstAccount[0].SCO_Account_ID__c=='Processing' ){
            for(Account ac:lstAccount){
                ac.Create_SCO_Account__c = true;
                ac.SCO_Account_ID__c = 'Processing';
         //       ac.B2B_Account_ID__c = 'Processing';
         //       ac.B2B_Account_Request__c = true;
            }
            update lstAccount;
        }
        
        system.debug('lstAccount--> ' + lstAccount ); 
        
        PageReference retURL = new PageReference('/' + accountId );
        retURL.setRedirect(true);
        return retURL;    
   //     return null; 
    }
}