force-app/main/default/objects/Account/fields/Last_Delivery_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Requested_Date__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <description>Latest Last Confirm/Delivery Requested Date from Sales Order Header</description>
    <label>Last Delivery Requested Date</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Header__c/Sales_Order_Header__c.object-meta.xml
<CustomObject>
    <label>Sales Order Header</label>
    <nameField>
        <displayFormat>SOH-{000000}</displayFormat>
        <label>Sales Order Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Headers</relationshipLabel>
    <relationshipName>Sales_Order_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Reject_Reason_Desc__c.field-meta.xml
<CustomField>
    <fullName>Item_Reject_Reason_Desc__c</fullName>
    <label>Item Reject Reason Desc</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Last_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Confirmed_Date__c</fullName>
    <label>Last Confirmed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>54</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order_Header__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Header__c</fullName>
    <label>Sales Order Header</label>
    <referenceTo>Sales_Order_Header__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesOrderLineItemTriggerTest.cls
@isTest
private class SalesOrderLineItemTriggerTest {
	
	static testmethod void requestedDeliveryDateTestMethod() {
		List<Account> accounts = TestDataFactory.createAccounts(1);
		insert accounts;

		List<Sales_Order_Header__c> headers = TestDataFactory.createSalesOrderHeaders(1);
		headers[0].Account__c = accounts[0].Id;		
		insert headers;

		List<Sales_Order_Line_Item__c> lineItems = TestDataFactory.createSalesOrderLineItems(5, headers[0].Id);
		for(Integer a = 0; a < 5; a++){
			lineItems[a].Last_Confirmed_Date__c = Date.today() + a;
			lineItems[a].Product_Id__c = (a == 4 ? '40010510000':'04660603000');			
		}

		lineItems[3].Item_Reject_Reason_Desc__c = 'Test Reason Code';

		Test.startTest();
		insert lineItems;
		
		List<Account> insertedAccount = [SELECT Id, Last_Delivery_Requested_Date__c FROM Account WHERE Id = :accounts[0].Id];
		System.assertEquals(Date.parse(insertedAccount[0].Last_Delivery_Requested_Date__c), Date.today() + 2);

		LIST<Sales_Order_Header__c> insertedHeaders = [SELECT Id, Requested_Delivery_Date__c FROM Sales_Order_Header__c WHERE Id = :headers[0].Id];
		System.assertEquals(insertedHeaders[0].Requested_Delivery_Date__c, Date.today() + 2);

		lineItems[0].Last_Confirmed_Date__c = Date.today() + 45;
		update lineItems[0];

		List<Account> updatedAccount = [SELECT Id, Last_Delivery_Requested_Date__c FROM Account WHERE Id = :accounts[0].Id];
		System.assertEquals(Date.parse(updatedAccount[0].Last_Delivery_Requested_Date__c),Date.today() + 45);
		
		LIST<Sales_Order_Header__c> updatedHeaders = [SELECT Id, Requested_Delivery_Date__c FROM Sales_Order_Header__c WHERE Id = :headers[0].Id];
		System.assertEquals(updatedHeaders[0].Requested_Delivery_Date__c, Date.today() + 45);

		List<Sales_Order_Line_Item__c> itemsToDelete = [SELECT Id FROM Sales_Order_Line_Item__c WHERE Id = :lineItems[0].Id];
		delete itemsToDelete;

		Test.stopTest();
	}
	
}