force-app/main/default/objects/Account/fields/Last_Delivery_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Requested_Date__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <description>Latest Last Confirm/Delivery Requested Date from Sales Order Header</description>
    <label>Last Delivery Requested Date</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Header__c/Sales_Order_Header__c.object-meta.xml
<CustomObject>
    <label>Sales Order Header</label>
    <nameField>
        <displayFormat>SOH-{000000}</displayFormat>
        <label>Sales Order Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Headers</relationshipLabel>
    <relationshipName>Sales_Order_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Reject_Reason_Desc__c.field-meta.xml
<CustomField>
    <fullName>Item_Reject_Reason_Desc__c</fullName>
    <label>Item Reject Reason Desc</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Last_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Confirmed_Date__c</fullName>
    <label>Last Confirmed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>54</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order_Header__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Header__c</fullName>
    <label>Sales Order Header</label>
    <referenceTo>Sales_Order_Header__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesOrderLineItemHandler.cls
public class SalesOrderLineItemHandler implements ITrigger {
    private Map<String,Account> accountRecords = new Map<String,Account>();
    private Map<String,Account> accountsToUpdate = new Map<String,Account>();
    private Map<String,Sales_Order_Header__c> headerRecords = new Map<String, Sales_Order_Header__c>();
    private Map<String, Sales_Order_Header__c> headersToUpdate = new Map<String, Sales_Order_Header__c>();

    public SalesOrderLineItemHandler() {
        
    }

    public void bulkBefore(){

    }

    public void bulkAfter(){     
        if(!Trigger.isDelete){ 
            accountRecords = new Map<String,Account>();
            SET<String> accountIds = new SET<String>();
            List<Sales_Order_Header__c> headerIds = new List<Sales_Order_Header__c>();
            
            headerIds = [SELECT Id, Account__c, Requested_Delivery_Date__c FROM Sales_Order_Header__c WHERE Id IN (SELECT Sales_Order_Header__c FROM Sales_Order_Line_Item__c WHERE Id IN :Trigger.newMap.keySet())];        

            for(Sales_Order_Header__c record :headerIds){
                headerRecords.put(record.Id, record);
                accountIds.add(record.Account__c);
            }

            List<Account> accounts = [SELECT Id, Last_Delivery_Requested_Date__c FROM Account WHERE Id IN :accountIds];

            for(Sales_Order_Header__c record :headerIds){
                for(Account account :accounts){
                    if(record.Account__c == account.Id){
                        if(accountRecords.get(record.Id) == null){
                            accountRecords.put(record.Id, account);
                        }
                    }
                }
            }
        }
    }

    public void beforeInsert(Sobject obj){

    }

    public void beforeUpdate(Sobject oldObj, Sobject newObj){

    }

    public  void beforeDelete(Sobject obj){

    }

    public void afterInsert(Sobject obj){    
        lastRequestedDateCheck((Sales_Order_Line_Item__c)obj);
    }

    public void afterUpdate(Sobject oldObj, Sobject newObj){
        lastRequestedDateCheck((Sales_Order_Line_Item__c)newObj);
    }

    public void afterDelete(Sobject obj){

    }

    public void andFinally(){
        if(accountsToUpdate.size() > 0){
            update accountsToUpdate.values();
        }

        if(headersToUpdate.size() > 0){
            update headersToUpdate.values();
        }
    }

    private void lastRequestedDateCheck(Sales_Order_Line_Item__c lineItemObject){
        Set<String> itemFilter = new Set<String>{'400', '070','010'};

        if(String.isNotEmpty(lineItemObject.Product_Id__c) && !itemFilter.contains(lineItemObject.Product_Id__c.left(3)) && String.isEmpty(lineItemObject.Item_Reject_Reason_Desc__c)){
            Account accountRecord = accountRecords.get(lineItemObject.Sales_Order_Header__c);
            Sales_Order_Header__c headerRecord = headerRecords.get(lineItemObject.Sales_Order_Header__c);

           
	        if(accountRecord != null){
		        if(!accountsToUpdate.containsKey(accountRecord.Id)){
		        	if(String.isEmpty(accountRecord.Last_Delivery_Requested_Date__c) || accountRecord.Last_Delivery_Requested_Date__c == '//' || accountRecord.Last_Delivery_Requested_Date__c == '1/1/00' || lineItemObject.Last_Confirmed_Date__c > Date.parse(accountRecord.Last_Delivery_Requested_Date__c)){
		        		accountRecord.Last_Delivery_Requested_Date__c = lineItemObject.Last_Confirmed_Date__c.format();
		        		accountsToUpdate.put(accountRecord.Id, accountRecord);
		        	}
		        }
		        else{
		        	if(String.isEmpty(accountsToUpdate.get(accountRecord.Id).Last_Delivery_Requested_Date__c) || lineItemObject.Last_Confirmed_Date__c > Date.parse(accountsToUpdate.get(accountRecord.Id).Last_Delivery_Requested_Date__c)){
		        		accountsToUpdate.get(accountRecord.Id).Last_Delivery_Requested_Date__c = lineItemObject.Last_Confirmed_Date__c.format();
		        	}
		        }
	    	}

	    	if(headerRecord != null){
		        if(!headersToUpdate.containsKey(headerRecord.Id)){
		        	if(headerRecord.Requested_Delivery_Date__c == null || lineItemObject.Last_Confirmed_Date__c > headerRecord.Requested_Delivery_Date__c){
		        		headerRecord.Requested_Delivery_Date__c = lineItemObject.Last_Confirmed_Date__c;
		        		headersToUpdate.put(headerRecord.Id, headerRecord);
		        	}
		        }
		        else{
		        	if(headersToUpdate.get(headerRecord.Id).Requested_Delivery_Date__c == null || lineItemObject.Last_Confirmed_Date__c > headersToUpdate.get(headerRecord.Id).Requested_Delivery_Date__c){
		        		headersToUpdate.get(headerRecord.Id).Requested_Delivery_Date__c = lineItemObject.Last_Confirmed_Date__c;
		        	}	        	
		        }
	        }            
        }
    }
}