force-app/main/default/objects/Account/fields/NewTerritory__c.field-meta.xml
<CustomField>
    <fullName>NewTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory ID</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts (Territory)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <description>Field needs to be translated</description>
    <label>Price List Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>C0</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C6</fullName>
            </value>
            <value>
                <fullName>C7</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CK</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CQ</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SCO_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCO_Account_ID__c</fullName>
    <description>External ID of account on Sears Commercial Online website</description>
    <externalId>true</externalId>
    <label>SCO Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/County_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Code__c</fullName>
    <label>County Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/County_Name__c.field-meta.xml
<CustomField>
    <fullName>County_Name__c</fullName>
    <label>County Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/District_Id__c.field-meta.xml
<CustomField>
    <fullName>District_Id__c</fullName>
    <label>District Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DOS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>DOS_Order_Number__c</fullName>
    <label>DOS Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Geo_Code__c.field-meta.xml
<CustomField>
    <fullName>Geo_Code__c</fullName>
    <label>Geo Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Haulaway_Charge__c.field-meta.xml
<CustomField>
    <fullName>Haulaway_Charge__c</fullName>
    <label>Haulaway Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/isCommonCarrier__c.field-meta.xml
<CustomField>
    <fullName>isCommonCarrier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCommonCarrier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Source__c.field-meta.xml
<CustomField>
    <fullName>Order_Source__c</fullName>
    <label>Order Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Standard Team</fullName>
            </value>
            <value>
                <fullName>Premier Team</fullName>
            </value>
            <value>
                <fullName>Contract Team</fullName>
            </value>
            <value>
                <fullName>Web Team</fullName>
            </value>
            <value>
                <fullName>Inside Sales Team</fullName>
            </value>
            <value>
                <fullName>Opstech</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
                <isActive>false</isActive>
                <label>OMS</label>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Origin_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Origin_Order_Date__c</fullName>
    <label>Origin Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parent_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Amended Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Premium_Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Premium_Delivery_Charge__c</fullName>
    <label>Premium Delivery Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Purchase_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Number__c</fullName>
    <label>Purchase Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/RMA_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>RMA_Order_Number__c</fullName>
    <label>RMA Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Email__c</fullName>
    <label>Shipping Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_First_Name__c</fullName>
    <label>Shipping Contact First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Last_Name__c</fullName>
    <label>Shipping Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Phone__c</fullName>
    <label>Shipping Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <label>Territory Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Configuration_Description__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Description__c</fullName>
    <label>Configuration Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isProductParent__c.field-meta.xml
<CustomField>
    <fullName>isProductParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isProductParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Parent_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part_Number__c</fullName>
    <label>Parent Part Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Catalog</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>OrderItem</fullName>
            </value>
            <value>
                <fullName>PAWarranty</fullName>
            </value>
            <value>
                <fullName>InstallationService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductParentUnique__c.field-meta.xml
<CustomField>
    <fullName>ProductParentUnique__c</fullName>
    <label>ProductParentUnique</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Reason_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Category_Code__c</fullName>
    <label>Reason Category Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Parent_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part_Number__c</fullName>
    <label>Parent Part Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason_Code__c/Reason_Code__c.object-meta.xml
<CustomObject>
    <label>Reason Code</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Reason Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason_Code__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>District_Territory_ID__c</fullName>
    <description>This field represents the 4 digit District ID.</description>
    <label>District Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StandaloneTest.cls
@isTest
public class StandaloneTest {

    static testMethod void edit_rx(){
        String orderid = '';
        String selectedAdjustment = 'Return';
        orderid = insertOrder(selectedAdjustment);
        
        system.debug('orderid--> ' + orderid );
        
        PageReference pageRef = Page.StandaloneEdit; 
        pageRef.getParameters().put('id', orderid);
        pageRef.getParameters().put('adj', selectedAdjustment);
        Test.setCurrentPage(pageRef);
        
        StandaloneEditController ctredt = new StandaloneEditController();

        ctredt.gotoOrder();
        ctredt.actionGoToSubmission();
        ctredt.getAdjustmentSelection();
        
        pageRef.getParameters().put('prcd', 'uncrate_k');
        pageRef.getParameters().put('key', 'ServicesSelect_One');
        Test.setCurrentPage(pageRef);
        
        ctredt.getAdjustmentSelection();
        ctredt.getAdjPart();
        ctredt.getPAWarrantyPart();
        ctredt.getInstallPart();
        
   //     ctredt.actionLoadProducts();
        ctredt.selectedAdjustment = 'Return';
        ctredt.selectedSCOAccount = '1100000007';
  //      ctredt.actionLoadProducts();
        ctredt.getHeaderReasonCode();
        
        
        ctredt.actionLoadAccessories();
        ctredt.selectedproductcode = '02608262000';
        ctredt.selectedzipcode = '60179';
        ctredt.actionLoadAccessories();
        
        
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionSelected();
        
        ctredt.getInstallationService();
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionInstallation();
        
        ctredt.actionAddToList();
        
        ctredt.checkAddress();
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today();
        ctredt.objOrderOverviewQry.Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = -1;
        ctredt.checkAddress();

        ctredt.objOrderOverviewQry.Reason_Code__c = 'S12';
        ctredt.objOrderOverviewQry.Purchase_Number__c = '12';
        ctredt.objOrderOverviewQry.Shipping_Contact_First_Name__c = 'Fn';
        ctredt.objOrderOverviewQry.Shipping_Contact_Last_Name__c = 'Ln';
        ctredt.objOrderOverviewQry.Shipping_Contact_Phone__c = '1234567890';
        ctredt.objOrderOverviewQry.Shipping_Contact_Email__c = 'fn@ln.com';
        ctredt.objOrderOverviewQry.ShippingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingState = 'IL';
        ctredt.objOrderOverviewQry.ShippingPostalCode = '60179';
        ctredt.objOrderOverviewQry.BillingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingState = 'IL';
        ctredt.objOrderOverviewQry.BillingPostalCode = '60179';
        ctredt.objOrderOverviewQry.DOS_Order_Number__c = '23';
        ctredt.objOrderOverviewQry.RMA_Order_Number__c = '34';
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today().addDays(-1);
        ctredt.objOrderOverviewQry.Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = 1;
        ctredt.checkAddress();
        ctredt.getAddressList();
        
        ctredt.selectedAddr = 'GEO CODE: 00 | COUNTY CODE: 031 | COUNTY NAME: COOK' ;
        ctredt.actionSaveAdjustment();
        
        ctredt.selectedSaveAdjustment = 'Exchange';
        ctredt.actionSaveAdjustment();
        
        ctredt.actionDelete();
        pageRef.getParameters().put('sid', '1');
        ctredt.actionDelete();
        
    }

    static testMethod void edit_cd(){
        String orderid = '';
        String selectedAdjustment = 'Credit Memo';
        orderid = insertOrder(selectedAdjustment);
        
        system.debug('orderid--> ' + orderid );
        
        PageReference pageRef = Page.StandaloneEdit; 
        pageRef.getParameters().put('id', orderid);
        pageRef.getParameters().put('adj', selectedAdjustment);
        Test.setCurrentPage(pageRef);
        
        StandaloneEditController ctredt = new StandaloneEditController();

        ctredt.gotoOrder();
        ctredt.actionGoToSubmission();
        ctredt.getAdjustmentSelection();
        
        pageRef.getParameters().put('prcd', 'uncrate_k');
        pageRef.getParameters().put('key', 'ServicesSelect_One');
        Test.setCurrentPage(pageRef);
        
        ctredt.getAdjustmentSelection();
        ctredt.getAdjPart();
        ctredt.getPAWarrantyPart();
        ctredt.getInstallPart();
        
  //      ctredt.actionLoadProducts();
        ctredt.selectedAdjustment = 'Credit Memo';
        ctredt.selectedSCOAccount = '1100000007';
  //      ctredt.actionLoadProducts();
        ctredt.getHeaderReasonCode();
        
        
        ctredt.actionLoadAccessories();
        ctredt.selectedproductcode = '02608262000';
        ctredt.selectedzipcode = '60179';
        ctredt.actionLoadAccessories();
        
        
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionSelected();
        
        ctredt.getInstallationService();
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionInstallation();
        
        ctredt.actionAddToList();
        
        ctredt.selectedmemoproductcode = '02608262000';
        pageRef.getParameters().put('type', 'prod');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedpart = '40010500000';
        pageRef.getParameters().put('type', 'part');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedprotection = '07062376000';
        pageRef.getParameters().put('type', 'prot');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedinstall = '01026200000';
        pageRef.getParameters().put('type', 'inst');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        
        

 //       ctredt.actionAddToList();

        
        ctredt.checkAddress();
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today();
        ctredt.objOrderOverviewQry.Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = -1;
        ctredt.checkAddress();

        ctredt.objOrderOverviewQry.Reason_Code__c = 'S12';
        ctredt.objOrderOverviewQry.Purchase_Number__c = '12';
        ctredt.objOrderOverviewQry.Shipping_Contact_First_Name__c = 'Fn';
        ctredt.objOrderOverviewQry.Shipping_Contact_Last_Name__c = 'Ln';
        ctredt.objOrderOverviewQry.Shipping_Contact_Phone__c = '1234567890';
        ctredt.objOrderOverviewQry.Shipping_Contact_Email__c = 'fn@ln.com';
        ctredt.objOrderOverviewQry.ShippingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingState = 'IL';
        ctredt.objOrderOverviewQry.ShippingPostalCode = '60179';
        ctredt.objOrderOverviewQry.BillingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingState = 'IL';
        ctredt.objOrderOverviewQry.BillingPostalCode = '60179';
        ctredt.objOrderOverviewQry.DOS_Order_Number__c = '23';
        ctredt.objOrderOverviewQry.RMA_Order_Number__c = '34';
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today().addDays(-1);
        ctredt.objOrderOverviewQry.Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = 1;
        ctredt.checkAddress();
        ctredt.getAddressList();
        
        ctredt.selectedAddr = 'GEO CODE: 00 | COUNTY CODE: 031 | COUNTY NAME: COOK' ;
        ctredt.actionSaveAdjustment();
        
        ctredt.selectedSaveAdjustment = 'Debit Memo';
        ctredt.actionSaveAdjustment();
        
        ctredt.actionDelete();
        pageRef.getParameters().put('sid', '1');
        ctredt.actionDelete();
        
    }

    public Static String insertOrder(String selectedAdjustment){
        AdjustmentFactory.insertBasics();
        
        List<Account> lstSCOAccount = new List<Account>();
        lstSCOAccount = [SELECT Id, Name, Price_List_Type__c, SCO_Account_Id__c, NewTerritory__c 
                         FROM Account 
                         LIMIT 1
                        ];
        
        String accountId = '';
        String account_new_territory = '';
        String territory_id = '';
        String district_id = '';
        
        if(lstSCOAccount.size()>0){
            accountId = lstSCOAccount[0].Id;
            account_new_territory = lstSCOAccount[0].NewTerritory__c;
            
            
            territory_id = '';
            district_id = '';
            
            List<Territory__c> lstTerritory = new List<Territory__c>();
            lstTerritory = [SELECT Id, Name, Territory_ID__c, District_Territory_ID__c 
                            FROM Territory__c 
                            WHERE Id =: account_new_territory 
                            ORDER BY Id DESC
                            LIMIT 1
                           ];
            if(lstTerritory.size()>0){
                territory_id = lstTerritory[0].Territory_ID__c;
                district_id = lstTerritory[0].District_Territory_ID__c;
            }
            
        }
        
        
        Order objOrderInsert = new Order();
        objOrderInsert.AccountId = accountId;
        //     objOrderInsert.Status = 'Submitted';
        objOrderInsert.Status = 'Adjustment Created';
        objOrderInsert.Order_Reference_Number__c = 'orn_st';
        objOrderInsert.Type = selectedAdjustment;
        objOrderInsert.Pricebook2Id='01s300000006uBlAAI';
        objOrderInsert.Order_Source__c='Salesforce';
        //     objOrderInsert.Parent_Order__c=orderId;
        objOrderInsert.District_Id__c=district_id;
        objOrderInsert.Territory_Id__c=territory_id;
        objOrderInsert.EffectiveDate = system.today();        
        objOrderInsert.Reason_Code__c = 'S12';
        objOrderInsert.Purchase_Number__c='12';
        objOrderInsert.DOS_Order_Number__c='23';
        objOrderInsert.RMA_Order_Number__c='34';
        objOrderInsert.Origin_Order_Date__c=system.today().addDays(-1);
        objOrderInsert.isCommonCarrier__c=false;
        objOrderInsert.Shipping_Contact_First_Name__c='Fn';
        objOrderInsert.Shipping_Contact_Last_Name__c='Ln';
        objOrderInsert.Shipping_Contact_Phone__c='1234567890';
        objOrderInsert.Shipping_Contact_Email__c='fn@ln.com';
        objOrderInsert.ShippingStreet='beverly st1 n dearborn';
        objOrderInsert.ShippingCity='hoffman estates';
        objOrderInsert.ShippingState='IL';
        objOrderInsert.ShippingPostalCode='60179';
        objOrderInsert.BillingStreet='beverly st1 n dearborn';
        objOrderInsert.BillingCity='hoffman estates';
        objOrderInsert.BillingState='IL';
        objOrderInsert.BillingPostalCode='60179';
        objOrderInsert.Delivery_Charge__c = 1;
        objOrderInsert.Premium_Delivery_Charge__c = 1;
        objOrderInsert.Haulaway_Charge__c = 1;
        objOrderInsert.Geo_Code__c = '00';
        objOrderInsert.County_Code__c = '031';
        objOrderInsert.County_Name__c = 'COOK';
        
        insert objOrderInsert;
        
        String saveOrderId = '';
        saveOrderId = objOrderInsert.Id;
        
        
        List<Product2> lstProduct = new List<Product2>();
        
        lstProduct = [SELECT Id, Name, ProductCode  
                      FROM Product2 
                      WHERE IsActive=true AND SBQQ__Component__c =false AND CanUseQuantitySchedule=false AND ProductCode!=null 
                     ];
        
        Map<String, String> mapPriceBookEntry = new Map<String, String>();
        List<PricebookEntry> lstPricebookEntry = new List<PricebookEntry>();
        lstPricebookEntry = [SELECT Id, Name, Product2Id  
                             FROM PricebookEntry
                             WHERE  Pricebook2Id='01s300000006uBlAAI'
                            ];
        
        for(PricebookEntry pb:lstPricebookEntry){
            mapPriceBookEntry.put(pb.Product2Id, pb.Id);
        }
        
        system.debug('mapPriceBookEntry--> ' + mapPriceBookEntry );        
        
        
        OrderItem objInsPartsOrderItem = new OrderItem();
        
        objInsPartsOrderItem.OrderId = saveOrderId;
        objInsPartsOrderItem.Number__c = '10';
        objInsPartsOrderItem.Product2Id = lstProduct[0].Id;
        objInsPartsOrderItem.Quantity = 1;
        objInsPartsOrderItem.PriceBookEntryId = mapPriceBookEntry.get(lstProduct[0].Id);
        objInsPartsOrderItem.Configuration__c = '';
        objInsPartsOrderItem.Configuration_Description__c = '';
        objInsPartsOrderItem.Feature__c = '';
        objInsPartsOrderItem.isProductParent__c = true;
        objInsPartsOrderItem.ProductParentUnique__c = lstProduct[0].Id;
        objInsPartsOrderItem.Parent_Part_Number__c = '';
        objInsPartsOrderItem.List_Unit_Price__c = 691.67;
        objInsPartsOrderItem.Net_Unit_Price__c = 649.99;
        objInsPartsOrderItem.UnitPrice = 649.99;
        
        objInsPartsOrderItem.Reason_Category_Code__c = '30';
        
        objInsPartsOrderItem.Reason_Code__c = '02';
        
        objInsPartsOrderItem.Product_Type__c = 'OrderItem';
        
        insert objInsPartsOrderItem;
        
        return saveOrderId;
        
    }
    
    static testMethod void creation_rx(){
        
        AdjustmentFactory.insertBasics();
        
        StandaloneCreationController ctredt = new StandaloneCreationController();
        
        PageReference pageRef = Page.StandaloneCreation; 
        pageRef.getParameters().put('prcd', 'uncrate_k');
        pageRef.getParameters().put('key', 'ServicesSelect_One');
        Test.setCurrentPage(pageRef);
        
        ctredt.getAdjustmentSelection();
        ctredt.getAdjPart();
        ctredt.getPAWarrantyPart();
        ctredt.getInstallPart();
        
        ctredt.actionLoadProducts();
        ctredt.selectedAdjustment = 'Return';
        ctredt.selectedSCOAccount = '1100000007';
        ctredt.actionLoadProducts();
        ctredt.getHeaderReasonCode();
        
        
        ctredt.actionLoadAccessories();
        ctredt.selectedproductcode = '02608262000';
        ctredt.selectedzipcode = '60179';
        ctredt.actionLoadAccessories();
        
        
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionSelected();
        
        ctredt.getInstallationService();
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionInstallation();
        
        ctredt.actionAddToList();
        
        ctredt.actionDelete();
        pageRef.getParameters().put('sid', '1');
        ctredt.actionDelete();
        
        ctredt.checkAddress();
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today();
        ctredt.objOrderOverviewQry.Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = -1;
        ctredt.checkAddress();

        ctredt.objOrderOverviewQry.Reason_Code__c = 'S12';
        ctredt.objOrderOverviewQry.Purchase_Number__c = '12';
        ctredt.objOrderOverviewQry.Shipping_Contact_First_Name__c = 'Fn';
        ctredt.objOrderOverviewQry.Shipping_Contact_Last_Name__c = 'Ln';
        ctredt.objOrderOverviewQry.Shipping_Contact_Phone__c = '1234567890';
        ctredt.objOrderOverviewQry.Shipping_Contact_Email__c = 'fn@ln.com';
        ctredt.objOrderOverviewQry.ShippingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingState = 'IL';
        ctredt.objOrderOverviewQry.ShippingPostalCode = '60179';
        ctredt.objOrderOverviewQry.BillingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingState = 'IL';
        ctredt.objOrderOverviewQry.BillingPostalCode = '60179';
        ctredt.objOrderOverviewQry.DOS_Order_Number__c = '23';
        ctredt.objOrderOverviewQry.RMA_Order_Number__c = '34';
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today().addDays(-1);
        ctredt.objOrderOverviewQry.Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = 1;
        ctredt.checkAddress();
        ctredt.getAddressList();
        
        ctredt.selectedAddr = 'GEO CODE: 00 | COUNTY CODE: 031 | COUNTY NAME: COOK' ;
        ctredt.actionSaveAdjustment();
        
        ctredt.selectedSaveAdjustment = 'Exchange';
        ctredt.actionSaveAdjustment();
                
        ctredt.actionDelete();
        pageRef.getParameters().put('sid', '1');
        ctredt.actionDelete();
    }   
    
    static testMethod void creation_cd(){
        
        AdjustmentFactory.insertBasics();
        
        StandaloneCreationController ctredt = new StandaloneCreationController();
        
        PageReference pageRef = Page.StandaloneCreation; 
        pageRef.getParameters().put('prcd', 'uncrate_k');
        pageRef.getParameters().put('key', 'ServicesSelect_One');
        Test.setCurrentPage(pageRef);
        
        ctredt.getAdjustmentSelection();
        ctredt.getAdjPart();
        ctredt.getPAWarrantyPart();
        ctredt.getInstallPart();
        
        ctredt.actionLoadProducts();
        ctredt.selectedAdjustment = 'Credit Memo';
        ctredt.selectedSCOAccount = '1100000007';
        ctredt.actionLoadProducts();
        ctredt.getHeaderReasonCode();
        
        
        ctredt.actionLoadAccessories();
        ctredt.selectedproductcode = '02608262000';
        ctredt.selectedzipcode = '60179';
        ctredt.actionLoadAccessories();
        
        
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionSelected();
        
        ctredt.getInstallationService();
        ctredt.selInstallation = null;
        ctredt.selInstallPrice = null;
        ctredt.actionInstallation();
        
        ctredt.actionAddToList();
        
        ctredt.selectedmemoproductcode = '02608262000';
        pageRef.getParameters().put('type', 'prod');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedpart = '40010500000';
        pageRef.getParameters().put('type', 'part');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedprotection = '07062376000';
        pageRef.getParameters().put('type', 'prot');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        ctredt.selectedinstall = '01026200000';
        pageRef.getParameters().put('type', 'inst');
        ctredt.FindProducts();
        ctredt.actionAddtoAdjustment();
        
        
        
        ctredt.actionDelete();
        pageRef.getParameters().put('sid', '1');
        ctredt.actionDelete();

 //       ctredt.actionAddToList();

        
        ctredt.checkAddress();
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today();
        ctredt.objOrderOverviewQry.Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = -1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = -1;
        ctredt.checkAddress();

        ctredt.objOrderOverviewQry.Reason_Code__c = 'S12';
        ctredt.objOrderOverviewQry.Purchase_Number__c = '12';
        ctredt.objOrderOverviewQry.Shipping_Contact_First_Name__c = 'Fn';
        ctredt.objOrderOverviewQry.Shipping_Contact_Last_Name__c = 'Ln';
        ctredt.objOrderOverviewQry.Shipping_Contact_Phone__c = '1234567890';
        ctredt.objOrderOverviewQry.Shipping_Contact_Email__c = 'fn@ln.com';
        ctredt.objOrderOverviewQry.ShippingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.ShippingState = 'IL';
        ctredt.objOrderOverviewQry.ShippingPostalCode = '60179';
        ctredt.objOrderOverviewQry.BillingStreet = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingCity = 'beverly st1 n dearborn';
        ctredt.objOrderOverviewQry.BillingState = 'IL';
        ctredt.objOrderOverviewQry.BillingPostalCode = '60179';
        ctredt.objOrderOverviewQry.DOS_Order_Number__c = '23';
        ctredt.objOrderOverviewQry.RMA_Order_Number__c = '34';
        ctredt.objOrderOverviewQry.Origin_Order_Date__c = system.today().addDays(-1);
        ctredt.objOrderOverviewQry.Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Premium_Delivery_Charge__c = 1;
        ctredt.objOrderOverviewQry.Haulaway_Charge__c = 1;
        ctredt.checkAddress();
        ctredt.getAddressList();
        
        ctredt.selectedAddr = 'GEO CODE: 00 | COUNTY CODE: 031 | COUNTY NAME: COOK' ;
        ctredt.actionSaveAdjustment();
        
        ctredt.selectedSaveAdjustment = 'Debit Memo';
        ctredt.actionSaveAdjustment();
                
        
    }   
    
    
}