force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Header__c/Sales_Order_Header__c.object-meta.xml
<CustomObject>
    <label>Sales Order Header</label>
    <nameField>
        <displayFormat>SOH-{000000}</displayFormat>
        <label>Sales Order Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Header__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Headers</relationshipLabel>
    <relationshipName>Sales_Order_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Header__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CheckOpenOrders1.cls
global class CheckOpenOrders1 implements Database.Batchable<sObject>{
 
global Database.QueryLocator start(Database.BatchableContext BC){
return Database.getQueryLocator('SELECT id,Bill_To__c,Account__c FROM Sales_Order_Header__c WHERE Bill_To__c != NULL AND Bill_To__c != \'\' ');
}
 
global void execute(Database.BatchableContext BC,List<Sales_Order_Header__c> sOrder){
    List<String> salesSAP = new List<String>();
    List<Sales_Order_Header__c> soHead = new List<Sales_Order_Header__c>();
    Map<String,id> accSAP = new Map<String,id>();
        for(Sales_Order_Header__c sO :sOrder){
            salesSAP.add('00'+sO.Bill_To__c);
          
        }
        for(Account acc :[SELECT id,SAP_Account_ID__c FROM Account WHERE SAP_Account_ID__c IN :salesSAP AND SAP_Account_ID__c!= NULL AND SAP_Account_ID__c != ' ']){
            accSAP.put(acc.SAP_Account_ID__c,acc.id);
        }
        for(Sales_Order_Header__c sOH :sOrder){
            if(accSAP.containskey('00'+sOH.Bill_To__c)){
                sOH.Account__c = accSAP.get('00'+sOH.Bill_To__c);
                soHead .add(sOH);
            }
        }
        if(soHead.size() > 0){
        update soHead;
        }
}
global void finish(Database.BatchableContext BC){
 
}
}