force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <description>Used for Territory Management</description>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name_Short__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name_Short__c</fullName>
    <label>District Manager Name Short</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/EID_Length__c.field-meta.xml
<CustomField>
    <fullName>EID_Length__c</fullName>
    <formula>LEN(Enterprise_ID__c) &lt; 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EID Length</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SFDC_USER_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_USER_ID__c</fullName>
    <label>SFDC USER ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateAccount.cls
global class updateAccount implements Database.Batchable<sObject>{
 
global Database.QueryLocator start(Database.BatchableContext BC){
return Database.getQueryLocator('SELECT Id,Territory_ID__c,SAP_Account_ID__c FROM Account where SAP_Account_ID__c!=NULL');
}
 
global void execute(Database.BatchableContext BC, List<Account> myAccs){
List<String> territoryIds = new List<String>();
//Map<String, Territory__c> tIdUIDMap = new Map<String, Territory__c>();
Map<String, Territory__c> terrmap = new Map<String, Territory__c>();
//Map<String, Territory__c> terDistName = new Map<String, Territory__c>();
//Map<String, User> sfdcID = new Map<String, User>();
//Map<String,User> userFirstName = new Map<String,User>();
List<Account> accToUpdate= new List<Account>();
for(Account acc : myAccs){
territoryIds.add(acc.Territory_ID__c);
}
List<Territory__c> allTerri = [SELECT Id,Territory_ID__c ,SFDC_USER_ID__c,District_Manager_Name_Short__c,Enterprise_ID__c,EID_length__c FROM Territory__c where Territory_ID__c IN :territoryIds];
for(Territory__c t : allTerri){
//tIdUIdmap.put(t.Enterprise_ID__c, t);
//terDistName.put(t.District_Manager_Name_Short__c,t);
terrmap.put(t.Territory_ID__c, t);
}

 for(Account acc : myAccs){
     if(terrmap.containskey(acc.Territory_ID__c)){
         acc.ownerID=terrmap.get(acc.Territory_ID__c).SFDC_USER_ID__c;
         accToUpdate.add(acc); 
     }
     
 }

 
 if(accToUpdate.size()> 0){
     //update accToUpdate;
 }
}
 
global void finish(Database.BatchableContext BC){
 
}
}