force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>This object is mainly used to change any existing data from account/SAP.</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>SAP Value does not exist to create a new request.</errorMessage>
        <filterItems>
            <field>Account.SAP_Account_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Change Basic Account Information</relationshipLabel>
    <relationshipName>ChangeRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Auto_Approve__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approve__c</fullName>
    <defaultValue>false</defaultValue>
    <description>KEEP HIDDEN: Used by workflow to automatically approve a change request when assigning a parents Tier to a child for reporting and auditing purposes.</description>
    <label>Auto Approve</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Change_Request_Approver__c.field-meta.xml
<CustomField>
    <fullName>Change_Request_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Change Request Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Change_Requests_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Current_Request__c.field-meta.xml
<CustomField>
    <fullName>Current_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for reporting to tell which change request is the most current.</description>
    <label>Current Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/New_Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>New_Pricing_Tier__c</fullName>
    <label>New Pricing Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Save</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeRequestTriggerTest.cls
@isTest
private class ChangeRequestTriggerTest {	
	static testmethod void currentChangeRequestTest() {
		TestDataFactory.setupCommonVariables();		
		List<User> users = TestDataFactory.createUsers(1);
		insert users;		

		List<Account> accounts = TestDataFactory.createAccounts(2);
		accounts[0].OwnerId = users[0].Id;
		accounts[1].OwnerId = users[0].Id;
		accounts[0].SAP_Account_ID__c = '00000001';
		accounts[1].SAP_Account_ID__c = '00000002';
		insert accounts;

		List<Change_Request__c> firstRequests = TestDataFactory.createChangeRequests(2);
		firstRequests[0].Account_Name__c = accounts[0].Id;
		firstRequests[1].Account_Name__c = accounts[1].Id;
		insert firstRequests;

		List<Change_Request__c> firstResult = [SELECT Id, Account_Name__c, Current_Request__c FROM Change_Request__c WHERE Current_Request__c = true];

		System.assert(firstResult.size() == 2);

		List<Change_Request__c> secondRequest = TestDataFactory.createChangeRequests(1, accounts[0].Id);
		insert secondRequest;

		List<Change_Request__c> secondResult = [SELECT Id, Account_Name__c, Current_Request__c FROM Change_Request__c WHERE Current_Request__c = true AND Account_Name__c = :accounts[0].Id];

		System.assert(secondResult.size() == 1);
		System.assertEquals(secondRequest[0].Id, secondResult[0].Id);

		delete secondRequest;
	}

	static testmethod void changeRequestUpdateApproverTest() {
		TestDataFactory.setupCommonVariables();

	//	Profile CommercialUserProfile = [Select Id from Profile where Name = 'Standard Commercial AM User' LIMIT 1];
		Profile CommercialUserProfile = [Select Id from Profile where Name = 'Standard User' LIMIT 1];

		List<User> managers = TestDataFactory.createUsers(2);
		managers[0].Username = 'devtestmanager1@factory.com';
		managers[1].Username = 'devtestmanager2@factory.com';
		insert managers;

		List<User> users = TestDataFactory.createUsers(2);
		users[0].ManagerId = managers[0].Id;
		users[0].ProfileId = CommercialUserProfile.Id;
		users[1].ManagerId = managers[1].Id;
		insert users;		

		List<Account> accounts = TestDataFactory.createAccounts(3);
		accounts[0].OwnerId = users[0].Id;
		accounts[1].OwnerId = users[1].Id;
		accounts[0].SAP_Account_ID__c = '00000001';
		accounts[1].SAP_Account_ID__c = '00000002';
		accounts[2].OwnerId = users[0].Id;		
		accounts[2].SAP_Account_ID__c = '00100003';
		accounts[2].ParentId = accounts[0].Id;
		insert accounts;

		List<Change_Request__c> firstRequests = TestDataFactory.createChangeRequests(3);
		firstRequests[0].Account_Name__c = accounts[0].Id;
		firstRequests[1].Account_Name__c = accounts[1].Id;
		firstRequests[2].Account_Name__c = accounts[2].Id;
		firstRequests[2].Auto_Approve__c = true;
		firstRequests[2].New_Pricing_Tier__c = 'Gold';
		insert firstRequests;	

		List<Change_Request__c> firstResult = [SELECT Id, Account_Name__c, Current_Request__c,Change_Request_Approver__c, Request_Status__c FROM Change_Request__c WHERE Account_Name__c = :accounts[0].Id OR Account_Name__c = :accounts[1].Id];

	//	System.assert(firstResult.size() == 2);	

		for(Change_Request__c record :firstResult){
			if(record.Account_Name__c == accounts[0].Id){
			//	System.assertEquals(record.Change_Request_Approver__c, users[0].ManagerId);
				record.Request_Status__c = 'Approved';
				record.New_Pricing_Tier__c = 'Gold';
				update record;
			}
			else if (record.Account_Name__c == accounts[0].Id){
			//	System.assertEquals(record.Change_Request_Approver__c, users[1].Id);
				record.Request_Status__c = 'Approved';
				record.New_Pricing_Tier__c = 'Gold';
			}

		}	
	}
	
}