force-app/main/default/objects/Account/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>SAP Account ID</description>
    <externalId>true</externalId>
    <label>SAP Account ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/Commercial_Contract__c.object-meta.xml
<CustomObject>
    <description>Sears Commercial Contracts</description>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Supplier agreement</fullName>
                <default>true</default>
                <label>Supplier agreement</label>
            </value>
            <value>
                <fullName>Subcontractor agreement</fullName>
            </value>
            <value>
                <fullName>Government agreement</fullName>
            </value>
            <value>
                <fullName>Signed Sales Order/Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <formula>HYPERLINK(&quot;/servlet/servlet.FileDownload?file=&quot;+Attachment__c, &quot;View Document&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Document</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Addendums</fullName>
            </value>
            <value>
                <fullName>Final/signed contract</fullName>
            </value>
            <value>
                <fullName>Initial forecast</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Site readiness form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the contract ends</description>
    <inlineHelpText>Contract End Date</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Contract Start Date</description>
    <inlineHelpText>Contract Start Date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_ID__c</fullName>
    <description>Hidden Field for reporting and Campaign purposes</description>
    <formula>Account.SAP_Account_ID__c</formula>
    <inlineHelpText>Hidden Field for reporting and Campaign purposes</inlineHelpText>
    <label>SAP Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Most Sears Commercial Contracts will be &quot;Product&quot; contracts, but some will be contractual agreements for &quot;Rebates&quot;.  Most Home Services / A&amp;E contracts will be &quot;Service&quot; contracts.</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UploadAttachmentCustomController.cls
public with sharing class UploadAttachmentCustomController {

    @TestVisible Account account {get;set;}
    public Commercial_Contract__c contract {get; set;}
	public transient String fileName {get;set;}
    public transient Blob fileBody {get;set;}
    public List<SelectOption> typeOptions {get; set;}
    public List<SelectOption> documentTypeOptions {get; set;}
    public String selectedType {get; set;}
    public String selectedDocumentType {get; set;}
    public String contractName {get; set;}
    private String addToContractId {get; set;}
    public Boolean readOnlyFlag {get; set;}
    private Attachment attachment {get; set;}
    private Boolean deleteContract {get; set;}    
    private Boolean deleteAttachment {get; set;}
    
    public UploadAttachmentCustomController(ApexPages.StandardController controller) {  
        readOnlyFlag = false;   
        deleteAttachment = false;
        deleteContract = false;
        if(!Test.isRunningTest()){               
            controller.addFields(new List<String>{'SAP_Account_ID__c'});
        }
        
        this.account = (Account)controller.getRecord(); 
        this.contract = new Commercial_Contract__c();
        addToContractId = system.CurrentPageReference().GetParameters().get('contractId');

        if(String.isNotBlank(addToContractId)){
            contract = [SELECT Account__c,Attachment__c,Contract_Type__c,CreatedById,CreatedDate,Document_Type__c,Document__c,End_Date__c,Id,Name,Total_Amount__c,Start_Date__c FROM Commercial_Contract__c WHERE Id = :addToContractId LIMIT 1];
            selectedType = contract.Contract_Type__c;
            selectedDocumentType = contract.Document_Type__c;
            readOnlyFlag = true;
        }

        Schema.DescribeFieldResult componentFieldDescription = Commercial_Contract__c.Document_Type__c.getDescribe();
        documentTypeOptions = new list<SelectOption>();
        for (Schema.Picklistentry picklistEntry : componentFieldDescription.getPicklistValues())
        {
            documentTypeOptions.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
        }

        Schema.DescribeFieldResult typeFieldDescription = Commercial_Contract__c.Contract_Type__c.getDescribe();
        typeOptions = new List<SelectOption>();
        for(Schema.PickListEntry picklistEntry : typeFieldDescription.getPicklistValues()){
            typeOptions.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
        }

        contractName = String.format('{0} - {1}', new String[]{account.SAP_Account_ID__c, account.Name});
    }   
    
    // creates a new Contact_Attachment__c record
    private Database.SaveResult saveCustomAttachment() {
        contract.Account__c = account.Id;
        contract.Contract_Type__c = selectedType;
        contract.Document_Type__c = selectedDocumentType;
        contract.Name = contractName;

        return Database.insert(contract);
    }
    
    // create an actual Attachment record with the Contact_Attachment__c as parent
    private Database.SaveResult saveStandardAttachment(Id parentId) {
        Database.SaveResult result;
        
        attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.parentId = parentId;
        // inser the attahcment
        result = Database.insert(attachment);
        // reset the file for the view state
        fileBody = Blob.valueOf(' ');
        return result;
    }
    
    public PageReference processUpload() {
        Database.SaveResult attachmentResult;
        Database.SaveResult customAttachmentResult;
        PageReference page = null;

        try { 
            if(fileBody != null){
                if(contract.Total_Amount__c == NULL && selectedType == 'Subcontractor agreement' && (selectedDocumentType == 'Addendums' || selectedDocumentType == 'Final/signed contract')){
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                      'Total Ammount is required for this document.'));            
                    return null;
                }
                else{
                     if(String.isBlank(addToContractId)){
                        customAttachmentResult = saveCustomAttachment();
                    
                        if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                              'Could not save attachment.'));
                            return null;
                        }

                        attachmentResult = saveStandardAttachment(customAttachmentResult.getId());
                    }
                    else{                
                        attachmentResult = saveStandardAttachment(contract.Id);
                    }
                
                    if (attachmentResult == null || !attachmentResult.isSuccess()) {
                        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                          'Could not save attachment.'));            
                        return null;
                    } else {
                        // update the custom attachment record with some attachment info
                        contract.Attachment__c = attachmentResult.getId();
                        update contract;
                    }
                }
            }
            else{
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                      'Please attach a file.'));            
                    return null;
            }
        
        } catch (Exception e) {
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                      'Failed to upload contract, please try again or contact support for assistance'));
            System.debug(e);            
        } 

        if(String.isNotBlank(addToContractId)){
            return new PageReference('/' + contract.Id);
        }
        
        return new PageReference('/'+account.Id);
    }
}