force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/B2B_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>B2B Order Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Instruction__c</fullName>
    <label>Delivery Instruction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/District_Id__c.field-meta.xml
<CustomField>
    <fullName>District_Id__c</fullName>
    <label>District Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Source__c.field-meta.xml
<CustomField>
    <fullName>Order_Source__c</fullName>
    <label>Order Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Standard Team</fullName>
            </value>
            <value>
                <fullName>Premier Team</fullName>
            </value>
            <value>
                <fullName>Contract Team</fullName>
            </value>
            <value>
                <fullName>Web Team</fullName>
            </value>
            <value>
                <fullName>Inside Sales Team</fullName>
            </value>
            <value>
                <fullName>Opstech</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
                <isActive>false</isActive>
                <label>OMS</label>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Credit Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Purchase_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Number__c</fullName>
    <label>Purchase Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <label>Territory Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Configuration_Description__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Description__c</fullName>
    <label>Configuration Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <label>Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/isProductParent__c.field-meta.xml
<CustomField>
    <fullName>isProductParent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isProductParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Tax__c.field-meta.xml
<CustomField>
    <fullName>Item_Tax__c</fullName>
    <label>Item Tax</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <label>Order Reference Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductParentUnique__c.field-meta.xml
<CustomField>
    <fullName>ProductParentUnique__c</fullName>
    <label>ProductParentUnique</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Unique_Value__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value__c</fullName>
    <externalId>true</externalId>
    <label>Unique Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Delivery_Total__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Total__c</fullName>
    <formula>Delivery_Charge__c -  Delivery_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <inlineHelpText>Solid waste fee/ Disposable fee for North Carolina &amp; South Carolina States</inlineHelpText>
    <label>Solid Waste fee/Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Reference_Number__c</fullName>
    <label>Order Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Purchase_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Number__c</fullName>
    <label>Purchase Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote Header Review</fullName>
                <default>true</default>
                <label>Quote Header Review</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Add/Edit Products</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Document Preparation</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <formula>SBQQ__Quote__r.Delivery_Charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>List_Price__c - SBQQ__AdditionalDiscountAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/BatchUpdateQuoteCCTest.cls
@isTest
public class BatchUpdateQuoteCCTest {

    static testMethod void testMethod1(){
        DataInsertFactory.insertQuote();
               
        Test.startTest();

             BatchUpdateQuoteCC obj = new  BatchUpdateQuoteCC();
            DataBase.executeBatch(obj);
        
           
        Test.stopTest();
    }
    
    static testMethod void testMethod2(){
        DataInsertFactory.insertQuote();
               
        Test.startTest();

             BatchUpdateUniqueOLI obj = new  BatchUpdateUniqueOLI();
            DataBase.executeBatch(obj);
        
           
        Test.stopTest();
    }
    
    static testMethod void testMethod3(){
        DataInsertFactory.insertQuote();
               
        SBQQ__Quote__c objTestQuote = new SBQQ__Quote__c();
        objTestQuote = [SELECT Id, Name, SBQQ__Account__c, Delivery_Total__c, Purchase_Number__c, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1 ];
            system.debug('objTestQuote --> ' + objTestQuote );
        objTestQuote.SBQQ__Status__c = 'Add/Edit Products';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Approval';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Order';
        update objTestQuote;
        Order objOrderInsert = new Order();
            objOrderInsert.SBQQ__Quote__c = objTestQuote.Id;
        //    objOrderInsert.SBQQ__Contracted__c = false;
            objOrderInsert.AccountId = objTestQuote.SBQQ__Account__c;
            objOrderInsert.Status = 'Submitted';
            objOrderInsert.EffectiveDate = system.today();
            objOrderInsert.Delivery_Date__c = system.today();
            objOrderInsert.Delivery_Instruction__c = '';
            objOrderInsert.Pricebook2Id='01s300000006uBlAAI';
            objOrderInsert.Payment_Type__c = 'Credit Card';
            objOrderInsert.Delivery_Charge__c=objTestQuote.Delivery_Total__c;
            objOrderInsert.Purchase_Number__c=objTestQuote.Purchase_Number__c;
            objOrderInsert.Order_Reference_Number__c='test_orn';
            objOrderInsert.District_Id__c='';
            objOrderInsert.Territory_Id__c='';
            objOrderInsert.Order_Source__c='Salesforce';
            objOrderInsert.Type='Order';
            objOrderInsert.B2B_Order_Id__c='4321';
        insert objOrderInsert;
        
        
        Map<String, String> mapProductPriceBook = new Map<String, String>();
        List<PricebookEntry> lstTestPricebookEntry = new List<PricebookEntry>();
            lstTestPricebookEntry = [SELECT Id, Name, Product2Id  
                                 FROM PricebookEntry 
                                 WHERE  Pricebook2Id='01s300000006uBlAAI'
                                ];
            for(PricebookEntry pb:lstTestPricebookEntry){
                mapProductPriceBook.put(pb.Product2Id, pb.Id);
            }
        
      
        
        SBQQ__QuoteLine__c objQuoteLine = new SBQQ__QuoteLine__c();
        objQuoteLine = [SELECT Id, Name, SBQQ__Quantity__c, SBQQ__Product__c, SBQQ__Product__r.ProductCode, Feature__c, 
                        	ProductParentUnique__c, List_Price__c, Net_Unit_Price__c, Disposable_Fee__c 
                        FROM SBQQ__QuoteLine__c 
                        LIMIT 1 
                       ];
        
                OrderItem objOrderItemInsert = new OrderItem();
                objOrderItemInsert.OrderId = objOrderInsert.id;
                objOrderItemInsert.Quantity = objQuoteLine.SBQQ__Quantity__c;
                objOrderItemInsert.Product2Id = objQuoteLine.SBQQ__Product__c;
                objOrderItemInsert.PriceBookEntryId = mapProductPriceBook.get(objQuoteLine.SBQQ__Product__c);
                objOrderItemInsert.Configuration__c = '';
                objOrderItemInsert.Configuration_Description__c = '';
                objOrderItemInsert.Delivery_Date__c = system.today();
                objOrderItemInsert.Number__c = '10';
                objOrderItemInsert.Feature__c = objQuoteLine.Feature__c;
                objOrderItemInsert.isProductParent__c = true;
                objOrderItemInsert.ProductParentUnique__c = objQuoteLine.ProductParentUnique__c;
                objOrderItemInsert.List_Unit_Price__c = double.valueof(objQuoteLine.List_Price__c);
                objOrderItemInsert.Net_Unit_Price__c = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.UnitPrice = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.Disposable_Fee__c = double.valueof(objQuoteLine.Disposable_Fee__c);
                objOrderItemInsert.Order_Reference_Number__c=objOrderInsert.Order_Reference_Number__c;
                objOrderItemInsert.Unique_Value__c=objOrderInsert.Order_Reference_Number__c + objQuoteLine.SBQQ__Product__r.ProductCode ;
        		objOrderItemInsert.Tax_Rate__c = 0;
        		objOrderItemInsert.SBQQ__TaxAmount__c = 0;
        		objOrderItemInsert.Item_Tax__c = 0;
        
        insert objOrderItemInsert;
        
        
        Test.startTest();

             BatchUpdateMismatchOLI obj = new  BatchUpdateMismatchOLI();
            DataBase.executeBatch(obj);
        
           
        Test.stopTest();
    }
    
    static testMethod void testMethod4(){
        DataInsertFactory.insertQuote();
               
        SBQQ__Quote__c objTestQuote = new SBQQ__Quote__c();
        objTestQuote = [SELECT Id, Name, SBQQ__Account__c, Delivery_Total__c, Purchase_Number__c, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1 ];
            system.debug('objTestQuote --> ' + objTestQuote );
        objTestQuote.SBQQ__Status__c = 'Add/Edit Products';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Approval';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Order';
        update objTestQuote;
        Order objOrderInsert = new Order();
            objOrderInsert.SBQQ__Quote__c = objTestQuote.Id;
        //    objOrderInsert.SBQQ__Contracted__c = false;
            objOrderInsert.AccountId = objTestQuote.SBQQ__Account__c;
            objOrderInsert.Status = 'Submitted';
            objOrderInsert.EffectiveDate = system.today();
            objOrderInsert.Delivery_Date__c = system.today();
            objOrderInsert.Delivery_Instruction__c = '';
            objOrderInsert.Pricebook2Id='01s300000006uBlAAI';
            objOrderInsert.Payment_Type__c = 'Credit Card';
            objOrderInsert.Delivery_Charge__c=objTestQuote.Delivery_Total__c;
            objOrderInsert.Purchase_Number__c=objTestQuote.Purchase_Number__c;
            objOrderInsert.Order_Reference_Number__c='test_orn';
            objOrderInsert.District_Id__c='';
            objOrderInsert.Territory_Id__c='';
            objOrderInsert.Order_Source__c='Salesforce';
            objOrderInsert.Type='Order';
            objOrderInsert.B2B_Order_Id__c='4321';
        insert objOrderInsert;
        
        
        Map<String, String> mapProductPriceBook = new Map<String, String>();
        List<PricebookEntry> lstTestPricebookEntry = new List<PricebookEntry>();
            lstTestPricebookEntry = [SELECT Id, Name, Product2Id  
                                 FROM PricebookEntry 
                                 WHERE  Pricebook2Id='01s300000006uBlAAI'
                                ];
            for(PricebookEntry pb:lstTestPricebookEntry){
                mapProductPriceBook.put(pb.Product2Id, pb.Id);
            }
        
      
        
        SBQQ__QuoteLine__c objQuoteLine = new SBQQ__QuoteLine__c();
        objQuoteLine = [SELECT Id, Name, SBQQ__Quantity__c, SBQQ__Product__c, SBQQ__Product__r.ProductCode, Feature__c, 
                        	ProductParentUnique__c, List_Price__c, Net_Unit_Price__c, Disposable_Fee__c 
                        FROM SBQQ__QuoteLine__c 
                        LIMIT 1 
                       ];
        
                OrderItem objOrderItemInsert = new OrderItem();
                objOrderItemInsert.OrderId = objOrderInsert.id;
                objOrderItemInsert.Quantity = objQuoteLine.SBQQ__Quantity__c;
                objOrderItemInsert.Product2Id = objQuoteLine.SBQQ__Product__c;
                objOrderItemInsert.PriceBookEntryId = mapProductPriceBook.get(objQuoteLine.SBQQ__Product__c);
                objOrderItemInsert.Configuration__c = '';
                objOrderItemInsert.Configuration_Description__c = '';
                objOrderItemInsert.Delivery_Date__c = system.today();
                objOrderItemInsert.Number__c = '10';
                objOrderItemInsert.Feature__c = objQuoteLine.Feature__c;
                objOrderItemInsert.isProductParent__c = true;
                objOrderItemInsert.ProductParentUnique__c = objQuoteLine.ProductParentUnique__c;
                objOrderItemInsert.List_Unit_Price__c = double.valueof(objQuoteLine.List_Price__c);
                objOrderItemInsert.Net_Unit_Price__c = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.UnitPrice = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.Disposable_Fee__c = double.valueof(objQuoteLine.Disposable_Fee__c);
                objOrderItemInsert.Order_Reference_Number__c=objOrderInsert.Order_Reference_Number__c;
                objOrderItemInsert.Unique_Value__c=objOrderInsert.Order_Reference_Number__c + objQuoteLine.SBQQ__Product__r.ProductCode ;
        		objOrderItemInsert.Tax_Rate__c = 0;
        		objOrderItemInsert.SBQQ__TaxAmount__c = 0;
        		objOrderItemInsert.Item_Tax__c = 0;
        
        insert objOrderItemInsert;
               
        Test.startTest();

             BatchUpdateDuplicateProducts obj = new  BatchUpdateDuplicateProducts();
            DataBase.executeBatch(obj);
        
           
        Test.stopTest();
    }
    
    static testMethod void testMethod5(){
        DataInsertFactory.insertQuote();
               
        SBQQ__Quote__c objTestQuote = new SBQQ__Quote__c();
        objTestQuote = [SELECT Id, Name, SBQQ__Account__c, Delivery_Total__c, Purchase_Number__c, SBQQ__Status__c FROM SBQQ__Quote__c LIMIT 1 ];
            system.debug('objTestQuote --> ' + objTestQuote );
        objTestQuote.SBQQ__Status__c = 'Add/Edit Products';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Approval';
        update objTestQuote;
        objTestQuote.SBQQ__Status__c = 'Order';
        update objTestQuote;
        Order objOrderInsert = new Order();
            objOrderInsert.SBQQ__Quote__c = objTestQuote.Id;
        //    objOrderInsert.SBQQ__Contracted__c = false;
            objOrderInsert.AccountId = objTestQuote.SBQQ__Account__c;
            objOrderInsert.Status = 'Submitted';
            objOrderInsert.EffectiveDate = system.today();
            objOrderInsert.Delivery_Date__c = system.today();
            objOrderInsert.Delivery_Instruction__c = '';
            objOrderInsert.Pricebook2Id='01s300000006uBlAAI';
            objOrderInsert.Payment_Type__c = 'Credit Card';
            objOrderInsert.Delivery_Charge__c=objTestQuote.Delivery_Total__c;
            objOrderInsert.Purchase_Number__c=objTestQuote.Purchase_Number__c;
            objOrderInsert.Order_Reference_Number__c='test_orn';
            objOrderInsert.District_Id__c='';
            objOrderInsert.Territory_Id__c='';
            objOrderInsert.Order_Source__c='Salesforce';
            objOrderInsert.Type='Order';
            objOrderInsert.B2B_Order_Id__c='4321';
        insert objOrderInsert;
        
        
        Map<String, String> mapProductPriceBook = new Map<String, String>();
        List<PricebookEntry> lstTestPricebookEntry = new List<PricebookEntry>();
            lstTestPricebookEntry = [SELECT Id, Name, Product2Id  
                                 FROM PricebookEntry 
                                 WHERE  Pricebook2Id='01s300000006uBlAAI'
                                ];
            for(PricebookEntry pb:lstTestPricebookEntry){
                mapProductPriceBook.put(pb.Product2Id, pb.Id);
            }
        
      
        
        SBQQ__QuoteLine__c objQuoteLine = new SBQQ__QuoteLine__c();
        objQuoteLine = [SELECT Id, Name, SBQQ__Quantity__c, SBQQ__Product__c, SBQQ__Product__r.ProductCode, Feature__c, 
                        	ProductParentUnique__c, List_Price__c, Net_Unit_Price__c, Disposable_Fee__c 
                        FROM SBQQ__QuoteLine__c 
                        LIMIT 1 
                       ];
        
                OrderItem objOrderItemInsert = new OrderItem();
                objOrderItemInsert.OrderId = objOrderInsert.id;
                objOrderItemInsert.Quantity = objQuoteLine.SBQQ__Quantity__c;
                objOrderItemInsert.Product2Id = objQuoteLine.SBQQ__Product__c;
                objOrderItemInsert.PriceBookEntryId = mapProductPriceBook.get(objQuoteLine.SBQQ__Product__c);
                objOrderItemInsert.Configuration__c = '';
                objOrderItemInsert.Configuration_Description__c = '';
                objOrderItemInsert.Delivery_Date__c = system.today();
                objOrderItemInsert.Number__c = '10';
                objOrderItemInsert.Feature__c = objQuoteLine.Feature__c;
                objOrderItemInsert.isProductParent__c = true;
                objOrderItemInsert.ProductParentUnique__c = objQuoteLine.ProductParentUnique__c;
                objOrderItemInsert.List_Unit_Price__c = double.valueof(objQuoteLine.List_Price__c);
                objOrderItemInsert.Net_Unit_Price__c = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.UnitPrice = double.valueof(objQuoteLine.Net_Unit_Price__c);
                objOrderItemInsert.Disposable_Fee__c = double.valueof(objQuoteLine.Disposable_Fee__c);
                objOrderItemInsert.Order_Reference_Number__c=objOrderInsert.Order_Reference_Number__c;
                objOrderItemInsert.Unique_Value__c=objOrderInsert.Order_Reference_Number__c + objQuoteLine.SBQQ__Product__r.ProductCode ;
        		objOrderItemInsert.Tax_Rate__c = 0;
        		objOrderItemInsert.SBQQ__TaxAmount__c = 0;
        		objOrderItemInsert.Item_Tax__c = 0;
        
        insert objOrderItemInsert;
               
        Test.startTest();

             BatchUpdateUnitPrice obj = new  BatchUpdateUnitPrice();
            DataBase.executeBatch(obj);
        
           
        Test.stopTest();
    }
    
    static testMethod void testMethod6(){
        DataInsertFactory.insertQuote();
        Account objAccount = new Account();
        objAccount = [SELECT Id FROM Account LIMIT 1];
        
        Invoice__c inv = new Invoice__c();
        inv.Parent_Account__c = objAccount.Id;
        insert inv;

        Invoice_Line_Item__c ili = new Invoice_Line_Item__c(Invoice__c = inv.Id, Invoice_Date__c = system.today(), Pay_Type__c = 'SCO' );
        insert ili;
        
        Test.startTest();
        BatchInvoiceDatePay obj = new  BatchInvoiceDatePay();
        DataBase.executeBatch(obj);
        Test.stopTest();
    }
    
    
    
    
}