force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ADDR1__c.field-meta.xml
<CustomField>
    <fullName>ADDR1__c</fullName>
    <label>ADDR1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ADDR2__c.field-meta.xml
<CustomField>
    <fullName>ADDR2__c</fullName>
    <label>ADDR2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ADDR3__c.field-meta.xml
<CustomField>
    <fullName>ADDR3__c</fullName>
    <label>ADDR3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <formula>Order__r.Account.AccountNumber</formula>
    <label>Bill To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Billing_Unit__c.field-meta.xml
<CustomField>
    <fullName>Billing_Unit__c</fullName>
    <label>Billing Unit</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Order__r.ShippingCity</formula>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>Invoice_Total__c  +  Tax_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Territory_ID__c</fullName>
    <label>Invoice Territory ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <label>Invoice Total</label>
    <summarizedField>Invoice_Line_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZF</fullName>
            </value>
            <value>
                <fullName>ZRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Pay_Type__c.field-meta.xml
<CustomField>
    <fullName>Pay_Type__c</fullName>
    <label>Pay Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>DI</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>SCO</fullName>
            </value>
            <value>
                <fullName>SCP</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SMC</fullName>
            </value>
            <value>
                <fullName>CPRO</fullName>
            </value>
            <value>
                <fullName>COM1</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CHCK</fullName>
            </value>
            <value>
                <fullName>CASH</fullName>
            </value>
            <value>
                <fullName>WIRE</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>INTL</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>ECHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Rep_Name__c</fullName>
    <label>Rep Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_to_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Name_2__c</fullName>
    <label>Ship to Name 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Name__c</fullName>
    <label>Ship to Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Order__r.ShippingState</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_Total__c.field-meta.xml
<CustomField>
    <fullName>Tax_Total__c</fullName>
    <label>Tax Total</label>
    <summarizedField>Invoice_Line_Item__c.Tax_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Order__r.ShippingPostalCode</formula>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000}</displayFormat>
        <label>Invoice Line  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_Id_Line_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id_Line_No__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id Line No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Order_Date_Entered__c.field-meta.xml
<CustomField>
    <fullName>Order_Date_Entered__c</fullName>
    <formula>Invoice__r.Order__r.CreatedDate</formula>
    <label>Order Date Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <formula>Product__r.Description</formula>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quantity__c * Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Invoice.cls
/** @Description
*   This is the decorator object for the custom object Invoice__c that implements
*   functionality to create Invoices with Invoice Line Items, create PDFs and handle Attachments
*/
public virtual class Invoice { 
    
    /** @Description    The decorated original SObject */
    public Invoice__c Record {public get; private set;}
    
    /** @Description    The invoice line items */
    public List<InvoiceLineItem> LineItems {public get; private set;}
    
    public String invoicedateformatted {
        public get {
            return Record.Invoice_Date__c.format();
        }
    }
    
    public String invoiceduedate {
        public get {
            Date dueDate = Record.Invoice_Date__c.addDays(30);
            return dueDate.format();
        }
    }
    
    
    /** @Description    Initialize the object by invoice id */
    public Invoice(String recordId) {
        try {
            this([
                SELECT 	Id,
                Name,
                ADDR1__c,
                ADDR2__c,
                ADDR3__c,
                Bill_To__c,
                Billing_Unit__c,
                City__c,
                Customer_PO__c,
                Invoice_Number__c,
                Invoice_Territory_ID__c,
                Invoice_Type__c,
                Invoice_Date__c,
                Order__c,
                Order_Number__c,
                Parent_Account__c,
                Parent_Account__r.Name,
                Parent_Account__r.BillingStreet,
                Parent_Account__r.BillingState,
                Parent_Account__r.BillingCity,
                Parent_Account__r.BillingPostalCode,
                Rep_Name__c,
                Ship_to_Name__c,
                Ship_to_Name_2__c,
                State__c,
                Zip__c, 
                Grand_Total__c,
                Invoice_Total__c,
                Tax_Total__c,
                Pay_Type__c,
                (SELECT Id,Sequence__c,Product__c,Product_Description__c,Invoice_Id_Line_No__c,Order_Date_Entered__c,Pay_Type__c,Quantity__c,
                     Tax_Amount__c,Total_Price__c,Unit_Price__c,product__r.Name, product__r.ProductCode 
                     FROM Invoice_Line_Items__r  ORDER BY Sequence__c ASC )
                FROM Invoice__c WHERE Id = :recordId
                
            ]);
        } catch (Exception e) {
        }
        
        system.debug('invoice query result '+ Record );
    }
    
    /** @Description    Initialize the object with the fully queried record */
    public Invoice(Invoice__c originalRecord) {
        Record = originalRecord;
        
        // get line items from related records
        LineItems = new List<InvoiceLineItem>();
        if (originalRecord.Invoice_Line_Items__r != null) {
            for (Invoice_Line_Item__c ili : originalRecord.Invoice_Line_Items__r) {
                LineItems.add(new InvoiceLineItem(ili));
            }

            List<InvoiceLineItem> LineItemsTemp =  new List<InvoiceLineItem>();
            Integer n = LineItems.size();
            for (Integer i = 0; i < n; i++) {
                for (Integer j = 1; j < (n-i); j++) { 
                    if (integer.valueof(LineItems[j-1].Record.Sequence__c) > integer.valueof(LineItems[j].Record.Sequence__c)) { 
                        LineItemsTemp.add(LineItems[j-1]);
                        LineItems[j-1] = LineItems[j];
                        LineItems[j] = LineItemsTemp[0];
                        LineItemsTemp.clear();
                    }
                }
            }

        }
    }
}