force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Pay_Type__c.field-meta.xml
<CustomField>
    <fullName>Pay_Type__c</fullName>
    <label>Pay Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>DI</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>SCO</fullName>
            </value>
            <value>
                <fullName>SCP</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SMC</fullName>
            </value>
            <value>
                <fullName>CPRO</fullName>
            </value>
            <value>
                <fullName>COM1</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CHCK</fullName>
            </value>
            <value>
                <fullName>CASH</fullName>
            </value>
            <value>
                <fullName>WIRE</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>INTL</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>ECHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000}</displayFormat>
        <label>Invoice Line  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchInvoiceDatePay.cls
global class BatchInvoiceDatePay implements Database.Batchable<sObject>, Database.Stateful{
      global final String Query;

   global BatchInvoiceDatePay(){
       Query = 'SELECT Id, Name, Invoice_Date__c, Pay_Type__c ' 
           + '  FROM Invoice__c ' 
           + '  WHERE Invoice_Date__c = null OR Pay_Type__c = null  ' ;
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

    global void execute(Database.BatchableContext BC, List<Invoice__c> lstInvoice ){
        
  //      system.debug('lstInvoice --> ' + lstInvoice );
        system.debug('lstInvoice.size() --> ' + lstInvoice.size() );
        
        Set<String > setInvoiceId = new Set<String >();
        
        for(Invoice__c inv:lstInvoice){
      //      system.debug('inv --> ' + inv );
            setInvoiceId.add(inv.Id);
        }
        
        List<Invoice_Line_Item__c > lstInvoiceLineItem = new List<Invoice_Line_Item__c >();
        lstInvoiceLineItem = [SELECT Id, Invoice__c, Invoice_Date__c, Pay_Type__c 
                              FROM Invoice_Line_Item__c 
                              WHERE Invoice__c IN: setInvoiceId 
                             ];
        
        Map<String, Date > mapInvoiceDate = new Map<String, Date >();
        Map<String, String > mapPayType = new Map<String, String >();
        
        for(Invoice_Line_Item__c ili:lstInvoiceLineItem){
     //       system.debug('ili --> ' + ili );
            if(ili.Invoice_Date__c!=null){
                mapInvoiceDate.put(ili.Invoice__c, ili.Invoice_Date__c);
            }
            if(ili.Pay_Type__c!=null){
                mapPayType.put(ili.Invoice__c, ili.Pay_Type__c);
            }
        }
        
       //     system.debug('mapInvoiceDate --> ' + mapInvoiceDate );
       //     system.debug('mapPayType --> ' + mapPayType );
            system.debug('mapInvoiceDate.size() --> ' + mapInvoiceDate.size() );
            system.debug('mapPayType.size() --> ' + mapPayType.size() );
        
        for(Invoice__c inv:lstInvoice){
     //       system.debug('inv --> ' + inv );
            if(mapInvoiceDate.get(inv.Id) != null){
                inv.Invoice_Date__c = mapInvoiceDate.get(inv.Id);
            }
            if(mapPayType.get(inv.Id) != null){
                inv.Pay_Type__c = mapPayType.get(inv.Id);
            }
        }
        
        for(Invoice__c inv:lstInvoice){
            system.debug('inv --> ' + inv );
        }
        
        update lstInvoice;
    }
        
       

   global void finish(Database.BatchableContext BC){
   }

}