force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ADDR1__c.field-meta.xml
<CustomField>
    <fullName>ADDR1__c</fullName>
    <label>ADDR1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Name__c</fullName>
    <label>Ship to Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000}</displayFormat>
        <label>Invoice Line  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VFInvoicePdfControllerTest.cls
@isTest
public class VFInvoicePdfControllerTest {
    
    static void makeData(){
        DataInsertFactory.insertQuote();
        Account objAccount = new Account();
        objAccount = [SELECT Id FROM Account LIMIT 1];
        List<Invoice__c> objInvoice = new List<Invoice__c>();
        objInvoice = [SELECT Id FROM Invoice__c];
        
        system.debug('objInvoice --> ' + objInvoice );
        system.debug('objInvoice.size() --> ' + objInvoice.size() );
        
        	Invoice__c invoicelist = new Invoice__c();
           	invoicelist.Invoice_number__c = 'Test123';
            invoicelist.order_number__c = '12345678';
            invoicelist.Invoice_Date__c = system.today();
            invoicelist.Parent_Account__c = objAccount.Id;
            invoicelist.Customer_PO__c = 'Test Invoice';  
            invoicelist.Ship_to_Name__c = 'Test Ship to Name';
            invoicelist.ADDR1__c = 'Test ship address';
        
        List<Invoice__c> Invoices = new List<Invoice__c>();
        Invoices.add(invoicelist);
        
          insert Invoices;
        
       Invoice_Line_Item__c InvoiceLineItems = TestDataFactory.createInvoiceLineItems(Invoices[0].Id);
            insert InvoiceLineItems;

    }
     
  //  @isTest
    static testMethod void InvoicePrintTestPDF() {
        // SETUP
        makeData();
        
        List<Invoice__c> Invoices = new List<Invoice__c>();
        Invoices = [SELECT Id FROM Invoice__c LIMIT 1];
        
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('Id', Invoices[0].Id);
        
        system.debug('IRALA');
        system.debug('IRALA---'+new VFInvoicePdfController().Invoice.Record);
        system.debug('IRALA---'+new VFInvoicePdfController().PdfTitle);
        
        // VERIFY
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice, 'Invoice');
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice.Record, 'Invoice.Record');
        System.assertnotEquals('', new VFInvoicePdfController().PdfTitle, 'PdfTitle');
        System.assertnotEquals('', new VFInvoicePdfController().Invoice.invoiceduedate, 'invoiceduedate');
        System.assertnotEquals('', new VFInvoicePdfController().Invoice.invoicedateformatted, 'invoicedateformatted');
       
    }   
}


/*

@isTest
public class VFInvoicePdfControllerTest {

    public static List<Invoice__c> Invoices;

    @TestSetup
    static void makeData(){
        //Account a = TestDataFactory.createAccounts();
        //List<Account> a = TestDataFactory.createAccounts(1);
        //insert a;

       // Invoices = TestDataFactory.createInvoice(1,a[0].Id);
        Invoices = TestDataFactory.createInvoice(1);
          insert Invoices;
        
       Invoice_Line_Item__c InvoiceLineItems = TestDataFactory.createInvoiceLineItems(Invoices[0].Id);
            insert InvoiceLineItems;

    }
     
    @isTest
    static void InvoicePrintTestPDF() {
        // SETUP
        makeData();
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('Id', Invoices[0].Id);
        
        system.debug('IRALA');
        system.debug('IRALA---'+new VFInvoicePdfController().Invoice.Record);
        system.debug('IRALA---'+new VFInvoicePdfController().PdfTitle);
        
        // VERIFY
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice, 'Invoice');
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice.Record, 'Invoice.Record');
        System.assertnotEquals('', new VFInvoicePdfController().PdfTitle, 'PdfTitle');
        System.assertnotEquals('', new VFInvoicePdfController().Invoice.invoiceduedate, 'invoiceduedate');
        System.assertnotEquals('', new VFInvoicePdfController().Invoice.invoicedateformatted, 'invoicedateformatted');
       
    }   
}

*/