force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote Header Review</fullName>
                <default>true</default>
                <label>Quote Header Review</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Add/Edit Products</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Document Preparation</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/List_Cost__c.field-meta.xml
<CustomField>
    <fullName>List_Cost__c</fullName>
    <label>List Cost</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Price_Source__c.field-meta.xml
<CustomField>
    <fullName>Price_Source__c</fullName>
    <label>Price Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KAP</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Substituted_Product__c.field-meta.xml
<CustomField>
    <fullName>Substituted_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Substituted Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines (Substituted Product)</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteLineMarginApproval.cls
public class QuoteLineMarginApproval {
    
    @InvocableMethod
    public static void calculateLineMargin(List<Id> list_qId) {
        
        System.debug('list_qId--> ' + list_qId);
            String qId = '';
        if(list_qId!=null){
            qId = list_qId[0];
            
            SBQQ__Quote__c objQuote = new SBQQ__Quote__c();
            
            objQuote = [SELECT Id, Name, SBQQ__Status__c
                        FROM SBQQ__Quote__c 
                        WHERE Id =: qId
                       ];
            
            system.debug('objQuote--> ' + objQuote );
            
            List<SBQQ__QuoteLine__c> lstQuoteLine = new List<SBQQ__QuoteLine__c>();
            lstQuoteLine = [SELECT Id, Name, List_Price__c, Feature__c, Price_Source__c, SBQQ__AdditionalDiscountAmount__c, 
                            		List_Cost__c, Substituted_Product__c 
                            FROM SBQQ__QuoteLine__c 
                            WHERE SBQQ__Quote__c =: qId
                           ];
            
            Boolean sendForApproval = false;
            Double line_price = 0;
            Double line_cost = 0;
            Double line_margin = 0;
            
            
            for(SBQQ__QuoteLine__c ql:lstQuoteLine){
                line_price = 0;
                line_cost = 0;
                line_margin = 0;
                
                if((ql.Feature__c==null || ql.Feature__c=='Parts' ) && !sendForApproval && ql.Substituted_Product__c==null ){
                    if(ql.Price_Source__c==null || ql.Price_Source__c=='' || ql.Price_Source__c=='List' || ql.Price_Source__c=='KAP' ){
                        if(ql.Price_Source__c=='KAP' && ql.SBQQ__AdditionalDiscountAmount__c!=null && ql.SBQQ__AdditionalDiscountAmount__c>0){
                            sendForApproval = true;
                        }else if(ql.Price_Source__c==null || ql.Price_Source__c=='' || ql.Price_Source__c=='List'){
                            line_price = (ql.List_Price__c==null?0:ql.List_Price__c) - (ql.SBQQ__AdditionalDiscountAmount__c==null?0:ql.SBQQ__AdditionalDiscountAmount__c);
                            line_cost = ql.List_Cost__c==null?0:ql.List_Cost__c;
                            
                            system.debug('line_price--> ' + line_price );
                            system.debug('line_cost--> ' + line_cost );
                            
                      //      if(line_price > 0 && line_cost > 0 ){
                            if(line_price != 0 ){
                                line_margin = (line_price - line_cost)/line_price;
                                if(line_margin <= 0.23995 ){
                                    sendForApproval = true;
                                }
                            }else if(line_price == 0){
                                	line_margin = 0;
                                    sendForApproval = true;
                            }
                            
                                system.debug('line_margin--> ' + line_margin );
                                system.debug('sendForApproval--> ' + sendForApproval );
                            
                        }
                    } 
                }
                
            }
            
            system.debug('sendForApproval--> ' + sendForApproval );
            
            if(sendForApproval){
                
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            //    req1.setComments('Quote Line Margin Approval.');
                req1.setObjectId(qId);
                
                req1.setSubmitterId(userinfo.getUserId()); 
                
                req1.setProcessDefinitionNameOrId('Quote_Approval_Process');
                req1.setSkipEntryCriteria(true);
                if(!Test.isRunningTest() ){
                    Approval.ProcessResult result = Approval.process(req1);
                    
                    List<Id> newWorkItemIds = result.getNewWorkitemIds();
                    system.debug('result.getInstanceStatus()--> ' + result.getInstanceStatus());
                    system.debug('result.isSuccess()--> ' + result.isSuccess());
                    system.debug('newWorkItemIds--> ' + newWorkItemIds);
                }
                
            }else{
                objQuote.SBQQ__Status__c = 'Document Preparation';
                update objQuote;
            }
            
        }
        
        
    }
    
}