force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Approval_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Approval_Deadline__c</fullName>
    <label>Approval Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QuoteBusinessHours.cls
public class QuoteBusinessHours {
    
    @InvocableMethod
    public static void quoteBusiensshour_method(List<ID> qId) {
        DateTime timestart = system.now();
        List<BusinessHours> lstBusinessHours = new List<BusinessHours>();
        lstBusinessHours = [SELECT Id, Name, IsActive, IsDefault FROM BusinessHours WHERE Name = 'IST Business Hours' LIMIT 1];
        if(lstBusinessHours.size()>0){
            Long interval = 16 * 60 * 60 * 1000;
            DateTime time2businessdays = BusinessHours.add(lstBusinessHours[0].id, timestart, interval);
            system.debug('timestart--> ' + timestart );
            system.debug('time2businessdays--> ' + time2businessdays );
            List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
            lstQuote = [SELECT Id, Name, Approval_Deadline__c FROM SBQQ__Quote__c WHERE Id =: qId LIMIT 1];
            if(lstQuote.size()>0){
                for(SBQQ__Quote__c qt:lstQuote){
                    qt.Approval_Deadline__c = time2businessdays;
                }
                update lstQuote;
            }
        }
        
    }
    
}