force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Approval_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Approval_Deadline__c</fullName>
    <label>Approval Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Approval_Stage__c</fullName>
    <label>Approval Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <isActive>false</isActive>
                <label>Not Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/ScheduledRejectComment__c.field-meta.xml
<CustomField>
    <fullName>ScheduledRejectComment__c</fullName>
    <label>ScheduledRejectComment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduledQuoteApproval.cls
global class ScheduledQuoteApproval Implements Schedulable
{
    
    
    //   ScheduledQuoteApproval rt = new ScheduledQuoteApproval();
    //   String srt = '0 13 * * * ?';
    //   String jobID = system.schedule('ScheduledQuoteApproval', srt, rt);
    
    global void execute(SchedulableContext sc){
        DateTime systemNow = system.now();
        List<SBQQ__Quote__c> lstQuote = new List<SBQQ__Quote__c>();
        lstQuote = [SELECT Id, ScheduledRejectComment__c  FROM SBQQ__Quote__c 
                    WHERE Approval_Stage__c IN (1,2,3) AND Approval_Status__c='Pending'
                    AND Approval_Deadline__c>:systemNow.addDays(1) AND Approval_Deadline__c<:systemNow.addDays(2)
                   ];
        
        
        
        Set<Id> setQuote = (new Map<Id, SBQQ__Quote__c>([SELECT Id FROM SBQQ__Quote__c 
                                                         WHERE Approval_Stage__c IN (1,2,3) AND Approval_Status__c='Pending'
                                                         AND Approval_Deadline__c>:systemNow.addDays(1) AND Approval_Deadline__c<:systemNow.addDays(2)
                                                        ])).keySet();
        //    system.debug('setQuote--> ' + setQuote );
        Set<Id> setProcessInstance = (new Map<Id, ProcessInstance>([SELECT Id,Status,TargetObjectId FROM ProcessInstance where Status='Pending' and TargetObjectId in :setQuote AND ProcessDefinition.DeveloperName='CPQ_Margin_Approval_Process'])).keySet();
        //    system.debug('setProcessInstance--> ' + setProcessInstance );
        Set<Id> setInstanceWorkitems = (new Map<Id, ProcessInstanceWorkitem>([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :setProcessInstance])).keySet();
        //     system.debug('setInstanceWorkitems--> ' + setInstanceWorkitems );
        
        List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();
        for (Id pInstanceWorkitemsId:setInstanceWorkitems){
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('The Quote is rejected because it was not approved within 2 business days.');
            req.setAction('Reject');
            req.setWorkitemId(pInstanceWorkitemsId);
            requests.add(req);
            
        }
        Approval.ProcessResult[] processResults = Approval.process(requests);
        
        for (SBQQ__Quote__c qt:lstQuote){
            qt.ScheduledRejectComment__c = 'The Quote is rejected because it was not approved within 2 business days.';
        } 
        update lstQuote;
    }
}