force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote Header Review</fullName>
                <default>true</default>
                <label>Quote Header Review</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Add/Edit Products</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Document Preparation</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QLMATest.cls
@isTest
public class QLMATest {

    static testMethod void test_QLMA(){
        
        String ran = DataInsertFactory.insertQuote();
            
        List<SBQQ__Quote__c> lstTestQuote = new List<SBQQ__Quote__c>();
        lstTestQuote = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c ORDER BY Id];
        
        system.debug('lstTestQuote --> ' + lstTestQuote.size() );
        
        for(SBQQ__Quote__c tq:lstTestQuote){
            tq.SBQQ__Status__c = 'Add/Edit Products';
        }
        update lstTestQuote;
        
        for(SBQQ__Quote__c tq:lstTestQuote){
            tq.SBQQ__Status__c = 'Approval';
        }
        update lstTestQuote;
        /*
        List<String> list_qid = new List<String>();
        for(SBQQ__Quote__c tq:lstTestQuote){
            list_qid.add(tq.Id);
        }
        
        system.debug('list_qid --> ' + list_qid );
        
        QuoteLineMarginApproval.calculateLineMargin(list_qid);
        */
    }    
    
}