force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/District_Manager_Name_Short__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Name_Short__c</fullName>
    <label>District Manager Name Short</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/EID_Length__c.field-meta.xml
<CustomField>
    <fullName>EID_Length__c</fullName>
    <formula>LEN(Enterprise_ID__c) &lt; 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EID Length</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>This is the SAP Territory ID for the assigned Territory</description>
    <label>Territory ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sears_Enterprise_id__c.field-meta.xml
<CustomField>
    <fullName>Sears_Enterprise_id__c</fullName>
    <externalId>true</externalId>
    <label>Sears_Enterprise_id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateSFDCUserIDTest.cls
@isTest
public class UpdateSFDCUserIDTest{
     static testmethod void testAccUpdate(){
     
     User user = new User();
        user.FirstName='District ';
        user.LastName='Manager';
        user.Sears_Enterprise_id__c  ='testsearchid';
        user.Username='johnacmeff@fgf.com';
        user.Email='testemail@cg.com';
        user.Alias='aa';
        user.isActive=true;
        user.CommunityNickname='testccname';
        user.TimeZoneSidKey='America/Denver';
        user.LocaleSidKey='en_US';
        user.EmailEncodingKey='UTF-8';
        user.ProfileId='00e30000001FeAR';
        user.LanguageLocaleKey='en_US';
        insert user;
     
     
     
     Territory__c terr = new Territory__c();
        terr.Territory_ID__c ='111';
        terr.FIRST_NAME__c ='testFname';
        terr.LAST_NAME__c='testLname';
        terr.Enterprise_ID__c='testsearchid';
        terr.District_Manager_Name_Short__c='District Manager';
        //terr.EID_length__c ='true';
        insert terr;
        
          Territory__c terr1 = new Territory__c();
        terr1.Territory_ID__c ='111';
        terr1.FIRST_NAME__c ='testFname';
        terr1.LAST_NAME__c='testLname';
        terr1.Enterprise_ID__c='testid';
        terr1.District_Manager_Name_Short__c='District Manager';
        //terr.EID_length__c ='true';
        insert terr1;
        
        
        

     
     }
 }