force-app/main/default/objects/Change_Request__c/Change_Request__c.object-meta.xml
<CustomObject>
    <description>This object is mainly used to change any existing data from account/SAP.</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>SAP Value does not exist to create a new request.</errorMessage>
        <filterItems>
            <field>Account.SAP_Account_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Change Basic Account Information</relationshipLabel>
    <relationshipName>ChangeRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChangeRequestIPController.cls
public class ChangeRequestIPController{

    public Change_Request__c change_request_obj {get;set;}

    public ChangeRequestIPController()
    {
    }
    
    public ChangeRequestIPController(ApexPages.StandardController controller) {
         this.change_request_obj = (Change_Request__c)controller.getRecord();         
         
    }

    public PageReference goNext(){
        if(this.change_request_obj.Account_Name__c != null){
             return this.Next();
         }
       return null;
    }
 
   
    public PageReference Next(){
               
        Id myId = this.change_request_obj.Account_Name__c;   
        
        PageReference nextPage= new PageReference('/apex/ChangeRequestPage2?myId='+myId+'&tier=false');
        nextPage.setRedirect(true);
        return nextPage;
    }
        
    public PageReference Cancel(){

        PageReference page_reference_obj_after_cancel = new PageReference('/a1M/o');
        page_reference_obj_after_cancel.setRedirect(true);

        return page_reference_obj_after_cancel;
    }   
}