force-app/main/default/objects/Lead/fields/Sales_Cycle_Log__c.field-meta.xml
<CustomField>
    <fullName>Sales_Cycle_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Cycle Log</label>
    <referenceTo>Sales_Cycle_Log__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log__c/Sales_Cycle_Log__c.object-meta.xml
<CustomObject>
    <description>Tracks IST person and date/time of Lead Status change</description>
    <label>Sales Cycle Log</label>
    <nameField>
        <displayFormat>SCL-{00000}</displayFormat>
        <label>Sales Cycle Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Cycle Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Cycle_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Cycle Log</relationshipLabel>
    <relationshipName>IST_Lead_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log_Action__c/Sales_Cycle_Log_Action__c.object-meta.xml
<CustomObject>
    <label>Sales Cycle Log Action</label>
    <nameField>
        <displayFormat>SCLA-{00000}</displayFormat>
        <label>Sales Cycle Log Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Cycle Log Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Cycle_Log_Action__c/fields/Sales_Cycle_Log__c.field-meta.xml
<CustomField>
    <fullName>Sales_Cycle_Log__c</fullName>
    <label>Sales Cycle Log</label>
    <referenceTo>Sales_Cycle_Log__c</referenceTo>
    <relationshipLabel>Sales Cycle Log Actions</relationshipLabel>
    <relationshipName>Sales_Cycle_Log_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesCycleLogActionTriggerTest.cls
@isTest
private class SalesCycleLogActionTriggerTest {
	
	static testmethod void test_method_one() {
		TestDataFactory.setupCommonVariables();

		List<Lead> leads = TestDataFactory.createLeads(1);
		insert leads;

		List<Sales_Cycle_Log__c> sclResult = [SELECT Lead__c, Id FROM Sales_Cycle_Log__c WHERE Lead__c = :leads[0].Id];

	//	System.assertEquals(1, sclResult.size());
	//	System.assertEquals(0, [SELECT Id FROM Sales_Cycle_Log_Action__c WHERE Sales_Cycle_Log__c = :sclResult[0].Id].size());

		leads[0].Status = 'Existing';
		update leads[0];

	//	System.assertEquals(1, [SELECT Id FROM Sales_Cycle_Log_Action__c WHERE Sales_Cycle_Log__c = :sclResult[0].Id].size());
if(!Test.isRunningTest()){
		update [SELECT Id FROM Sales_Cycle_Log_Action__c WHERE Sales_Cycle_Log__c = :sclResult[0].Id];
		delete [SELECT Id FROM Sales_Cycle_Log_Action__c WHERE Sales_Cycle_Log__c = :sclResult[0].Id];
}
	}
    
	static testmethod void test_method_two() {
		Sales_Cycle_Log__c sclResult = new Sales_Cycle_Log__c();
      //  sclResult.Sales_Cycle_Log__c  = '';
        insert sclResult;
        
		Sales_Cycle_Log_Action__c sclaResult = new Sales_Cycle_Log_Action__c();
        sclaResult.Sales_Cycle_Log__c = sclResult.Id;
        insert sclaResult;
        
    }    
    
}