force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Staging__c/Quote_Line_Staging__c.object-meta.xml
<CustomObject>
    <label>Quote Line Staging</label>
    <nameField>
        <displayFormat>QLS-{000000}</displayFormat>
        <label>Quote Line Staging Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Additional_Disc__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc__c</fullName>
    <label>Additional Disc</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/AdditionalDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDiscountAmount__c</fullName>
    <formula>IF( OR(ISNULL(TEXT(Discount_Operator__c)),ISNULL(Additional_Disc__c),ISNULL(List_Unit_Price__c)), 0, IF(OR(TEXT(Discount_Operator__c)==&quot;Amount&quot;,TEXT(Discount_Operator__c)==&quot;&quot;,TEXT(Discount_Operator__c)==null), Additional_Disc__c, (List_Unit_Price__c*Additional_Disc__c)/100))</formula>
    <label>Additional Disc. (Amt)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/AdditionalDiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDiscountPercent__c</fullName>
    <formula>IF( OR(ISNULL(TEXT(Discount_Operator__c)),ISNULL(List_Unit_Price__c),ISNULL(Additional_Disc__c)), 0, IF(TEXT(Discount_Operator__c)==&quot;Percent&quot;, Additional_Disc__c/100, Additional_Disc__c/List_Unit_Price__c))</formula>
    <label>Additional Disc. (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Bundled__c.field-meta.xml
<CustomField>
    <fullName>Bundled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bundled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Discount_Operator__c.field-meta.xml
<CustomField>
    <fullName>Discount_Operator__c</fullName>
    <label>Discount Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <label>Solid Waste fee/Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Earliest_Available_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Available_Date__c</fullName>
    <label>Earliest Available Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Protection Agreements</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Net_Total__c.field-meta.xml
<CustomField>
    <fullName>Net_Total__c</fullName>
    <formula>Net_Unit_Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Net_Total_Non_Discount__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Non_Discount__c</fullName>
    <formula>List_Unit_Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total (Non-Discount)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>List_Unit_Price__c - AdditionalDiscountAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Non_Discountable__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable__c</fullName>
    <formula>Product__r.SBQQ__NonDiscountable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Discountable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/PA_API_Message__c.field-meta.xml
<CustomField>
    <fullName>PA_API_Message__c</fullName>
    <label>PA API Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Stagings</relationshipLabel>
    <relationshipName>Quote_Line_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/ProductParent__c.field-meta.xml
<CustomField>
    <fullName>ProductParent__c</fullName>
    <label>ProductParent</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Quantity_Editable__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Editable__c</fullName>
    <formula>Product__r.SBQQ__QuantityEditable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Stagings</relationshipLabel>
    <relationshipName>Quote_Line_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <formula>Net_Unit_Price__c *  Tax_Rate__c *100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <formula>( Tax__c * Quantity__c) + Disposable_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/County_Code__c.field-meta.xml
<CustomField>
    <fullName>County_Code__c</fullName>
    <label>County Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Delivery_Tax__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Tax__c</fullName>
    <label>Delivery Tax</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Delivery_Total__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Total__c</fullName>
    <formula>Delivery_Charge__c -  Delivery_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Disposable_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disposable_Fee__c</fullName>
    <inlineHelpText>Solid waste fee/ Disposable fee for North Carolina &amp; South Carolina States</inlineHelpText>
    <label>Solid Waste fee/Disposable Fee</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/GeoCode__c.field-meta.xml
<CustomField>
    <fullName>GeoCode__c</fullName>
    <label>GeoCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/isTaxError__c.field-meta.xml
<CustomField>
    <fullName>isTaxError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTaxError</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <summarizedField>SBQQ__QuoteLine__c.Total_Tax_Amount__c</summarizedField>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_API_Request__c.field-meta.xml
<CustomField>
    <fullName>Tax_API_Request__c</fullName>
    <label>Tax API Request</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_API_Response__c.field-meta.xml
<CustomField>
    <fullName>Tax_API_Response__c</fullName>
    <label>Tax API Response</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProductIntegrationController.cls
public class ProductIntegrationController {
    
    public String quoteId {get; set;}
    public List<Quote_Line_Staging__c> lstQuoteLineStaging {get; set;}
    
    public ProductIntegrationController() {
        quoteId = ApexPages.CurrentPage().getparameters().get('id');
        
        lstQuoteLineStaging = new List<Quote_Line_Staging__c>();
        
        //    actionSave();
        
    }  
    
    public PageReference redirectQLE()
    {
        
        lstQuoteLineStaging = new List<Quote_Line_Staging__c>();
        lstQuoteLineStaging = [SELECT Id, Name, AdditionalDiscountAmount__c, AdditionalDiscountPercent__c, Quote__c, 
                               Product__c, Quantity__c, List_Unit_Price__c, Product__r.ProductCode, Product__r.Name, 
                               Product__r.Description, Non_Discountable__c, Quantity_Editable__c, Bundled__c, 
                               Net_Unit_Price__c, Net_Total__c, Available_Quantity__c, PA_API_Message__c, Available__c, 
                               Earliest_Available_Date__c, Disposable_Fee__c, //Shipping_Charge__c,
                               Tax_Rate__c, Total_Tax_Amount__c, Tax_Amount__c, Tax__c,Additional_Disc__c, Discount_Operator__c, 
                               isProductParent__c, ProductParent__c, ProductParentUnique__c, Feature__c, 
                               Net_Total_Non_Discount__c, Target_Customer_Amount__c 
                               FROM Quote_Line_Staging__c 
                               WHERE Quote__c = :quoteId
                              ];
        system.debug('lstQuoteLineStaging--> ' + lstQuoteLineStaging );
        
        PageReference retURL = new PageReference('/apex/ProductIntegration2?id=' + quoteId );
        
        if(lstQuoteLineStaging.size()>0){
            
            //     Quotehandler.ProdAvailCheckCallout(qheader.Id);
            SBQQ__Quote__c qheader = new SBQQ__Quote__c();
            qheader = [select SBQQ__NetAmount__c , SBQQ__ShippingCity__c, SBQQ__ShippingPostalCode__c, SBQQ__ShippingState__c, SBQQ__ShippingStreet__c, GeoCode__c, County_Code__c, SBQQ__Account__c, Delivery_Total__c, Delivery_Tax__c, Tax_API_Request__c, Tax_API_Response__c, isTaxError__c from SBQQ__Quote__c where Id = :quoteId LIMIT 1];
            if(qheader!=null && qheader.SBQQ__ShippingPostalCode__c!=null ){
                CalloutTaxCalculationAPI6.TaxCalcWrapper(qheader);
                //  	CalloutProdInventoryCheckAPI6.ProdAvailCheckWrapper(qheader);
            }
            
        }else{
            SBQQ__Quote__c qheader = new SBQQ__Quote__c();
            qheader = [select Id, Delivery_Tax__c from SBQQ__Quote__c where Id = :quoteId LIMIT 1];
        system.debug('qheader--> ' + qheader );
            qheader.Delivery_Tax__c = 0;
        system.debug('qheader--> ' + qheader );
            update qheader;
        system.debug('qheader--> ' + qheader );
            retURL = new PageReference('/apex/QuoteLineEditor?id=' + quoteId );
        }
        retURL.setRedirect(true);
        return retURL;
    }
    
    
    
}