force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Pricing__c/Product_Pricing__c.object-meta.xml
<CustomObject>
    <label>Product Pricing</label>
    <nameField>
        <displayFormat>PP-{0000000}</displayFormat>
        <label>Product Pricing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Pricing__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Staging__c/Quote_Line_Staging__c.object-meta.xml
<CustomObject>
    <label>Quote Line Staging</label>
    <nameField>
        <displayFormat>QLS-{000000}</displayFormat>
        <label>Quote Line Staging Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Staging__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Stagings</relationshipLabel>
    <relationshipName>Quote_Line_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QLESupportTest2.cls
@isTest
public class QLESupportTest2 {

    static testMethod void ProductAccesorries_Test0_pu(){
        
        DataInsertFactory.insertQuote();
                    
        List<SBQQ__Quote__c> lstTestQuote = new List<SBQQ__Quote__c>();
        lstTestQuote = [SELECT Id FROM SBQQ__Quote__c ORDER BY Id];
        
        List<Product2> lstTestProduct = new List<Product2>();
        lstTestProduct = [SELECT Id, ProductCode FROM Product2 ORDER BY Id];
        
        List<Product_Pricing__c> lstTestPP = new List<Product_Pricing__c>();
        Product_Pricing__c test_PP_1 = new Product_Pricing__c();
        
        for(Product2 tp:lstTestProduct){
            test_PP_1 = new Product_Pricing__c();
        	test_PP_1.Material_Number__c = tp.ProductCode;
        	test_PP_1.Price__c = 500;
        	test_PP_1.Cost__c = 250;
        	lstTestPP.add(test_PP_1);
        }
        insert lstTestPP;
        
        List<Quote_Line_Staging__c> lstTestQLS = new List<Quote_Line_Staging__c>();
        lstTestQLS = [SELECT Id, Product__c, ProductParentUnique__c FROM Quote_Line_Staging__c ORDER BY Id];
        
        PageReference pageRef = Page.ProductAccesorries; 
        pageRef.getParameters().put('id', lstTestQuote[0].Id);
        pageRef.getParameters().put('prodid', lstTestQLS[0].Product__c);
        pageRef.getParameters().put('pu', lstTestQLS[0].ProductParentUnique__c);

        Test.setCurrentPage(pageRef);
        
            
        ProductAccesorriesController ctredt = new ProductAccesorriesController();
        ctredt.redirectQLE();
        ctredt.actionSave();
  //      ctredt.gotoNext();
        ctredt.gotoProducts();
        ctredt.actionSelected();
        ctredt.getInstallationService();
  //      ctredt.actionInstallation();
    }   
    
    static testMethod void ProductAccesorries_Test0_pe(){
        
        DataInsertFactory.insertQuote();
                    
        List<SBQQ__Quote__c> lstTestQuote = new List<SBQQ__Quote__c>();
        lstTestQuote = [SELECT Id FROM SBQQ__Quote__c ORDER BY Id];
        
        List<Product2> lstTestProduct = new List<Product2>();
        lstTestProduct = [SELECT Id, ProductCode FROM Product2 ORDER BY Id];
        
        List<Product_Pricing__c> lstTestPP = new List<Product_Pricing__c>();
        Product_Pricing__c test_PP_1 = new Product_Pricing__c();
        
        for(Product2 tp:lstTestProduct){
            test_PP_1 = new Product_Pricing__c();
        	test_PP_1.Material_Number__c = tp.ProductCode;
        	test_PP_1.Price__c = 500;
        	test_PP_1.Cost__c = 250;
        	lstTestPP.add(test_PP_1);
        }
        insert lstTestPP;
        
        List<Quote_Line_Staging__c> lstTestQLS = new List<Quote_Line_Staging__c>();
        lstTestQLS = [SELECT Id, Product__c, ProductParentUnique__c FROM Quote_Line_Staging__c ORDER BY Id];
        
        PageReference pageRef = Page.ProductAccesorries; 
        pageRef.getParameters().put('id', lstTestQuote[0].Id);
        pageRef.getParameters().put('prodid', lstTestQLS[0].Product__c);
        pageRef.getParameters().put('pe', lstTestQLS[0].ProductParentUnique__c);

        Test.setCurrentPage(pageRef);
        
            
        ProductAccesorriesController ctredt = new ProductAccesorriesController();
        ctredt.redirectQLE();
        ctredt.actionSave();
  //      ctredt.gotoNext();
        ctredt.gotoProducts();
        ctredt.actionSelected();
        ctredt.getInstallationService();
  //      ctredt.actionInstallation();
    }   
    
    
}