force-app/main/default/objects/Campaign_Territory_Management_Exception__c/Campaign_Territory_Management_Exception__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of campaigns that need to bypass auto assignment rules and go straight to DM</description>
    <label>Campaign Territory Management Exception</label>
</CustomObject>

force-app/main/default/objects/Common_Variables__c/Common_Variables__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to define common variables utilized by Apex to avoid hard coding items or using items that can change such as userIds or Stages/Statuses.</description>
    <label>Common Variables</label>
</CustomObject>

force-app/main/default/objects/Common_Variables__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Used to define the content of the variable to be referenced in Apex.</description>
    <label>Content</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If the referral source is a Contact (and not a user of Salesforce.com), enter the Contact Name here.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referral Partner Contact</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Estimated_Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Opportunity_Amount__c</fullName>
    <description>The dollar amount of an opportunity is determined by the amount of the estimated spend for that specific bid, project, or actual business development opportunity.</description>
    <inlineHelpText>The dollar amount of an opportunity is determined by the amount of the estimated spend for that specific bid, project, or actual business development opportunity.</inlineHelpText>
    <label>Estimated Opportunity Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Cycle_Log__c.field-meta.xml
<CustomField>
    <fullName>Sales_Cycle_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Cycle Log</label>
    <referenceTo>Sales_Cycle_Log__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Toggle__c/Round_Robin_Toggle__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to define whether or not to use Round Robin for territory management functionality</description>
    <label>Round Robin Toggle</label>
</CustomObject>

force-app/main/default/objects/Round_Robin_Toggle__c/fields/Round_Robin_Active__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, leads will be put through the districts round robin porcess</description>
    <label>Round Robin Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log__c/Sales_Cycle_Log__c.object-meta.xml
<CustomObject>
    <description>Tracks IST person and date/time of Lead Status change</description>
    <label>Sales Cycle Log</label>
    <nameField>
        <displayFormat>SCL-{00000}</displayFormat>
        <label>Sales Cycle Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Cycle Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Cycle_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Cycle Logs</relationshipLabel>
    <relationshipName>Sales_Cycle_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Cycle Log</relationshipLabel>
    <relationshipName>Sales_Cycle_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Sales Cycle Log</relationshipLabel>
    <relationshipName>IST_Lead_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Cycle_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Cycle Logs</relationshipLabel>
    <relationshipName>Sales_Cycle_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Default task, copied from &quot;Master&quot;.</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This object is for the custom territory list provided by SAP.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Is_Current_Round_Robin_Selection__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Round_Robin_Selection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Round Robin Selection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadHandler.cls
public class LeadHandler implements ITrigger {

    Map<String, String> postalCodeMap = new Map<String, String>();    
    List<Lead> leadsToUpdate = new List<Lead>();
    List<Task> tasksToUpdate = new List<Task>();
    List<Sales_Cycle_Log__c> sclToUpdate = new List<Sales_Cycle_Log__c>();
    //List<User> usersToUpdate = new List<User>();
    Map<String, List<Territory2>> territoryChildrenMap = new Map<String, List<Territory2>>();
    Map<Id, Boolean> usersToUpdate = new Map<Id, Boolean>();
    Map<String, List<Campaign>> leadCampaigns = new Map<String, List<Campaign>>();
    Map<String, List<Task>> leadTasks = new Map<String, List<Task>>();
     Map<Id, Sales_Cycle_Log__c> sclEntries = new Map<Id, Sales_Cycle_Log__c>();        
            
    public LeadHandler(){        
    }

    public void bulkBefore(){
        if(!Trigger.isDelete){
            List<String> postalCodes = new List<String>();
            List<Id> leadId = new List<Id>();

            For( Lead newLead :(List<Lead>)Trigger.new){
                if(String.isNotBlank(newLead.PostalCode)){
                    postalCodes.add(newLead.PostalCode.Left(5));
                }
                if(Trigger.isUpdate){
                    leadId.add(newLead.Id);
                }
            }

            postalCodeMap = TerritoryUtils.getDistrictMapping(postalCodes);       
            
            if(Trigger.isUpdate){     
                TerritoryUtils.getTerritoryUsers();
                TerritoryUtils.getChildrenTerritories(False);
                leadCampaigns = CommonUtils.getLeadCampaigns(leadId);                  
            }
        }
    }

    public void bulkAfter(){   
        if(!Trigger.isDelete){
            if(Trigger.isUpdate){
                List<Id> leadId = new List<Id>();
                List<Id> convertedLeadIds = new List<Id>();
                Map<Id, Id> mapLeadOwners = new Map<Id, Id>();

                For( Lead newLead :(List<Lead>)Trigger.new){
                    leadId.add(newLead.Id);                    
                    mapLeadOwners.put(newLead.Id, newLead.OwnerId);

                    if(newLead.isConverted){
                        convertedLeadIds.add(newLead.Id);
                    }
                }

                for(Sales_Cycle_Log__c scl : [select Contact__c, Opportunity__c, Account__c, Lead__c from Sales_Cycle_Log__c where lead__c in :convertedLeadIds ORDER BY LastModifiedDate DESC]){
                    if(!sclEntries.containsKey(scl.Lead__c)){
                        sclEntries.put(scl.Lead__c,scl);
                    }
                }


                tasksToUpdate = CommonUtils.updateTaskOwner(leadId, Lead.sObjecttype, mapLeadOwners);
            }
        }
    }

    public void beforeInsert(Sobject obj){
        Lead newObject = (Lead)obj;
        String newPostalCode = String.isNotBlank(newObject.PostalCode) ? newObject.PostalCode.Left(5) : '';

        //Territory Assignment
        if(postalCodeMap.containsKey(newPostalCode)){
            newObject.Territory__c = postalCodeMap.get(newPostalCode);
        }
    }

    public void beforeUpdate(Sobject oldObj, Sobject newObj){        
        Lead oldLead = (Lead)oldObj;
        Lead newLead = (Lead)newObj;
        String oldPostalCode = String.isNotBlank(oldLead.PostalCode) ? oldLead.PostalCode.Left(5) : '';
        String newPostalCode = String.isNotBlank(newLead.PostalCode) ? newLead.PostalCode.Left(5) : '';

        if((newPostalCode != oldPostalCode || String.isBlank(oldLead.Territory__c)) && postalCodeMap.containsKey(newPostalCode)){ 
            newLead.Territory__c = postalCodeMap.get(newPostalCode);
        }   

        //If we are not a field user, auto assign user on status change
        if(oldLead.Status != newLead.Status && newLead.Status == Common_Variables__c.getInstance('Auto Assignment Status Change').Content__c && String.isNotBlank(newLead.Territory__c)){
            String dm = null;
            Boolean dmRoute = false;
            Boolean childTerritoryFound = false;

            List<Campaign_Territory_Management_Exception__c> exceptionList = Campaign_Territory_Management_Exception__c.getall().values();

            //check custom settings for Campaign Ids that should bypass TM and go to DM
            //System.debug('***** member : campaigns - ' + leadCampaigns.size() + ' : ' +exceptionList.size());
            if(exceptionList != null && exceptionList.size() > 0 && leadCampaigns != null && leadCampaigns.containsKey(newLead.Id)){
                for(Campaign_Territory_Management_Exception__c exc : exceptionList){
                    for(Campaign cmp : leadCampaigns.get(newLead.Id)){
                        if(exc.CampaignId__c == cmp.Id){
                            dmRoute = true;
                            System.debug('***** camp exception found');
                        }
                    }
                }
            }

            String correctTerritory = TerritoryUtils.checkForChildTerritory(newLead,Lead.sObjectType,TerritoryUtils.childTerritories.get(newLead.Territory__c));

            //if we have a child territory don't send to DM
            if(correctTerritory != newLead.Territory__c && !dmRoute){
                childTerritoryFound = true;
            }

            if(dmRoute || (!Round_Robin_Toggle__c.getInstance(newLead.Territory__c).Round_Robin_Active__c && newLead.Estimated_Opportunity_Amount__c >= Decimal.valueOf(Common_Variables__c.getInstance('IST Lead Dollar Amount').Content__c))){
                dm = TerritoryUtils.getDistrictManager(newLead.Territory__c, TerritoryUtils.territoryUserMap.get(newLead.Territory__c));
                System.debug('***** DM - ' + dm);
            }

            if(String.isNotBlank(dm) && !childTerritoryFound){
                newLead.OwnerId = dm;
            }
            else{
                
                sObject result = CommonUtils.autoAssignOwner(newLead, Lead.sObjectType, TerritoryUtils.territoryUserMap.get(correctTerritory));

                if(result != null){
                    Lead leadResult = (Lead)result;
                    System.debug('***** ' + leadResult.OwnerId + ' - ' + newLead.OwnerId);
                    System.debug('***** ' + CommonUtils.userAssigned);

                    //If an actual user was assigned, update flags on user accounts
                    if(CommonUtils.userAssigned){
                        System.debug('***** user assigned');
                        for(User user : TerritoryUtils.territoryUserMap.get(correctTerritory)){
                            System.debug('***** ' + user.LastName);
                            if(user.Is_Current_Round_Robin_Selection__c){
                                usersToUpdate.put(user.Id, false);
                                continue;
                            }

                            if(user.Id == leadResult.OwnerId){
                                usersToUpdate.put(user.Id, true);
                                continue;
                            }
                        }
                    }
                }
            }
        }     
    }

    public  void beforeDelete(Sobject obj){

    }

    public void afterInsert(Sobject obj){
        
    }

    public void afterUpdate(Sobject oldObj, Sobject newObj){      
        Lead oldLead = (Lead)oldObj;
        Lead newLead = (Lead)newObj;

        if(newLead.isConverted && oldLead.isConverted != newLead.isConverted && sclEntries.containsKey(newLead.Id)){
            Sales_Cycle_Log__c scl = sclEntries.get(newLead.Id);
            scl.contact__c = newLead.ConvertedContactId;
            scl.opportunity__c = newLead.ConvertedOpportunityId;
            scl.account__c = newLead.ConvertedAccountId;

            sclToUpdate.add(scl);
        }
    }

    public void afterDelete(Sobject obj){

    }

    public void andFinally(){
        if(usersToUpdate.size() > 0){
            updateUsers(usersToUpdate);
        }
        if(tasksToUpdate.size() > 0){
            update tasksToUpdate;
        }
        if(sclToUpdate.size() > 0){
            update sclToUpdate;
        }
    }

    //***************************Helper Methods******************************
    @future
    private static void updateUsers(Map<Id, Boolean> userMap){
        List<User> users = [SELECT Id, Is_Current_Round_Robin_Selection__c FROM User WHERE Id IN :userMap.keySet()];

        if(users != null){
            for(User user : users){
                user.Is_Current_Round_Robin_Selection__c = userMap.get(user.Id);
            }
            update users;
        }
    }
}