force-app/main/default/objects/Sales_Order_Header__c/Sales_Order_Header__c.object-meta.xml
<CustomObject>
    <label>Sales Order Header</label>
    <nameField>
        <displayFormat>SOH-{000000}</displayFormat>
        <label>Sales Order Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Header__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesOrderPurgeBatchClass.cls
public class SalesOrderPurgeBatchClass implements Database.Batchable<sObject> {
	
	private String query = 'SELECT Id FROM Sales_Order_Header__c WHERE Order_Status__c = \'' + 'Completed' + '\'' + ' AND Create_Date_Time__c < ' + datetime.now().addDays(-30).format('YYYY-MM-dd');

	public SalesOrderPurgeBatchClass() {
		
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('***** ' + query);
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		System.debug('***** ' + scope.size());

		if(scope != null && scope.size() > 0){
			delete scope;
		}
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}