force-app/main/default/objects/Delivery_Estimate__c/Delivery_Estimate__c.object-meta.xml
<CustomObject>
    <label>Delivery Estimate</label>
    <nameField>
        <label>Delivery Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Estimate__c/fields/Building_Count__c.field-meta.xml
<CustomField>
    <fullName>Building_Count__c</fullName>
    <description>How many buildings does the delivery site consist of?</description>
    <inlineHelpText>How many buildings does the delivery site consist of?</inlineHelpText>
    <label>Building Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Floors_Per_Building__c.field-meta.xml
<CustomField>
    <fullName>Floors_Per_Building__c</fullName>
    <label>How many floors per building</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Estimates</relationshipLabel>
    <relationshipName>Delivery_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Delivery Estimates</relationshipLabel>
    <relationshipName>Delivery_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Units_Per_Building__c.field-meta.xml
<CustomField>
    <fullName>Units_Per_Building__c</fullName>
    <label>How many units per building</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Units_Per_Floor__c.field-meta.xml
<CustomField>
    <fullName>Units_Per_Floor__c</fullName>
    <label>How many units per floor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate__c/fields/Units_per_week__c.field-meta.xml
<CustomField>
    <fullName>Units_per_week__c</fullName>
    <label>How many units per week</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Estimate_Feedback__c/Delivery_Estimate_Feedback__c.object-meta.xml
<CustomObject>
    <label>Delivery Estimate Feedback</label>
    <nameField>
        <displayFormat>DEF-{00000}</displayFormat>
        <label>Delivery Estimate Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Estimate Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Estimate_Feedback__c/fields/Delivery_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Estimate__c</fullName>
    <label>Delivery Estimate</label>
    <referenceTo>Delivery_Estimate__c</referenceTo>
    <relationshipLabel>Delivery Estimate Feedbacks</relationshipLabel>
    <relationshipName>Delivery_Estimate_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduleTestClasses.cls
@isTest
public class ScheduleTestClasses {
    
    static testMethod void test_ScheduledProductDocuments(){
         Test.StartTest();   
       DataInsertFactory.insertQuote();
        
       ScheduledProductDocuments rt = new ScheduledProductDocuments();
       String srt = '0 13 * * * ?';
       String jobID = system.schedule('ScheduledProductDocumentsTest', srt, rt);
        
       ScheduledQuoteApproval rt2 = new ScheduledQuoteApproval();
       String srt2 = '0 13 * * * ?';
       String jobID2 = system.schedule('ScheduledQuoteApprovalTest', srt2, rt2);

        List<SBQQ__Quote__c> lstTestQuote = new List<SBQQ__Quote__c>();
        lstTestQuote = [SELECT Id FROM SBQQ__Quote__c ORDER BY Id];
        List<Id> lstQuoteId = new List<Id>();
        lstQuoteId.add(lstTestQuote[0].Id);
        QuoteBusinessHours.quoteBusiensshour_method(lstQuoteId);
        
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        lstOpportunity = [SELECT Id FROM Opportunity ORDER BY Id];
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(lstOpportunity);
        QuoteFlowButtonController ctrlqfb = new QuoteFlowButtonController(sc);
        ctrlqfb.redirectNewQuote();
        QuoteProjectButtonController ctrlqpb = new QuoteProjectButtonController(sc);
        ctrlqpb.redirectNewQuote();
        
        List<Delivery_Estimate__c> lstTestDeliveryEstimate = new List<Delivery_Estimate__c>();
        Delivery_Estimate__c test_de_1 = new Delivery_Estimate__c();
        test_de_1.Quote__c = lstTestQuote[0].Id;
        test_de_1.Opportunity_Name__c = lstOpportunity[0].Id;
        test_de_1.Building_Count__c = 1;
        test_de_1.Floors_Per_Building__c = 1;
        test_de_1.Units_Per_Building__c = 1;
        test_de_1.Units_Per_Floor__c = 1;
        test_de_1.Units_per_week__c = 1;
        lstTestDeliveryEstimate.add(test_de_1);
        insert lstTestDeliveryEstimate;
        
        List<Delivery_Estimate__c> lstTestDeliveryEstimateQry = new List<Delivery_Estimate__c>();
        lstTestDeliveryEstimateQry = [SELECT Id FROM Delivery_Estimate__c ORDER BY Id];
        
        List<Delivery_Estimate_Feedback__c> lstTestDeliveryEstimateFeedback = new List<Delivery_Estimate_Feedback__c>();
        Delivery_Estimate_Feedback__c test_def_1 = new Delivery_Estimate_Feedback__c();
        test_def_1.Delivery_Estimate__c = lstTestDeliveryEstimateQry[0].Id;
        lstTestDeliveryEstimateFeedback.add(test_def_1);
        insert lstTestDeliveryEstimateFeedback;
        
        List<Delivery_Estimate_Feedback__c> lstTestDeliveryEstimateFeedbackQry = new List<Delivery_Estimate_Feedback__c>();
        lstTestDeliveryEstimateFeedbackQry = [SELECT Id FROM Delivery_Estimate_Feedback__c ORDER BY Id];
        
        update lstTestDeliveryEstimateFeedback;
        delete lstTestDeliveryEstimateFeedback;
        
        PageReference pageRef2 = Page.RouteDeliveryEstimate; 
        pageRef2.getParameters().put('id', lstTestDeliveryEstimateQry[0].Id);
        Test.setCurrentPage(pageRef2);
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(lstTestDeliveryEstimateQry[0]);
        RouteDeliveryEstimateController ctrlrde = new RouteDeliveryEstimateController(sc2);
        ctrlrde.routeHandler();
        
         Test.stopTest();   
    }
}