force-app/main/default/objects/Delivery_Estimate__c/Delivery_Estimate__c.object-meta.xml
<CustomObject>
    <label>Delivery Estimate</label>
    <nameField>
        <label>Delivery Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Estimate__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Delivery Estimates</relationshipLabel>
    <relationshipName>Delivery_Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Delivery_Charge__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charge__c</fullName>
    <label>Delivery Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/isDeliveryEstimate__c.field-meta.xml
<CustomField>
    <fullName>isDeliveryEstimate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDeliveryEstimate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeliveryEstimateFeedbackHandler.cls
public class DeliveryEstimateFeedbackHandler implements ITrigger {
    
        public void bulkBefore() {}
    
    public void bulkAfter() {}
    
    public void beforeInsert(Sobject obj) {/*
        system.debug('Delivery_Estimate__c--> ' +  String.valueOf(obj.getSObject('Delivery_Estimate__c').get('Quote__c')) );
        List<SBQQ__Quote__c> lstQuoteDeliveryUpdate = new List<SBQQ__Quote__c>();
        lstQuoteDeliveryUpdate = [SELECT Id, Name, isDeliveryEstimate__c, Delivery_Charge__c FROM SBQQ__Quote__c WHERE Id=:String.valueOf(obj.getSObject('Delivery_Estimate__c').get('Quote__c')) LIMIT 1];
        system.debug('lstQuoteDeliveryUpdate.size()--> ' +  lstQuoteDeliveryUpdate.size() );
        if(lstQuoteDeliveryUpdate.size()>0){
            for(SBQQ__Quote__c ld:lstQuoteDeliveryUpdate){
                if(Double.valueOf(Obj.get('Recommended_Delivery__c'))!=null  ){
                ld.isDeliveryEstimate__c = false;
                ld.Delivery_Charge__c = Double.valueOf(Obj.get('Recommended_Delivery__c'));
                }
            }
            update lstQuoteDeliveryUpdate;
        }*/
    }
    
    public void beforeUpdate(Sobject oldObj, Sobject newObj) {}
    
    public void beforeDelete(Sobject obj) {}
    
    public void afterInsert(Sobject obj) {
        
        String quoteId='';
        List<Delivery_Estimate__c> lstDeliveryEstimate = new List<Delivery_Estimate__c>();
        lstDeliveryEstimate = [SELECT Id, Quote__c FROM Delivery_Estimate__c WHERE Id=:String.valueOf(obj.get('Delivery_Estimate__c')) LIMIT 1];
        if(lstDeliveryEstimate.size()>0){
            for(Delivery_Estimate__c de:lstDeliveryEstimate){
                if(de.Quote__c!=null  ){
                	quoteId = de.Quote__c;
                }
            }
        }
        
        
        system.debug('quoteId--> ' +  quoteId );
        List<SBQQ__Quote__c> lstQuoteDeliveryUpdate = new List<SBQQ__Quote__c>();
        lstQuoteDeliveryUpdate = [SELECT Id, Name, isDeliveryEstimate__c, Delivery_Charge__c FROM SBQQ__Quote__c WHERE Id=:quoteId LIMIT 1];
        if(lstQuoteDeliveryUpdate.size()>0){
            for(SBQQ__Quote__c ld:lstQuoteDeliveryUpdate){
                if(Double.valueOf(Obj.get('Recommended_Delivery__c'))!=null  ){
                ld.isDeliveryEstimate__c = false;
                ld.Delivery_Charge__c = Double.valueOf(Obj.get('Recommended_Delivery__c'));
                }
            }
            update lstQuoteDeliveryUpdate;
        }
    }
    
    public void afterUpdate(Sobject oldObj, Sobject newObj) {}
    
    public void afterDelete(Sobject obj) {}
    
    public void andFinally() {}

}